// @generated
// This file is @generated by prost-build.
/// A registered transformation/derivation that can be applied to items in a
/// media set (e.g. thumbnail, waveform, OCR, HLS segments, geo tile).
///
/// `kind` is a free-form discriminator interpreted by the worker that runs
/// the pattern (Pipeline Builder transform, ML model, geo tiler, ...).
/// `params` is a JSON blob with kind-specific configuration.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccessPattern {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub media_set_rid: ::prost::alloc::string::String,
    /// Kind of pattern, e.g. `thumbnail`, `waveform`, `ocr`, `hls`, `geo_tile`.
    #[prost(string, tag="3")]
    pub kind: ::prost::alloc::string::String,
    /// Kind-specific configuration as a JSON-encoded string.
    #[prost(string, tag="4")]
    pub params: ::prost::alloc::string::String,
    #[prost(enumeration="PersistencePolicy", tag="5")]
    pub persistence: i32,
    /// TTL in seconds; only consulted when `persistence = CACHE_TTL`.
    #[prost(int64, tag="6")]
    pub ttl_seconds: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterAccessPatternRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub params: ::prost::alloc::string::String,
    #[prost(enumeration="PersistencePolicy", tag="4")]
    pub persistence: i32,
    #[prost(int64, tag="5")]
    pub ttl_seconds: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAccessPatternsRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAccessPatternsResponse {
    #[prost(message, repeated, tag="1")]
    pub patterns: ::prost::alloc::vec::Vec<AccessPattern>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunAccessPatternRequest {
    #[prost(string, tag="1")]
    pub access_pattern_id: ::prost::alloc::string::String,
    /// Item to apply the pattern to.
    #[prost(string, tag="2")]
    pub media_item_rid: ::prost::alloc::string::String,
    /// Optional override of the registered params, JSON-encoded.
    #[prost(string, tag="3")]
    pub params_override: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunAccessPatternResponse {
    /// Presigned URL pointing to the computed/cached artifact.
    #[prost(string, tag="1")]
    pub result_url: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub size_bytes: i64,
    /// True if the result was served from cache or persisted storage.
    #[prost(bool, tag="4")]
    pub cached: bool,
}
/// How derived outputs of an access pattern are stored.
///
/// - RECOMPUTE: never persist; re-run the pattern on every request.
/// - PERSIST: write the derived artifact alongside the source media item.
/// - CACHE_TTL: cache for `ttl_seconds` and recompute after expiry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PersistencePolicy {
    Unspecified = 0,
    Recompute = 1,
    Persist = 2,
    CacheTtl = 3,
}
impl PersistencePolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PERSISTENCE_POLICY_UNSPECIFIED",
            Self::Recompute => "PERSISTENCE_POLICY_RECOMPUTE",
            Self::Persist => "PERSISTENCE_POLICY_PERSIST",
            Self::CacheTtl => "PERSISTENCE_POLICY_CACHE_TTL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PERSISTENCE_POLICY_UNSPECIFIED" => Some(Self::Unspecified),
            "PERSISTENCE_POLICY_RECOMPUTE" => Some(Self::Recompute),
            "PERSISTENCE_POLICY_PERSIST" => Some(Self::Persist),
            "PERSISTENCE_POLICY_CACHE_TTL" => Some(Self::CacheTtl),
            _ => None,
        }
    }
}
/// A collection of media items (unstructured files) sharing a common schema.
///
/// `rid` is a Foundry-style resource identifier
/// (`ri.foundry.main.media_set.<uuid>`). When `virtual` is true the items
/// are read directly from `source_rid` (an external system) rather than
/// from OpenFoundry-managed object storage.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaSet {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub project_rid: ::prost::alloc::string::String,
    #[prost(enumeration="MediaSetSchema", tag="4")]
    pub schema: i32,
    /// Allowed MIME types. Empty = inferred from `schema`.
    #[prost(string, repeated, tag="5")]
    pub allowed_mime_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="TransactionPolicy", tag="6")]
    pub transaction_policy: i32,
    /// Retention window in seconds. `0` means retain forever.
    #[prost(int64, tag="7")]
    pub retention_seconds: i64,
    /// True when the media set is virtual (data lives in `source_rid`).
    #[prost(bool, tag="8")]
    pub r#virtual: bool,
    /// External source RID for virtual media sets (data-connection source).
    #[prost(string, optional, tag="9")]
    pub source_rid: ::core::option::Option<::prost::alloc::string::String>,
    /// Marking RIDs (security classifications) attached to the media set.
    #[prost(string, repeated, tag="10")]
    pub markings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="11")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag="12")]
    pub created_by: ::prost::alloc::string::String,
}
/// A single file inside a media set.
///
/// `path` is the logical key (typically the original filename); uploads to
/// the same path overwrite the previous item but keep prior versions
/// reachable through the immutable `rid` (Foundry path-deduplication).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaItem {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub branch: ::prost::alloc::string::String,
    /// RID of the transaction that wrote this item; empty for transactionless
    /// media sets.
    #[prost(string, tag="4")]
    pub transaction_rid: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag="7")]
    pub size_bytes: i64,
    #[prost(string, tag="8")]
    pub sha256: ::prost::alloc::string::String,
    /// Free-form metadata blob (JSON-encoded).
    #[prost(string, tag="9")]
    pub metadata: ::prost::alloc::string::String,
    #[prost(message, optional, tag="10")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    /// RID of the prior item this one replaced via path deduplication.
    #[prost(string, optional, tag="11")]
    pub deduplicated_from: ::core::option::Option<::prost::alloc::string::String>,
}
/// A write batch on a transactional media set branch.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Transaction {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub branch: ::prost::alloc::string::String,
    #[prost(enumeration="TransactionState", tag="4")]
    pub state: i32,
    #[prost(message, optional, tag="5")]
    pub opened_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub closed_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag="7")]
    pub opened_by: ::prost::alloc::string::String,
}
/// Media schema accepted by a media set. Mirrors the Foundry-documented
/// "permitted file formats" taxonomy (image, audio, video, document,
/// spreadsheet, email).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MediaSetSchema {
    Unspecified = 0,
    Image = 1,
    Audio = 2,
    Video = 3,
    Document = 4,
    Spreadsheet = 5,
    Email = 6,
}
impl MediaSetSchema {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MEDIA_SET_SCHEMA_UNSPECIFIED",
            Self::Image => "MEDIA_SET_SCHEMA_IMAGE",
            Self::Audio => "MEDIA_SET_SCHEMA_AUDIO",
            Self::Video => "MEDIA_SET_SCHEMA_VIDEO",
            Self::Document => "MEDIA_SET_SCHEMA_DOCUMENT",
            Self::Spreadsheet => "MEDIA_SET_SCHEMA_SPREADSHEET",
            Self::Email => "MEDIA_SET_SCHEMA_EMAIL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEDIA_SET_SCHEMA_UNSPECIFIED" => Some(Self::Unspecified),
            "MEDIA_SET_SCHEMA_IMAGE" => Some(Self::Image),
            "MEDIA_SET_SCHEMA_AUDIO" => Some(Self::Audio),
            "MEDIA_SET_SCHEMA_VIDEO" => Some(Self::Video),
            "MEDIA_SET_SCHEMA_DOCUMENT" => Some(Self::Document),
            "MEDIA_SET_SCHEMA_SPREADSHEET" => Some(Self::Spreadsheet),
            "MEDIA_SET_SCHEMA_EMAIL" => Some(Self::Email),
            _ => None,
        }
    }
}
/// How writes are sealed on a media set.
///
/// Foundry default is `TRANSACTIONLESS` — items are visible immediately and
/// cannot be rolled back. `TRANSACTIONAL` mirrors dataset semantics: writes
/// are staged in an open transaction and only visible after commit.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransactionPolicy {
    Unspecified = 0,
    Transactionless = 1,
    Transactional = 2,
}
impl TransactionPolicy {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRANSACTION_POLICY_UNSPECIFIED",
            Self::Transactionless => "TRANSACTION_POLICY_TRANSACTIONLESS",
            Self::Transactional => "TRANSACTION_POLICY_TRANSACTIONAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSACTION_POLICY_UNSPECIFIED" => Some(Self::Unspecified),
            "TRANSACTION_POLICY_TRANSACTIONLESS" => Some(Self::Transactionless),
            "TRANSACTION_POLICY_TRANSACTIONAL" => Some(Self::Transactional),
            _ => None,
        }
    }
}
/// Lifecycle of a transactional write batch on a media set branch.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TransactionState {
    Unspecified = 0,
    Open = 1,
    Committed = 2,
    Aborted = 3,
}
impl TransactionState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TRANSACTION_STATE_UNSPECIFIED",
            Self::Open => "TRANSACTION_STATE_OPEN",
            Self::Committed => "TRANSACTION_STATE_COMMITTED",
            Self::Aborted => "TRANSACTION_STATE_ABORTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSACTION_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "TRANSACTION_STATE_OPEN" => Some(Self::Open),
            "TRANSACTION_STATE_COMMITTED" => Some(Self::Committed),
            "TRANSACTION_STATE_ABORTED" => Some(Self::Aborted),
            _ => None,
        }
    }
}
// ---------------------------------------------------------------------------
// Media set CRUD
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateMediaSetRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub project_rid: ::prost::alloc::string::String,
    #[prost(enumeration="MediaSetSchema", tag="3")]
    pub schema: i32,
    /// Optional MIME-type allow list. Empty = inferred from `schema`.
    #[prost(string, repeated, tag="4")]
    pub allowed_mime_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="TransactionPolicy", tag="5")]
    pub transaction_policy: i32,
    /// 0 = retain forever.
    #[prost(int64, tag="6")]
    pub retention_seconds: i64,
    /// Virtual media set: data stays in `source_rid`, never copied.
    #[prost(bool, tag="7")]
    pub r#virtual: bool,
    #[prost(string, optional, tag="8")]
    pub source_rid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="9")]
    pub markings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMediaSetRequest {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMediaSetsRequest {
    #[prost(string, tag="1")]
    pub project_rid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMediaSetsResponse {
    #[prost(message, repeated, tag="1")]
    pub media_sets: ::prost::alloc::vec::Vec<MediaSet>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMediaSetRequest {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMediaSetResponse {
}
// ---------------------------------------------------------------------------
// Transactions
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenTransactionRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub branch: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommitTransactionRequest {
    #[prost(string, tag="1")]
    pub transaction_rid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AbortTransactionRequest {
    #[prost(string, tag="1")]
    pub transaction_rid: ::prost::alloc::string::String,
}
// ---------------------------------------------------------------------------
// Media items
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMediaItemsRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub branch: ::prost::alloc::string::String,
    /// Optional path prefix filter.
    #[prost(string, tag="3")]
    pub path_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMediaItemsResponse {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<MediaItem>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMediaItemRequest {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMediaItemRequest {
    #[prost(string, tag="1")]
    pub rid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMediaItemResponse {
}
// ---------------------------------------------------------------------------
// Presigned URLs
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GeneratePresignedUploadUrlRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub branch: ::prost::alloc::string::String,
    /// Logical path (filename) inside the media set.
    #[prost(string, tag="3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub mime_type: ::prost::alloc::string::String,
    /// Required for transactional policy; empty otherwise.
    #[prost(string, tag="5")]
    pub transaction_rid: ::prost::alloc::string::String,
    /// Lifetime of the presigned URL.
    #[prost(int64, tag="6")]
    pub expires_in_seconds: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GeneratePresignedDownloadUrlRequest {
    #[prost(string, tag="1")]
    pub media_item_rid: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub expires_in_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresignedUrlResponse {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    /// Required HTTP headers to include with the request (e.g. `Content-Type`).
    #[prost(map="string, string", tag="2")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub expires_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
// ---------------------------------------------------------------------------
// Virtual media sets
// ---------------------------------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterVirtualMediaItemRequest {
    #[prost(string, tag="1")]
    pub media_set_rid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub branch: ::prost::alloc::string::String,
    /// Path inside the external source (e.g. `s3://bucket/key.png`).
    #[prost(string, tag="3")]
    pub physical_path: ::prost::alloc::string::String,
    /// Logical path inside the media set (used for listings and dedup).
    #[prost(string, tag="4")]
    pub item_path: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag="6")]
    pub size_bytes: i64,
    #[prost(string, tag="7")]
    pub sha256: ::prost::alloc::string::String,
}
include!("open_foundry.media_set.tonic.rs");
// @@protoc_insertion_point(module)