// @generated
// This file is @generated by prost-build.
/// ExecuteInlineFunctionRequest carries the JSON envelope assembled by
/// the Go caller. `input_json` is the same shape Rust passed to PyO3:
/// `{ context: { action, targetObject, parameters, objectSet,
///     linkedObjects, justification, contextNow }, policy,
///     functionPackage, serviceToken, ontologyServiceUrl, aiServiceUrl }`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteInlineFunctionRequest {
    #[prost(string, tag="1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub input_json: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub timeout_seconds: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteInlineFunctionResponse {
    /// Raw JSON of the Python function's return value (already enriched
    /// with `stdout` / `stderr` arrays when the runtime added them).
    #[prost(string, tag="1")]
    pub result_json: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub stderr: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub error: ::prost::alloc::string::String,
}
/// ExecutePipelineTransformRequest mirrors the locals injected by the
/// Rust pipeline transform: the user source plus three JSON blobs.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutePipelineTransformRequest {
    #[prost(string, tag="1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub config_json: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub prepared_inputs_json: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub input_dataset_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub output_dataset_id: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub timeout_seconds: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutePipelineTransformResponse {
    /// Optional: -1 sentinel means "not set" (proto3 ints are not nullable).
    #[prost(int64, tag="1")]
    pub rows_affected: i64,
    #[prost(bool, tag="2")]
    pub rows_affected_set: bool,
    /// JSON: { stdout, result, sample_rows }
    #[prost(string, tag="3")]
    pub output_json: ::prost::alloc::string::String,
    /// JSON array of row objects when the transform set `result_rows`.
    #[prost(string, tag="4")]
    pub result_rows_json: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteNotebookCellRequest {
    /// 16-byte UUID (or zero-length when stateless).
    #[prost(bytes="vec", tag="1")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub workspace_dir: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="4")]
    pub notebook_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub timeout_seconds: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteNotebookCellResponse {
    #[prost(string, tag="1")]
    pub output_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub content_json: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnsureSessionRequest {
    #[prost(bytes="vec", tag="1")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnsureSessionResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropSessionRequest {
    #[prost(bytes="vec", tag="1")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropSessionResponse {
}
include!("runtime.tonic.rs");
// @@protoc_insertion_point(module)