package com.openfoundry.sdk;

// This file is generated by `go run ./tools/of-cli docs generate-sdk-java`.
// Do not edit manually.

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

public final class OpenFoundryClient {
    private final String baseUrl;
    private final HttpClient httpClient;
    private final Map<String, String> defaultHeaders;

    public OpenFoundryClient(String baseUrl) {
        this(baseUrl, HttpClient.newHttpClient(), Map.of());
    }

    public OpenFoundryClient(String baseUrl, HttpClient httpClient, Map<String, String> headers) {
        this.baseUrl = baseUrl.endsWith("/") ? baseUrl.substring(0, baseUrl.length() - 1) : baseUrl;
        this.httpClient = httpClient;
        this.defaultHeaders = new LinkedHashMap<>(headers);
    }

    public String authRbacAssignrole(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/assign-role", pathParams, queryParams, bodyJson);
    }

    public String authAuthGetme() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/auth/get-me", pathParams, queryParams, null);
    }

    public String authRbacListroles() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/auth/list-roles", pathParams, queryParams, null);
    }

    public String authAuthLogin(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/login", pathParams, queryParams, bodyJson);
    }

    public String authAuthRefreshtoken(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/refresh-token", pathParams, queryParams, bodyJson);
    }

    public String authAuthRegister(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/auth/register", pathParams, queryParams, bodyJson);
    }

    public String commonHealthCheck(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/common/check", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationIngestjobCancelingestjob(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/cancel-ingest-job", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorCreateconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/create-connection", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorDeleteconnection(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/data-integration/delete-connection", pathParams, queryParams, null);
    }

    public String dataIntegrationIngestjobGetingestjob(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("GET", "/api/v1/data-integration/get-ingest-job", pathParams, queryParams, null);
    }

    public String dataIntegrationConnectorInferschema(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/infer-schema", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorListconnections(String pagination) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        return request("GET", "/api/v1/data-integration/list-connections", pathParams, queryParams, null);
    }

    public String dataIntegrationIngestjobListingestjobs(String connectionId, String pagination) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (connectionId != null) { queryParams.put("connection_id", connectionId); }
        if (pagination != null) { queryParams.put("pagination", pagination); }
        return request("GET", "/api/v1/data-integration/list-ingest-jobs", pathParams, queryParams, null);
    }

    public String dataIntegrationIngestjobQueueingestjob(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/queue-ingest-job", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorSyncconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/sync-connection", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationConnectorTestconnection(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/test-connection", pathParams, queryParams, bodyJson);
    }

    public String dataIntegrationIngestjobWatchingestjob(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/data-integration/watch-ingest-job", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetCreatedataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/datasets/create-dataset", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetDeletedataset(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/datasets/delete-dataset", pathParams, queryParams, null);
    }

    public String datasetDatasetGetdataset(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("GET", "/api/v1/datasets/get-dataset", pathParams, queryParams, null);
    }

    public String datasetDatasetGetversions(String datasetId) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (datasetId != null) { queryParams.put("dataset_id", datasetId); }
        return request("GET", "/api/v1/datasets/get-versions", pathParams, queryParams, null);
    }

    public String datasetDatasetListdatasets(String pagination, String search, String tags) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (search != null) { queryParams.put("search", search); }
        if (tags != null) { queryParams.put("tags", tags); }
        return request("GET", "/api/v1/datasets/list-datasets", pathParams, queryParams, null);
    }

    public String datasetDatasetPreviewdata(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/datasets/preview-data", pathParams, queryParams, bodyJson);
    }

    public String datasetDatasetUpdatedataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/datasets/update-dataset", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetAborttransaction(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/abort-transaction", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetCommittransaction(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/commit-transaction", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetCreatemediaset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/create-media-set", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetDeletemediaitem(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("DELETE", "/api/v1/media-set/delete-media-item", pathParams, queryParams, null);
    }

    public String mediaSetMediasetDeletemediaset(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("DELETE", "/api/v1/media-set/delete-media-set", pathParams, queryParams, null);
    }

    public String mediaSetMediasetGeneratepresigneddownloadurl(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/generate-presigned-download-url", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetGeneratepresigneduploadurl(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/generate-presigned-upload-url", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetGetmediaitem(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/media-set/get-media-item", pathParams, queryParams, null);
    }

    public String mediaSetMediasetGetmediaset(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/media-set/get-media-set", pathParams, queryParams, null);
    }

    public String mediaSetAccesspatternListaccesspatterns(String mediaSetRid, String pagination) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (mediaSetRid != null) { queryParams.put("media_set_rid", mediaSetRid); }
        if (pagination != null) { queryParams.put("pagination", pagination); }
        return request("GET", "/api/v1/media-set/list-access-patterns", pathParams, queryParams, null);
    }

    public String mediaSetMediasetListmediaitems(String branch, String mediaSetRid, String pagination, String pathPrefix) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (branch != null) { queryParams.put("branch", branch); }
        if (mediaSetRid != null) { queryParams.put("media_set_rid", mediaSetRid); }
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (pathPrefix != null) { queryParams.put("path_prefix", pathPrefix); }
        return request("GET", "/api/v1/media-set/list-media-items", pathParams, queryParams, null);
    }

    public String mediaSetMediasetListmediasets(String pagination, String projectRid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (projectRid != null) { queryParams.put("project_rid", projectRid); }
        return request("GET", "/api/v1/media-set/list-media-sets", pathParams, queryParams, null);
    }

    public String mediaSetMediasetOpentransaction(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/open-transaction", pathParams, queryParams, bodyJson);
    }

    public String mediaSetAccesspatternRegisteraccesspattern(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/register-access-pattern", pathParams, queryParams, bodyJson);
    }

    public String mediaSetMediasetRegistervirtualmediaitem(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/register-virtual-media-item", pathParams, queryParams, bodyJson);
    }

    public String mediaSetAccesspatternRunaccesspattern(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/media-set/run-access-pattern", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookCreatenotebook(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/create-notebook", pathParams, queryParams, bodyJson);
    }

    public String notebookKernelCreatesession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/create-session", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookDeletenotebook(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/notebook/delete-notebook", pathParams, queryParams, null);
    }

    public String notebookNotebookGetnotebook(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("GET", "/api/v1/notebook/get-notebook", pathParams, queryParams, null);
    }

    public String notebookNotebookListnotebooks(Long page, Long perPage, String search) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (page != null) { queryParams.put("page", page); }
        if (perPage != null) { queryParams.put("per_page", perPage); }
        if (search != null) { queryParams.put("search", search); }
        return request("GET", "/api/v1/notebook/list-notebooks", pathParams, queryParams, null);
    }

    public String notebookKernelListsessions(String notebookId) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (notebookId != null) { queryParams.put("notebook_id", notebookId); }
        return request("GET", "/api/v1/notebook/list-sessions", pathParams, queryParams, null);
    }

    public String notebookKernelStopsession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/notebook/stop-session", pathParams, queryParams, bodyJson);
    }

    public String notebookNotebookUpdatenotebook(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/notebook/update-notebook", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyBinddataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/bind-dataset", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreatelinktype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-link-type", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyobjectCreateobject(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-object", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreateobjecttype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-object-type", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyCreateproperty(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/create-property", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyDeletelinktype(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/ontology/delete-link-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyobjectDeleteobject(String objectTypeId, String primaryKey) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (objectTypeId != null) { queryParams.put("object_type_id", objectTypeId); }
        if (primaryKey != null) { queryParams.put("primary_key", primaryKey); }
        return request("DELETE", "/api/v1/ontology/delete-object", pathParams, queryParams, null);
    }

    public String ontologyOntologyDeleteobjecttype(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/ontology/delete-object-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyobjectGetobject(String objectTypeId, String primaryKey) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (objectTypeId != null) { queryParams.put("object_type_id", objectTypeId); }
        if (primaryKey != null) { queryParams.put("primary_key", primaryKey); }
        return request("GET", "/api/v1/ontology/get-object", pathParams, queryParams, null);
    }

    public String ontologyOntologyGetobjecttype(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("GET", "/api/v1/ontology/get-object-type", pathParams, queryParams, null);
    }

    public String ontologyOntologyListlinktypes(String objectTypeId, String pagination) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (objectTypeId != null) { queryParams.put("object_type_id", objectTypeId); }
        if (pagination != null) { queryParams.put("pagination", pagination); }
        return request("GET", "/api/v1/ontology/list-link-types", pathParams, queryParams, null);
    }

    public String ontologyOntologyListobjecttypes(String pagination, String search) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (search != null) { queryParams.put("search", search); }
        return request("GET", "/api/v1/ontology/list-object-types", pathParams, queryParams, null);
    }

    public String ontologyOntologyobjectListobjects(String cursor, String filters, String objectTypeId, Long pageSize, String sort) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (cursor != null) { queryParams.put("cursor", cursor); }
        if (filters != null) { queryParams.put("filters", filters); }
        if (objectTypeId != null) { queryParams.put("object_type_id", objectTypeId); }
        if (pageSize != null) { queryParams.put("page_size", pageSize); }
        if (sort != null) { queryParams.put("sort", sort); }
        return request("GET", "/api/v1/ontology/list-objects", pathParams, queryParams, null);
    }

    public String ontologyOntologyListproperties(String objectTypeId) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (objectTypeId != null) { queryParams.put("object_type_id", objectTypeId); }
        return request("GET", "/api/v1/ontology/list-properties", pathParams, queryParams, null);
    }

    public String ontologyOntologyMaterializebinding(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/materialize-binding", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyobjectSearchobjects(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/search-objects", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyobjectTraverselinks(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/traverse-links", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyUnbinddataset(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/ontology/unbind-dataset", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyobjectUpdateobject(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/ontology/update-object", pathParams, queryParams, bodyJson);
    }

    public String ontologyOntologyUpdateobjecttype(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/ontology/update-object-type", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineCreatepipeline(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/create-pipeline", pathParams, queryParams, bodyJson);
    }

    public String pipelineScheduleCreateschedule(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/create-schedule", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineDeletepipeline(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/pipelines/delete-pipeline", pathParams, queryParams, null);
    }

    public String pipelineScheduleDeleteschedule(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("DELETE", "/api/v1/pipelines/delete-schedule", pathParams, queryParams, null);
    }

    public String pipelineLineageGetdatasetlineage(String datasetId) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (datasetId != null) { queryParams.put("dataset_id", datasetId); }
        return request("GET", "/api/v1/pipelines/get-dataset-lineage", pathParams, queryParams, null);
    }

    public String pipelineLineageGetfulllineage() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v1/pipelines/get-full-lineage", pathParams, queryParams, null);
    }

    public String pipelinePipelineGetpipeline(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("GET", "/api/v1/pipelines/get-pipeline", pathParams, queryParams, null);
    }

    public String pipelineSchedulerunsGetrun(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/pipelines/get-run", pathParams, queryParams, null);
    }

    public String pipelineScheduleGetschedule(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/pipelines/get-schedule", pathParams, queryParams, null);
    }

    public String pipelinePipelineListpipelines(String pagination, String search) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (search != null) { queryParams.put("search", search); }
        return request("GET", "/api/v1/pipelines/list-pipelines", pathParams, queryParams, null);
    }

    public String pipelineSchedulerunsListruns(Long limit, Long offset, String outcome, String scheduleRid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (limit != null) { queryParams.put("limit", limit); }
        if (offset != null) { queryParams.put("offset", offset); }
        if (outcome != null) { queryParams.put("outcome", outcome); }
        if (scheduleRid != null) { queryParams.put("schedule_rid", scheduleRid); }
        return request("GET", "/api/v1/pipelines/list-runs", pathParams, queryParams, null);
    }

    public String pipelineScheduleListschedules(Boolean includePaused, String owner, String pagination, String projectRid, String query) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (includePaused != null) { queryParams.put("include_paused", includePaused); }
        if (owner != null) { queryParams.put("owner", owner); }
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (projectRid != null) { queryParams.put("project_rid", projectRid); }
        if (query != null) { queryParams.put("query", query); }
        return request("GET", "/api/v1/pipelines/list-schedules", pathParams, queryParams, null);
    }

    public String pipelineSchedulePreviewnextfires(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/preview-next-fires", pathParams, queryParams, bodyJson);
    }

    public String pipelineLineageRecordlineage(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/record-lineage", pathParams, queryParams, bodyJson);
    }

    public String pipelineScheduleRunschedulenow(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/run-schedule-now", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineTriggerrun(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/pipelines/trigger-run", pathParams, queryParams, bodyJson);
    }

    public String pipelinePipelineUpdatepipeline(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/pipelines/update-pipeline", pathParams, queryParams, bodyJson);
    }

    public String pipelineScheduleUpdateschedule(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v1/pipelines/update-schedule", pathParams, queryParams, bodyJson);
    }

    public String queryQueryDeletesavedquery(String id) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (id != null) { queryParams.put("id", id); }
        return request("DELETE", "/api/v1/queries/delete-saved-query", pathParams, queryParams, null);
    }

    public String queryQueryExecutequery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/execute-query", pathParams, queryParams, bodyJson);
    }

    public String queryQueryExplainquery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/explain-query", pathParams, queryParams, bodyJson);
    }

    public String queryQueryListsavedqueries(String pagination, String search) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (pagination != null) { queryParams.put("pagination", pagination); }
        if (search != null) { queryParams.put("search", search); }
        return request("GET", "/api/v1/queries/list-saved-queries", pathParams, queryParams, null);
    }

    public String queryQuerySavequery(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/queries/save-query", pathParams, queryParams, bodyJson);
    }

    public String runtimePythonruntimeDropsession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/runtime/drop-session", pathParams, queryParams, bodyJson);
    }

    public String runtimePythonruntimeEnsuresession(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/runtime/ensure-session", pathParams, queryParams, bodyJson);
    }

    public String runtimePythonruntimeExecuteinlinefunction(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/runtime/execute-inline-function", pathParams, queryParams, bodyJson);
    }

    public String runtimePythonruntimeExecutenotebookcell(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/runtime/execute-notebook-cell", pathParams, queryParams, bodyJson);
    }

    public String runtimePythonruntimeExecutepipelinetransform(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/runtime/execute-pipeline-transform", pathParams, queryParams, bodyJson);
    }

    public String v1MarketplaceproductCreateproduct(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/create-product", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogDisablemodel(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/disable-model", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogEnablemodel(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/enable-model", pathParams, queryParams, bodyJson);
    }

    public String v1AuditExportevents(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/export-events", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogGetmodel(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/v1/get-model", pathParams, queryParams, null);
    }

    public String v1MarketplaceproductGetproduct(String rid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (rid != null) { queryParams.put("rid", rid); }
        return request("GET", "/api/v1/v1/get-product", pathParams, queryParams, null);
    }

    public String v1MarketplaceproductInstallproduct(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/install-product", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogInvoke(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/invoke", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogInvokestream(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/invoke-stream", pathParams, queryParams, bodyJson);
    }

    public String v1MarketplaceproductListinstallations(Long limit, Long offset, String productRid, String targetWorkspaceRid) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (limit != null) { queryParams.put("limit", limit); }
        if (offset != null) { queryParams.put("offset", offset); }
        if (productRid != null) { queryParams.put("product_rid", productRid); }
        if (targetWorkspaceRid != null) { queryParams.put("target_workspace_rid", targetWorkspaceRid); }
        return request("GET", "/api/v1/v1/list-installations", pathParams, queryParams, null);
    }

    public String v1LlmcatalogListmodels(Boolean onlyEnabled, String provider) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (onlyEnabled != null) { queryParams.put("only_enabled", onlyEnabled); }
        if (provider != null) { queryParams.put("provider", provider); }
        return request("GET", "/api/v1/v1/list-models", pathParams, queryParams, null);
    }

    public String v1MarketplaceproductListproducts(Long limit, Long offset, String status) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (limit != null) { queryParams.put("limit", limit); }
        if (offset != null) { queryParams.put("offset", offset); }
        if (status != null) { queryParams.put("status", status); }
        return request("GET", "/api/v1/v1/list-products", pathParams, queryParams, null);
    }

    public String v1EventrouterPublish(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/publish", pathParams, queryParams, bodyJson);
    }

    public String v1MarketplaceproductPublishversion(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/publish-version", pathParams, queryParams, bodyJson);
    }

    public String v1AuditQueryevents(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/query-events", pathParams, queryParams, bodyJson);
    }

    public String v1AuditRecordevent(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/record-event", pathParams, queryParams, bodyJson);
    }

    public String v1LlmcatalogRegistermodel(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/register-model", pathParams, queryParams, bodyJson);
    }

    public String v1EventrouterSubscribe(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/subscribe", pathParams, queryParams, bodyJson);
    }

    public String v1MarketplaceproductUninstall(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v1/v1/uninstall", pathParams, queryParams, bodyJson);
    }

    public String adminV2Getcontrolpanel() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/control-panel", pathParams, queryParams, null);
    }

    public String adminV2Updatecontrolpanel(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/control-panel", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listgroups() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/groups", pathParams, queryParams, null);
    }

    public String adminV2Creategroup(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/groups", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updategroup(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/groups/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listpermissions() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/permissions", pathParams, queryParams, null);
    }

    public String adminV2Createpermission(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/permissions", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listpolicies() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/policies", pathParams, queryParams, null);
    }

    public String adminV2Createpolicy(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/policies", pathParams, queryParams, bodyJson);
    }

    public String adminV2Evaluatepolicy(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/policies/evaluate", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updatepolicy(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v2/admin/policies/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listroles() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/roles", pathParams, queryParams, null);
    }

    public String adminV2Createrole(String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("POST", "/api/v2/admin/roles", pathParams, queryParams, bodyJson);
    }

    public String adminV2Updaterole(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PUT", "/api/v2/admin/roles/{id}", pathParams, queryParams, bodyJson);
    }

    public String adminV2Listusers() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/users", pathParams, queryParams, null);
    }

    public String adminV2Getcurrentuser() throws IOException, InterruptedException {
        Map<String, Object> pathParams = Map.of();
        Map<String, Object> queryParams = Map.of();
        return request("GET", "/api/v2/admin/users/me", pathParams, queryParams, null);
    }

    public String adminV2Updateuser(String id, String bodyJson) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("id", id);
        Map<String, Object> queryParams = Map.of();
        return request("PATCH", "/api/v2/admin/users/{id}", pathParams, queryParams, bodyJson);
    }

    public String filesystemV2Getdatasetfilesystem(String datasetId, String path) throws IOException, InterruptedException {
        Map<String, Object> pathParams = new LinkedHashMap<>();
        pathParams.put("dataset_id", datasetId);
        Map<String, Object> queryParams = new LinkedHashMap<>();
        if (path != null) { queryParams.put("path", path); }
        return request("GET", "/api/v2/filesystem/datasets/{dataset_id}", pathParams, queryParams, null);
    }

    private String request(String method, String pathTemplate, Map<String, Object> pathParams, Map<String, Object> queryParams, String bodyJson) throws IOException, InterruptedException {
        String path = interpolatePath(pathTemplate, pathParams);
        String url = buildUrl(path, queryParams);
        HttpRequest.BodyPublisher publisher = bodyJson == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(bodyJson);
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(url)).method(method, publisher).header("content-type", "application/json");
        for (Map.Entry<String, String> entry : defaultHeaders.entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        HttpResponse<String> response = httpClient.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() < 200 || response.statusCode() >= 300) {
            throw new IOException("OpenFoundry request failed: " + response.statusCode() + " " + response.body());
        }
        return response.body();
    }

    private String interpolatePath(String pathTemplate, Map<String, Object> pathParams) {
        String path = pathTemplate;
        for (Map.Entry<String, Object> entry : pathParams.entrySet()) {
            path = path.replace("{" + entry.getKey() + "}", urlEncode(String.valueOf(entry.getValue())));
        }
        return path;
    }

    private String buildUrl(String path, Map<String, Object> queryParams) {
        if (queryParams.isEmpty()) {
            return baseUrl + path;
        }
        StringBuilder query = new StringBuilder();
        for (Map.Entry<String, Object> entry : queryParams.entrySet()) {
            if (entry.getValue() == null) {
                continue;
            }
            if (query.length() > 0) {
                query.append('&');
            }
            query.append(urlEncode(entry.getKey())).append('=').append(urlEncode(String.valueOf(entry.getValue())));
        }
        return query.length() == 0 ? baseUrl + path : baseUrl + path + "?" + query;
    }

    private String urlEncode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }
}