// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audit/compliance.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_audit_compliance_proto protoreflect.FileDescriptor

const file_audit_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16audit/compliance.proto\x12\x12open_foundry.auditB\xca\x01\n" +
	"\x16com.open_foundry.auditB\x0fComplianceProtoP\x01Z:github.com/openfoundry/openfoundry-go/libs/proto-gen/audit\xa2\x02\x03OAX\xaa\x02\x11OpenFoundry.Audit\xca\x02\x11OpenFoundry\\Audit\xe2\x02\x1dOpenFoundry\\Audit\\GPBMetadata\xea\x02\x12OpenFoundry::Auditb\x06proto3"

var file_audit_compliance_proto_goTypes = []any{}
var file_audit_compliance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_compliance_proto_init() }
func file_audit_compliance_proto_init() {
	if File_audit_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_compliance_proto_rawDesc), len(file_audit_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_compliance_proto_goTypes,
		DependencyIndexes: file_audit_compliance_proto_depIdxs,
	}.Build()
	File_audit_compliance_proto = out.File
	file_audit_compliance_proto_goTypes = nil
	file_audit_compliance_proto_depIdxs = nil
}
