// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audit/v1/audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEvent is the canonical row shape returned by the query API.
// Field tags are stable; new optional fields may be appended.
type AuditEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Categories      []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	ActorId         string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ResourceRid     string                 `protobuf:"bytes,6,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	ProjectRid      string                 `protobuf:"bytes,7,opt,name=project_rid,json=projectRid,proto3" json:"project_rid,omitempty"`
	Action          string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	MarkingsAtEvent []string               `protobuf:"bytes,9,rep,name=markings_at_event,json=markingsAtEvent,proto3" json:"markings_at_event,omitempty"`
	SourceService   string                 `protobuf:"bytes,10,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	RequestId       string                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,12,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Ip              string                 `protobuf:"bytes,13,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent       string                 `protobuf:"bytes,14,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// payload is the JSON-encoded variant body.
	Payload       []byte `protobuf:"bytes,15,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuditEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuditEvent) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *AuditEvent) GetProjectRid() string {
	if x != nil {
		return x.ProjectRid
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetMarkingsAtEvent() []string {
	if x != nil {
		return x.MarkingsAtEvent
	}
	return nil
}

func (x *AuditEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RecordEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either provide the structured fields below…
	Event *AuditEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// …or the raw envelope bytes already produced by libs/audit-trail.
	// When both are set, raw_envelope wins.
	RawEnvelope   []byte `protobuf:"bytes,2,opt,name=raw_envelope,json=rawEnvelope,proto3" json:"raw_envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventRequest) Reset() {
	*x = RecordEventRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventRequest) ProtoMessage() {}

func (x *RecordEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventRequest.ProtoReflect.Descriptor instead.
func (*RecordEventRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEventRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RecordEventRequest) GetRawEnvelope() []byte {
	if x != nil {
		return x.RawEnvelope
	}
	return nil
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *RecordEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// QueryEventsRequest filters the audit_events table.
// All filter fields are AND-combined. Empty/zero values mean "no
// constraint". `page_size` is clamped to [1, 1000] server-side;
// pagination uses an opaque `next_cursor` cursor (created_at,event_id).
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ResourceRid   string                 `protobuf:"bytes,2,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *QueryEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *QueryEventsRequest) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *QueryEventsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QueryEventsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryEventsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *QueryEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_audit_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *QueryEventsResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// ExportEvents streams NDJSON-encoded events. Each AuditEventExport
// frame carries one event's bytes (`event_ndjson`), allowing clients
// to write straight to disk without re-encoding.
type ExportEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ResourceRid   string                 `protobuf:"bytes,2,opt,name=resource_rid,json=resourceRid,proto3" json:"resource_rid,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEventsRequest) Reset() {
	*x = ExportEventsRequest{}
	mi := &file_audit_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEventsRequest) ProtoMessage() {}

func (x *ExportEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEventsRequest.ProtoReflect.Descriptor instead.
func (*ExportEventsRequest) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *ExportEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ExportEventsRequest) GetResourceRid() string {
	if x != nil {
		return x.ResourceRid
	}
	return ""
}

func (x *ExportEventsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExportEventsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ExportEventsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type AuditEventExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventNdjson   []byte                 `protobuf:"bytes,1,opt,name=event_ndjson,json=eventNdjson,proto3" json:"event_ndjson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventExport) Reset() {
	*x = AuditEventExport{}
	mi := &file_audit_v1_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventExport) ProtoMessage() {}

func (x *AuditEventExport) ProtoReflect() protoreflect.Message {
	mi := &file_audit_v1_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventExport.ProtoReflect.Descriptor instead.
func (*AuditEventExport) Descriptor() ([]byte, []int) {
	return file_audit_v1_audit_proto_rawDescGZIP(), []int{6}
}

func (x *AuditEventExport) GetEventNdjson() []byte {
	if x != nil {
		return x.EventNdjson
	}
	return nil
}

var File_audit_v1_audit_proto protoreflect.FileDescriptor

const file_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x14audit/v1/audit.proto\x12\x15open_foundry.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x03\n" +
	"\n" +
	"AuditEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12!\n" +
	"\fresource_rid\x18\x06 \x01(\tR\vresourceRid\x12\x1f\n" +
	"\vproject_rid\x18\a \x01(\tR\n" +
	"projectRid\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x12*\n" +
	"\x11markings_at_event\x18\t \x03(\tR\x0fmarkingsAtEvent\x12%\n" +
	"\x0esource_service\x18\n" +
	" \x01(\tR\rsourceService\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x12%\n" +
	"\x0ecorrelation_id\x18\f \x01(\tR\rcorrelationId\x12\x0e\n" +
	"\x02ip\x18\r \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0e \x01(\tR\tuserAgent\x12\x18\n" +
	"\apayload\x18\x0f \x01(\fR\apayload\"p\n" +
	"\x12RecordEventRequest\x127\n" +
	"\x05event\x18\x01 \x01(\v2!.open_foundry.audit.v1.AuditEventR\x05event\x12!\n" +
	"\fraw_envelope\x18\x02 \x01(\fR\vrawEnvelope\"0\n" +
	"\x13RecordEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xfb\x01\n" +
	"\x12QueryEventsRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12!\n" +
	"\fresource_rid\x18\x02 \x01(\tR\vresourceRid\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12.\n" +
	"\x04from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\"q\n" +
	"\x13QueryEventsResponse\x129\n" +
	"\x06events\x18\x01 \x03(\v2!.open_foundry.audit.v1.AuditEventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xc7\x01\n" +
	"\x13ExportEventsRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12!\n" +
	"\fresource_rid\x18\x02 \x01(\tR\vresourceRid\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12.\n" +
	"\x04from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"5\n" +
	"\x10AuditEventExport\x12!\n" +
	"\fevent_ndjson\x18\x01 \x01(\fR\veventNdjson2\xc1\x02\n" +
	"\fAuditService\x12d\n" +
	"\vRecordEvent\x12).open_foundry.audit.v1.RecordEventRequest\x1a*.open_foundry.audit.v1.RecordEventResponse\x12d\n" +
	"\vQueryEvents\x12).open_foundry.audit.v1.QueryEventsRequest\x1a*.open_foundry.audit.v1.QueryEventsResponse\x12e\n" +
	"\fExportEvents\x12*.open_foundry.audit.v1.ExportEventsRequest\x1a'.open_foundry.audit.v1.AuditEventExport0\x01B\xe0\x01\n" +
	"\x19com.open_foundry.audit.v1B\n" +
	"AuditProtoP\x01ZEgithub.com/openfoundry/openfoundry-go/libs/proto-gen/audit/v1;auditv1\xa2\x02\x03OAX\xaa\x02\x14OpenFoundry.Audit.V1\xca\x02\x14OpenFoundry\\Audit\\V1\xe2\x02 OpenFoundry\\Audit\\V1\\GPBMetadata\xea\x02\x16OpenFoundry::Audit::V1b\x06proto3"

var (
	file_audit_v1_audit_proto_rawDescOnce sync.Once
	file_audit_v1_audit_proto_rawDescData []byte
)

func file_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)))
	})
	return file_audit_v1_audit_proto_rawDescData
}

var file_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_audit_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),            // 0: open_foundry.audit.v1.AuditEvent
	(*RecordEventRequest)(nil),    // 1: open_foundry.audit.v1.RecordEventRequest
	(*RecordEventResponse)(nil),   // 2: open_foundry.audit.v1.RecordEventResponse
	(*QueryEventsRequest)(nil),    // 3: open_foundry.audit.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil),   // 4: open_foundry.audit.v1.QueryEventsResponse
	(*ExportEventsRequest)(nil),   // 5: open_foundry.audit.v1.ExportEventsRequest
	(*AuditEventExport)(nil),      // 6: open_foundry.audit.v1.AuditEventExport
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_audit_v1_audit_proto_depIdxs = []int32{
	7,  // 0: open_foundry.audit.v1.AuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 1: open_foundry.audit.v1.RecordEventRequest.event:type_name -> open_foundry.audit.v1.AuditEvent
	7,  // 2: open_foundry.audit.v1.QueryEventsRequest.from:type_name -> google.protobuf.Timestamp
	7,  // 3: open_foundry.audit.v1.QueryEventsRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 4: open_foundry.audit.v1.QueryEventsResponse.events:type_name -> open_foundry.audit.v1.AuditEvent
	7,  // 5: open_foundry.audit.v1.ExportEventsRequest.from:type_name -> google.protobuf.Timestamp
	7,  // 6: open_foundry.audit.v1.ExportEventsRequest.to:type_name -> google.protobuf.Timestamp
	1,  // 7: open_foundry.audit.v1.AuditService.RecordEvent:input_type -> open_foundry.audit.v1.RecordEventRequest
	3,  // 8: open_foundry.audit.v1.AuditService.QueryEvents:input_type -> open_foundry.audit.v1.QueryEventsRequest
	5,  // 9: open_foundry.audit.v1.AuditService.ExportEvents:input_type -> open_foundry.audit.v1.ExportEventsRequest
	2,  // 10: open_foundry.audit.v1.AuditService.RecordEvent:output_type -> open_foundry.audit.v1.RecordEventResponse
	4,  // 11: open_foundry.audit.v1.AuditService.QueryEvents:output_type -> open_foundry.audit.v1.QueryEventsResponse
	6,  // 12: open_foundry.audit.v1.AuditService.ExportEvents:output_type -> open_foundry.audit.v1.AuditEventExport
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_audit_v1_audit_proto_init() }
func file_audit_v1_audit_proto_init() {
	if File_audit_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_v1_audit_proto_rawDesc), len(file_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_audit_v1_audit_proto = out.File
	file_audit_v1_audit_proto_goTypes = nil
	file_audit_v1_audit_proto_depIdxs = nil
}
