// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/v1/agent_modes.proto

// Agent operator modes — the broad task context an AI Operator session
// runs under. Each mode binds (a) a documentation bundle that primes the
// LLM with Foundry concepts relevant to the task, (b) an allowlist of
// tool kinds the agent may invoke, and (c) optional mode-specific
// configuration (transform builder choice, function language, ML
// authoring style, ...).
//
// Modes are an agent-runtime-service concept, distinct from the
// per-tool `execution_mode` field in `libs/ai-kernel-go/models/tool.go`
// (which describes *how* a single tool runs: simulated, http_json,
// native_*). Threads carry exactly one active mode at a time; the
// `change_mode` agent skill swaps it mid-session.
//
// Source of truth for the wire shape. The HTTP surface in
// services/agent-runtime-service speaks JSON derived from these
// messages; Go bindings live in libs/proto-gen/ after `make gen`.

package aiv1

import (
	common "github.com/openfoundry/openfoundry-go/libs/proto-gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMode is the closed set of operator-level modes mirrored from
// Palantir AI FDE. Adding a new mode is a wire change — bump cautiously
// and register documentation + tool-kind bindings in the same PR.
type AgentMode int32

const (
	AgentMode_AGENT_MODE_UNSPECIFIED AgentMode = 0
	AgentMode_DATA_INTEGRATION       AgentMode = 1 // Python transforms or Pipeline Builder
	AgentMode_DATA_CONNECTION        AgentMode = 2 // sources, egress policies, connectors
	AgentMode_ONTOLOGY_EDITING       AgentMode = 3 // object types, links, action types
	AgentMode_FUNCTIONS_EDITING      AgentMode = 4 // Foundry functions (Logic / TS / Python)
	AgentMode_EXPLORATION            AgentMode = 5 // read-only investigation
	AgentMode_GOVERNANCE             AgentMode = 6 // permissions, markings, access control
	AgentMode_MACHINE_LEARNING       AgentMode = 7 // Model Studio or pro-code modelling
	AgentMode_OSDK_REACT             AgentMode = 8 // React apps / custom widgets on OSDK
	AgentMode_PLATFORM_QA            AgentMode = 9 // general "how does Foundry work" Q&A
)

// Enum value maps for AgentMode.
var (
	AgentMode_name = map[int32]string{
		0: "AGENT_MODE_UNSPECIFIED",
		1: "DATA_INTEGRATION",
		2: "DATA_CONNECTION",
		3: "ONTOLOGY_EDITING",
		4: "FUNCTIONS_EDITING",
		5: "EXPLORATION",
		6: "GOVERNANCE",
		7: "MACHINE_LEARNING",
		8: "OSDK_REACT",
		9: "PLATFORM_QA",
	}
	AgentMode_value = map[string]int32{
		"AGENT_MODE_UNSPECIFIED": 0,
		"DATA_INTEGRATION":       1,
		"DATA_CONNECTION":        2,
		"ONTOLOGY_EDITING":       3,
		"FUNCTIONS_EDITING":      4,
		"EXPLORATION":            5,
		"GOVERNANCE":             6,
		"MACHINE_LEARNING":       7,
		"OSDK_REACT":             8,
		"PLATFORM_QA":            9,
	}
)

func (x AgentMode) Enum() *AgentMode {
	p := new(AgentMode)
	*p = x
	return p
}

func (x AgentMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[0].Descriptor()
}

func (AgentMode) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[0]
}

func (x AgentMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentMode.Descriptor instead.
func (AgentMode) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{0}
}

// TransformBuilder selects the data-integration authoring surface for
// DATA_INTEGRATION mode. Ignored for other modes.
type TransformBuilder int32

const (
	TransformBuilder_TRANSFORM_BUILDER_UNSPECIFIED TransformBuilder = 0
	TransformBuilder_PYTHON_TRANSFORMS             TransformBuilder = 1
	TransformBuilder_PIPELINE_BUILDER              TransformBuilder = 2
)

// Enum value maps for TransformBuilder.
var (
	TransformBuilder_name = map[int32]string{
		0: "TRANSFORM_BUILDER_UNSPECIFIED",
		1: "PYTHON_TRANSFORMS",
		2: "PIPELINE_BUILDER",
	}
	TransformBuilder_value = map[string]int32{
		"TRANSFORM_BUILDER_UNSPECIFIED": 0,
		"PYTHON_TRANSFORMS":             1,
		"PIPELINE_BUILDER":              2,
	}
)

func (x TransformBuilder) Enum() *TransformBuilder {
	p := new(TransformBuilder)
	*p = x
	return p
}

func (x TransformBuilder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransformBuilder) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[1].Descriptor()
}

func (TransformBuilder) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[1]
}

func (x TransformBuilder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransformBuilder.Descriptor instead.
func (TransformBuilder) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{1}
}

// BranchingMode controls whether agent-proposed changes land on a
// Foundry global branch (default, reviewable via Global Branch proposal)
// or a local-only branch (faster iteration, no proposal). Applies to
// modes that mutate platform state (DATA_INTEGRATION, ONTOLOGY_EDITING,
// FUNCTIONS_EDITING, MACHINE_LEARNING, OSDK_REACT).
type BranchingMode int32

const (
	BranchingMode_BRANCHING_MODE_UNSPECIFIED BranchingMode = 0
	BranchingMode_FOUNDRY_BRANCHING          BranchingMode = 1
	BranchingMode_LOCAL_BRANCHING            BranchingMode = 2
)

// Enum value maps for BranchingMode.
var (
	BranchingMode_name = map[int32]string{
		0: "BRANCHING_MODE_UNSPECIFIED",
		1: "FOUNDRY_BRANCHING",
		2: "LOCAL_BRANCHING",
	}
	BranchingMode_value = map[string]int32{
		"BRANCHING_MODE_UNSPECIFIED": 0,
		"FOUNDRY_BRANCHING":          1,
		"LOCAL_BRANCHING":            2,
	}
)

func (x BranchingMode) Enum() *BranchingMode {
	p := new(BranchingMode)
	*p = x
	return p
}

func (x BranchingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BranchingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[2].Descriptor()
}

func (BranchingMode) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[2]
}

func (x BranchingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BranchingMode.Descriptor instead.
func (BranchingMode) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{2}
}

// CodeEditingMode picks the surface used when the agent writes code:
// Code Workspaces (full repo) vs. inline Authoring (single artifact).
// Used by DATA_INTEGRATION, FUNCTIONS_EDITING, MACHINE_LEARNING,
// OSDK_REACT.
type CodeEditingMode int32

const (
	CodeEditingMode_CODE_EDITING_MODE_UNSPECIFIED CodeEditingMode = 0
	CodeEditingMode_CODE_WORKSPACES               CodeEditingMode = 1
	CodeEditingMode_AUTHORING                     CodeEditingMode = 2
)

// Enum value maps for CodeEditingMode.
var (
	CodeEditingMode_name = map[int32]string{
		0: "CODE_EDITING_MODE_UNSPECIFIED",
		1: "CODE_WORKSPACES",
		2: "AUTHORING",
	}
	CodeEditingMode_value = map[string]int32{
		"CODE_EDITING_MODE_UNSPECIFIED": 0,
		"CODE_WORKSPACES":               1,
		"AUTHORING":                     2,
	}
)

func (x CodeEditingMode) Enum() *CodeEditingMode {
	p := new(CodeEditingMode)
	*p = x
	return p
}

func (x CodeEditingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeEditingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[3].Descriptor()
}

func (CodeEditingMode) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[3]
}

func (x CodeEditingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeEditingMode.Descriptor instead.
func (CodeEditingMode) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{3}
}

// FunctionLanguage selects the language for FUNCTIONS_EDITING mode.
// Foundry functions support Logic (no-code), TypeScript, and Python.
type FunctionLanguage int32

const (
	FunctionLanguage_FUNCTION_LANGUAGE_UNSPECIFIED FunctionLanguage = 0
	FunctionLanguage_LOGIC                         FunctionLanguage = 1
	FunctionLanguage_TYPESCRIPT                    FunctionLanguage = 2
	FunctionLanguage_PYTHON                        FunctionLanguage = 3
)

// Enum value maps for FunctionLanguage.
var (
	FunctionLanguage_name = map[int32]string{
		0: "FUNCTION_LANGUAGE_UNSPECIFIED",
		1: "LOGIC",
		2: "TYPESCRIPT",
		3: "PYTHON",
	}
	FunctionLanguage_value = map[string]int32{
		"FUNCTION_LANGUAGE_UNSPECIFIED": 0,
		"LOGIC":                         1,
		"TYPESCRIPT":                    2,
		"PYTHON":                        3,
	}
)

func (x FunctionLanguage) Enum() *FunctionLanguage {
	p := new(FunctionLanguage)
	*p = x
	return p
}

func (x FunctionLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[4].Descriptor()
}

func (FunctionLanguage) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[4]
}

func (x FunctionLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionLanguage.Descriptor instead.
func (FunctionLanguage) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{4}
}

// MLAuthoringStyle picks between Model Studio (no-code, visual) and
// pro-code authoring for MACHINE_LEARNING mode.
type MLAuthoringStyle int32

const (
	MLAuthoringStyle_ML_AUTHORING_STYLE_UNSPECIFIED MLAuthoringStyle = 0
	MLAuthoringStyle_MODEL_STUDIO                   MLAuthoringStyle = 1
	MLAuthoringStyle_PRO_CODE                       MLAuthoringStyle = 2
)

// Enum value maps for MLAuthoringStyle.
var (
	MLAuthoringStyle_name = map[int32]string{
		0: "ML_AUTHORING_STYLE_UNSPECIFIED",
		1: "MODEL_STUDIO",
		2: "PRO_CODE",
	}
	MLAuthoringStyle_value = map[string]int32{
		"ML_AUTHORING_STYLE_UNSPECIFIED": 0,
		"MODEL_STUDIO":                   1,
		"PRO_CODE":                       2,
	}
)

func (x MLAuthoringStyle) Enum() *MLAuthoringStyle {
	p := new(MLAuthoringStyle)
	*p = x
	return p
}

func (x MLAuthoringStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MLAuthoringStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_agent_modes_proto_enumTypes[5].Descriptor()
}

func (MLAuthoringStyle) Type() protoreflect.EnumType {
	return &file_ai_v1_agent_modes_proto_enumTypes[5]
}

func (x MLAuthoringStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MLAuthoringStyle.Descriptor instead.
func (MLAuthoringStyle) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{5}
}

// DataIntegrationConfig — settings exposed when AgentMode is
// DATA_INTEGRATION. Mirrors the AI FDE "Transform data" mode panel:
// transform type, branching mode, code editing mode, plus the optional
// "Create and edit object types and links" toggle.
type DataIntegrationConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TransformBuilder     TransformBuilder       `protobuf:"varint,1,opt,name=transform_builder,json=transformBuilder,proto3,enum=open_foundry.ai.v1.TransformBuilder" json:"transform_builder,omitempty"`
	BranchingMode        BranchingMode          `protobuf:"varint,2,opt,name=branching_mode,json=branchingMode,proto3,enum=open_foundry.ai.v1.BranchingMode" json:"branching_mode,omitempty"`
	CodeEditingMode      CodeEditingMode        `protobuf:"varint,3,opt,name=code_editing_mode,json=codeEditingMode,proto3,enum=open_foundry.ai.v1.CodeEditingMode" json:"code_editing_mode,omitempty"`
	AllowOntologyEditing bool                   `protobuf:"varint,4,opt,name=allow_ontology_editing,json=allowOntologyEditing,proto3" json:"allow_ontology_editing,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataIntegrationConfig) Reset() {
	*x = DataIntegrationConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataIntegrationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataIntegrationConfig) ProtoMessage() {}

func (x *DataIntegrationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataIntegrationConfig.ProtoReflect.Descriptor instead.
func (*DataIntegrationConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{0}
}

func (x *DataIntegrationConfig) GetTransformBuilder() TransformBuilder {
	if x != nil {
		return x.TransformBuilder
	}
	return TransformBuilder_TRANSFORM_BUILDER_UNSPECIFIED
}

func (x *DataIntegrationConfig) GetBranchingMode() BranchingMode {
	if x != nil {
		return x.BranchingMode
	}
	return BranchingMode_BRANCHING_MODE_UNSPECIFIED
}

func (x *DataIntegrationConfig) GetCodeEditingMode() CodeEditingMode {
	if x != nil {
		return x.CodeEditingMode
	}
	return CodeEditingMode_CODE_EDITING_MODE_UNSPECIFIED
}

func (x *DataIntegrationConfig) GetAllowOntologyEditing() bool {
	if x != nil {
		return x.AllowOntologyEditing
	}
	return false
}

// FunctionsConfig — settings exposed when AgentMode is FUNCTIONS_EDITING.
type FunctionsConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        FunctionLanguage       `protobuf:"varint,1,opt,name=language,proto3,enum=open_foundry.ai.v1.FunctionLanguage" json:"language,omitempty"`
	CodeEditingMode CodeEditingMode        `protobuf:"varint,2,opt,name=code_editing_mode,json=codeEditingMode,proto3,enum=open_foundry.ai.v1.CodeEditingMode" json:"code_editing_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FunctionsConfig) Reset() {
	*x = FunctionsConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionsConfig) ProtoMessage() {}

func (x *FunctionsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionsConfig.ProtoReflect.Descriptor instead.
func (*FunctionsConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionsConfig) GetLanguage() FunctionLanguage {
	if x != nil {
		return x.Language
	}
	return FunctionLanguage_FUNCTION_LANGUAGE_UNSPECIFIED
}

func (x *FunctionsConfig) GetCodeEditingMode() CodeEditingMode {
	if x != nil {
		return x.CodeEditingMode
	}
	return CodeEditingMode_CODE_EDITING_MODE_UNSPECIFIED
}

// MachineLearningConfig — settings exposed when AgentMode is
// MACHINE_LEARNING.
type MachineLearningConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthoringStyle  MLAuthoringStyle       `protobuf:"varint,1,opt,name=authoring_style,json=authoringStyle,proto3,enum=open_foundry.ai.v1.MLAuthoringStyle" json:"authoring_style,omitempty"`
	CodeEditingMode CodeEditingMode        `protobuf:"varint,2,opt,name=code_editing_mode,json=codeEditingMode,proto3,enum=open_foundry.ai.v1.CodeEditingMode" json:"code_editing_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineLearningConfig) Reset() {
	*x = MachineLearningConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineLearningConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineLearningConfig) ProtoMessage() {}

func (x *MachineLearningConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineLearningConfig.ProtoReflect.Descriptor instead.
func (*MachineLearningConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{2}
}

func (x *MachineLearningConfig) GetAuthoringStyle() MLAuthoringStyle {
	if x != nil {
		return x.AuthoringStyle
	}
	return MLAuthoringStyle_ML_AUTHORING_STYLE_UNSPECIFIED
}

func (x *MachineLearningConfig) GetCodeEditingMode() CodeEditingMode {
	if x != nil {
		return x.CodeEditingMode
	}
	return CodeEditingMode_CODE_EDITING_MODE_UNSPECIFIED
}

// OntologyEditingConfig — settings exposed when AgentMode is
// ONTOLOGY_EDITING. Branching is the only knob: Foundry branching (with
// proposal review) vs. local branching.
type OntologyEditingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchingMode BranchingMode          `protobuf:"varint,1,opt,name=branching_mode,json=branchingMode,proto3,enum=open_foundry.ai.v1.BranchingMode" json:"branching_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OntologyEditingConfig) Reset() {
	*x = OntologyEditingConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OntologyEditingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OntologyEditingConfig) ProtoMessage() {}

func (x *OntologyEditingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OntologyEditingConfig.ProtoReflect.Descriptor instead.
func (*OntologyEditingConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{3}
}

func (x *OntologyEditingConfig) GetBranchingMode() BranchingMode {
	if x != nil {
		return x.BranchingMode
	}
	return BranchingMode_BRANCHING_MODE_UNSPECIFIED
}

// OSDKReactConfig — settings exposed when AgentMode is OSDK_REACT.
type OSDKReactConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CodeEditingMode CodeEditingMode        `protobuf:"varint,1,opt,name=code_editing_mode,json=codeEditingMode,proto3,enum=open_foundry.ai.v1.CodeEditingMode" json:"code_editing_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OSDKReactConfig) Reset() {
	*x = OSDKReactConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSDKReactConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSDKReactConfig) ProtoMessage() {}

func (x *OSDKReactConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSDKReactConfig.ProtoReflect.Descriptor instead.
func (*OSDKReactConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{4}
}

func (x *OSDKReactConfig) GetCodeEditingMode() CodeEditingMode {
	if x != nil {
		return x.CodeEditingMode
	}
	return CodeEditingMode_CODE_EDITING_MODE_UNSPECIFIED
}

// ModeConfig carries the per-mode configuration on a thread. Exactly
// one `settings` variant is populated, matching the active `mode`.
// Modes without configurable knobs (DATA_CONNECTION, EXPLORATION,
// GOVERNANCE, PLATFORM_QA) leave `settings` empty.
//
// `documentation_bundle_id` is the retrieval-context-service knowledge
// base loaded into the model's context when this mode activates. Empty
// = no bundle (the agent relies on its baseline Foundry knowledge).
//
// `enabled_tool_kinds` is the allowlist of tool kinds the agent may
// invoke in this mode — drawn from the execution_mode vocabulary in
// libs/ai-kernel-go/models/tool.go (e.g. "native_pipeline",
// "native_ontology"). Empty = allow all tools registered for the
// agent.
type ModeConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Mode                  AgentMode              `protobuf:"varint,1,opt,name=mode,proto3,enum=open_foundry.ai.v1.AgentMode" json:"mode,omitempty"`
	DocumentationBundleId *common.Uuid           `protobuf:"bytes,2,opt,name=documentation_bundle_id,json=documentationBundleId,proto3" json:"documentation_bundle_id,omitempty"`
	EnabledToolKinds      []string               `protobuf:"bytes,3,rep,name=enabled_tool_kinds,json=enabledToolKinds,proto3" json:"enabled_tool_kinds,omitempty"`
	// Types that are valid to be assigned to Settings:
	//
	//	*ModeConfig_DataIntegration
	//	*ModeConfig_OntologyEditing
	//	*ModeConfig_Functions
	//	*ModeConfig_MachineLearning
	//	*ModeConfig_OsdkReact
	Settings      isModeConfig_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeConfig) Reset() {
	*x = ModeConfig{}
	mi := &file_ai_v1_agent_modes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeConfig) ProtoMessage() {}

func (x *ModeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_agent_modes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeConfig.ProtoReflect.Descriptor instead.
func (*ModeConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_agent_modes_proto_rawDescGZIP(), []int{5}
}

func (x *ModeConfig) GetMode() AgentMode {
	if x != nil {
		return x.Mode
	}
	return AgentMode_AGENT_MODE_UNSPECIFIED
}

func (x *ModeConfig) GetDocumentationBundleId() *common.Uuid {
	if x != nil {
		return x.DocumentationBundleId
	}
	return nil
}

func (x *ModeConfig) GetEnabledToolKinds() []string {
	if x != nil {
		return x.EnabledToolKinds
	}
	return nil
}

func (x *ModeConfig) GetSettings() isModeConfig_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ModeConfig) GetDataIntegration() *DataIntegrationConfig {
	if x != nil {
		if x, ok := x.Settings.(*ModeConfig_DataIntegration); ok {
			return x.DataIntegration
		}
	}
	return nil
}

func (x *ModeConfig) GetOntologyEditing() *OntologyEditingConfig {
	if x != nil {
		if x, ok := x.Settings.(*ModeConfig_OntologyEditing); ok {
			return x.OntologyEditing
		}
	}
	return nil
}

func (x *ModeConfig) GetFunctions() *FunctionsConfig {
	if x != nil {
		if x, ok := x.Settings.(*ModeConfig_Functions); ok {
			return x.Functions
		}
	}
	return nil
}

func (x *ModeConfig) GetMachineLearning() *MachineLearningConfig {
	if x != nil {
		if x, ok := x.Settings.(*ModeConfig_MachineLearning); ok {
			return x.MachineLearning
		}
	}
	return nil
}

func (x *ModeConfig) GetOsdkReact() *OSDKReactConfig {
	if x != nil {
		if x, ok := x.Settings.(*ModeConfig_OsdkReact); ok {
			return x.OsdkReact
		}
	}
	return nil
}

type isModeConfig_Settings interface {
	isModeConfig_Settings()
}

type ModeConfig_DataIntegration struct {
	DataIntegration *DataIntegrationConfig `protobuf:"bytes,10,opt,name=data_integration,json=dataIntegration,proto3,oneof"`
}

type ModeConfig_OntologyEditing struct {
	OntologyEditing *OntologyEditingConfig `protobuf:"bytes,11,opt,name=ontology_editing,json=ontologyEditing,proto3,oneof"`
}

type ModeConfig_Functions struct {
	Functions *FunctionsConfig `protobuf:"bytes,12,opt,name=functions,proto3,oneof"`
}

type ModeConfig_MachineLearning struct {
	MachineLearning *MachineLearningConfig `protobuf:"bytes,13,opt,name=machine_learning,json=machineLearning,proto3,oneof"`
}

type ModeConfig_OsdkReact struct {
	OsdkReact *OSDKReactConfig `protobuf:"bytes,14,opt,name=osdk_react,json=osdkReact,proto3,oneof"`
}

func (*ModeConfig_DataIntegration) isModeConfig_Settings() {}

func (*ModeConfig_OntologyEditing) isModeConfig_Settings() {}

func (*ModeConfig_Functions) isModeConfig_Settings() {}

func (*ModeConfig_MachineLearning) isModeConfig_Settings() {}

func (*ModeConfig_OsdkReact) isModeConfig_Settings() {}

var File_ai_v1_agent_modes_proto protoreflect.FileDescriptor

const file_ai_v1_agent_modes_proto_rawDesc = "" +
	"\n" +
	"\x17ai/v1/agent_modes.proto\x12\x12open_foundry.ai.v1\x1a\x12common/types.proto\"\xbb\x02\n" +
	"\x15DataIntegrationConfig\x12Q\n" +
	"\x11transform_builder\x18\x01 \x01(\x0e2$.open_foundry.ai.v1.TransformBuilderR\x10transformBuilder\x12H\n" +
	"\x0ebranching_mode\x18\x02 \x01(\x0e2!.open_foundry.ai.v1.BranchingModeR\rbranchingMode\x12O\n" +
	"\x11code_editing_mode\x18\x03 \x01(\x0e2#.open_foundry.ai.v1.CodeEditingModeR\x0fcodeEditingMode\x124\n" +
	"\x16allow_ontology_editing\x18\x04 \x01(\bR\x14allowOntologyEditing\"\xa4\x01\n" +
	"\x0fFunctionsConfig\x12@\n" +
	"\blanguage\x18\x01 \x01(\x0e2$.open_foundry.ai.v1.FunctionLanguageR\blanguage\x12O\n" +
	"\x11code_editing_mode\x18\x02 \x01(\x0e2#.open_foundry.ai.v1.CodeEditingModeR\x0fcodeEditingMode\"\xb7\x01\n" +
	"\x15MachineLearningConfig\x12M\n" +
	"\x0fauthoring_style\x18\x01 \x01(\x0e2$.open_foundry.ai.v1.MLAuthoringStyleR\x0eauthoringStyle\x12O\n" +
	"\x11code_editing_mode\x18\x02 \x01(\x0e2#.open_foundry.ai.v1.CodeEditingModeR\x0fcodeEditingMode\"a\n" +
	"\x15OntologyEditingConfig\x12H\n" +
	"\x0ebranching_mode\x18\x01 \x01(\x0e2!.open_foundry.ai.v1.BranchingModeR\rbranchingMode\"b\n" +
	"\x0fOSDKReactConfig\x12O\n" +
	"\x11code_editing_mode\x18\x01 \x01(\x0e2#.open_foundry.ai.v1.CodeEditingModeR\x0fcodeEditingMode\"\xdf\x04\n" +
	"\n" +
	"ModeConfig\x121\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1d.open_foundry.ai.v1.AgentModeR\x04mode\x12Q\n" +
	"\x17documentation_bundle_id\x18\x02 \x01(\v2\x19.open_foundry.common.UuidR\x15documentationBundleId\x12,\n" +
	"\x12enabled_tool_kinds\x18\x03 \x03(\tR\x10enabledToolKinds\x12V\n" +
	"\x10data_integration\x18\n" +
	" \x01(\v2).open_foundry.ai.v1.DataIntegrationConfigH\x00R\x0fdataIntegration\x12V\n" +
	"\x10ontology_editing\x18\v \x01(\v2).open_foundry.ai.v1.OntologyEditingConfigH\x00R\x0fontologyEditing\x12C\n" +
	"\tfunctions\x18\f \x01(\v2#.open_foundry.ai.v1.FunctionsConfigH\x00R\tfunctions\x12V\n" +
	"\x10machine_learning\x18\r \x01(\v2).open_foundry.ai.v1.MachineLearningConfigH\x00R\x0fmachineLearning\x12D\n" +
	"\n" +
	"osdk_react\x18\x0e \x01(\v2#.open_foundry.ai.v1.OSDKReactConfigH\x00R\tosdkReactB\n" +
	"\n" +
	"\bsettings*\xd7\x01\n" +
	"\tAgentMode\x12\x1a\n" +
	"\x16AGENT_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_INTEGRATION\x10\x01\x12\x13\n" +
	"\x0fDATA_CONNECTION\x10\x02\x12\x14\n" +
	"\x10ONTOLOGY_EDITING\x10\x03\x12\x15\n" +
	"\x11FUNCTIONS_EDITING\x10\x04\x12\x0f\n" +
	"\vEXPLORATION\x10\x05\x12\x0e\n" +
	"\n" +
	"GOVERNANCE\x10\x06\x12\x14\n" +
	"\x10MACHINE_LEARNING\x10\a\x12\x0e\n" +
	"\n" +
	"OSDK_REACT\x10\b\x12\x0f\n" +
	"\vPLATFORM_QA\x10\t*b\n" +
	"\x10TransformBuilder\x12!\n" +
	"\x1dTRANSFORM_BUILDER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PYTHON_TRANSFORMS\x10\x01\x12\x14\n" +
	"\x10PIPELINE_BUILDER\x10\x02*[\n" +
	"\rBranchingMode\x12\x1e\n" +
	"\x1aBRANCHING_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FOUNDRY_BRANCHING\x10\x01\x12\x13\n" +
	"\x0fLOCAL_BRANCHING\x10\x02*X\n" +
	"\x0fCodeEditingMode\x12!\n" +
	"\x1dCODE_EDITING_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCODE_WORKSPACES\x10\x01\x12\r\n" +
	"\tAUTHORING\x10\x02*\\\n" +
	"\x10FunctionLanguage\x12!\n" +
	"\x1dFUNCTION_LANGUAGE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOGIC\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPESCRIPT\x10\x02\x12\n" +
	"\n" +
	"\x06PYTHON\x10\x03*V\n" +
	"\x10MLAuthoringStyle\x12\"\n" +
	"\x1eML_AUTHORING_STYLE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMODEL_STUDIO\x10\x01\x12\f\n" +
	"\bPRO_CODE\x10\x02B\xd0\x01\n" +
	"\x16com.open_foundry.ai.v1B\x0fAgentModesProtoP\x01Z?github.com/openfoundry/openfoundry-go/libs/proto-gen/ai/v1;aiv1\xa2\x02\x03OAX\xaa\x02\x11OpenFoundry.Ai.V1\xca\x02\x11OpenFoundry\\Ai\\V1\xe2\x02\x1dOpenFoundry\\Ai\\V1\\GPBMetadata\xea\x02\x13OpenFoundry::Ai::V1b\x06proto3"

var (
	file_ai_v1_agent_modes_proto_rawDescOnce sync.Once
	file_ai_v1_agent_modes_proto_rawDescData []byte
)

func file_ai_v1_agent_modes_proto_rawDescGZIP() []byte {
	file_ai_v1_agent_modes_proto_rawDescOnce.Do(func() {
		file_ai_v1_agent_modes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_agent_modes_proto_rawDesc), len(file_ai_v1_agent_modes_proto_rawDesc)))
	})
	return file_ai_v1_agent_modes_proto_rawDescData
}

var file_ai_v1_agent_modes_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_ai_v1_agent_modes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ai_v1_agent_modes_proto_goTypes = []any{
	(AgentMode)(0),                // 0: open_foundry.ai.v1.AgentMode
	(TransformBuilder)(0),         // 1: open_foundry.ai.v1.TransformBuilder
	(BranchingMode)(0),            // 2: open_foundry.ai.v1.BranchingMode
	(CodeEditingMode)(0),          // 3: open_foundry.ai.v1.CodeEditingMode
	(FunctionLanguage)(0),         // 4: open_foundry.ai.v1.FunctionLanguage
	(MLAuthoringStyle)(0),         // 5: open_foundry.ai.v1.MLAuthoringStyle
	(*DataIntegrationConfig)(nil), // 6: open_foundry.ai.v1.DataIntegrationConfig
	(*FunctionsConfig)(nil),       // 7: open_foundry.ai.v1.FunctionsConfig
	(*MachineLearningConfig)(nil), // 8: open_foundry.ai.v1.MachineLearningConfig
	(*OntologyEditingConfig)(nil), // 9: open_foundry.ai.v1.OntologyEditingConfig
	(*OSDKReactConfig)(nil),       // 10: open_foundry.ai.v1.OSDKReactConfig
	(*ModeConfig)(nil),            // 11: open_foundry.ai.v1.ModeConfig
	(*common.Uuid)(nil),           // 12: open_foundry.common.Uuid
}
var file_ai_v1_agent_modes_proto_depIdxs = []int32{
	1,  // 0: open_foundry.ai.v1.DataIntegrationConfig.transform_builder:type_name -> open_foundry.ai.v1.TransformBuilder
	2,  // 1: open_foundry.ai.v1.DataIntegrationConfig.branching_mode:type_name -> open_foundry.ai.v1.BranchingMode
	3,  // 2: open_foundry.ai.v1.DataIntegrationConfig.code_editing_mode:type_name -> open_foundry.ai.v1.CodeEditingMode
	4,  // 3: open_foundry.ai.v1.FunctionsConfig.language:type_name -> open_foundry.ai.v1.FunctionLanguage
	3,  // 4: open_foundry.ai.v1.FunctionsConfig.code_editing_mode:type_name -> open_foundry.ai.v1.CodeEditingMode
	5,  // 5: open_foundry.ai.v1.MachineLearningConfig.authoring_style:type_name -> open_foundry.ai.v1.MLAuthoringStyle
	3,  // 6: open_foundry.ai.v1.MachineLearningConfig.code_editing_mode:type_name -> open_foundry.ai.v1.CodeEditingMode
	2,  // 7: open_foundry.ai.v1.OntologyEditingConfig.branching_mode:type_name -> open_foundry.ai.v1.BranchingMode
	3,  // 8: open_foundry.ai.v1.OSDKReactConfig.code_editing_mode:type_name -> open_foundry.ai.v1.CodeEditingMode
	0,  // 9: open_foundry.ai.v1.ModeConfig.mode:type_name -> open_foundry.ai.v1.AgentMode
	12, // 10: open_foundry.ai.v1.ModeConfig.documentation_bundle_id:type_name -> open_foundry.common.Uuid
	6,  // 11: open_foundry.ai.v1.ModeConfig.data_integration:type_name -> open_foundry.ai.v1.DataIntegrationConfig
	9,  // 12: open_foundry.ai.v1.ModeConfig.ontology_editing:type_name -> open_foundry.ai.v1.OntologyEditingConfig
	7,  // 13: open_foundry.ai.v1.ModeConfig.functions:type_name -> open_foundry.ai.v1.FunctionsConfig
	8,  // 14: open_foundry.ai.v1.ModeConfig.machine_learning:type_name -> open_foundry.ai.v1.MachineLearningConfig
	10, // 15: open_foundry.ai.v1.ModeConfig.osdk_react:type_name -> open_foundry.ai.v1.OSDKReactConfig
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ai_v1_agent_modes_proto_init() }
func file_ai_v1_agent_modes_proto_init() {
	if File_ai_v1_agent_modes_proto != nil {
		return
	}
	file_ai_v1_agent_modes_proto_msgTypes[5].OneofWrappers = []any{
		(*ModeConfig_DataIntegration)(nil),
		(*ModeConfig_OntologyEditing)(nil),
		(*ModeConfig_Functions)(nil),
		(*ModeConfig_MachineLearning)(nil),
		(*ModeConfig_OsdkReact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_agent_modes_proto_rawDesc), len(file_ai_v1_agent_modes_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_v1_agent_modes_proto_goTypes,
		DependencyIndexes: file_ai_v1_agent_modes_proto_depIdxs,
		EnumInfos:         file_ai_v1_agent_modes_proto_enumTypes,
		MessageInfos:      file_ai_v1_agent_modes_proto_msgTypes,
	}.Build()
	File_ai_v1_agent_modes_proto = out.File
	file_ai_v1_agent_modes_proto_goTypes = nil
	file_ai_v1_agent_modes_proto_depIdxs = nil
}
