// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/v1/llm_catalog.proto

// LLM catalog + unified invocation surface. The single entry-point any
// AIP-style flow uses to register, list, and invoke an LLM regardless of
// upstream provider (Anthropic, OpenAI, Ollama, Bedrock, ...). Handlers
// in services/llm-catalog-service implement this service over HTTP/JSON;
// the proto is the source of truth for the wire shape.

package aiv1

import (
	common "github.com/openfoundry/openfoundry-go/libs/proto-gen/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provider enumeration. Anthropic and OpenAI-compatible (also covers
// Ollama and vLLM via the chat_completions API mode) are wired in v1;
// BEDROCK is reserved — registration succeeds, invocation returns
// UNIMPLEMENTED.
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_ANTHROPIC            Provider = 1
	Provider_OPENAI               Provider = 2
	Provider_OLLAMA               Provider = 3
	Provider_BEDROCK              Provider = 4
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "ANTHROPIC",
		2: "OPENAI",
		3: "OLLAMA",
		4: "BEDROCK",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"ANTHROPIC":            1,
		"OPENAI":               2,
		"OLLAMA":               3,
		"BEDROCK":              4,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_llm_catalog_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_ai_v1_llm_catalog_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{0}
}

// Capabilities advertised by a registered model. Capability filtering is
// applied at the planner layer; the invoke handler does not enforce.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	Capability_TEXT                   Capability = 1
	Capability_VISION                 Capability = 2
	Capability_TOOLS                  Capability = 3
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "TEXT",
		2: "VISION",
		3: "TOOLS",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"TEXT":                   1,
		"VISION":                 2,
		"TOOLS":                  3,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_v1_llm_catalog_proto_enumTypes[1].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_ai_v1_llm_catalog_proto_enumTypes[1]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{1}
}

// Model is one row of the catalog. `rid` is the stable resource handle
// callers reference in InvokeRequest.
type Model struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rid              *common.Uuid           `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Provider         Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=open_foundry.ai.v1.Provider" json:"provider,omitempty"`
	ModelId          string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ContextWindow    int32                  `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	InputCostPer_1K  float64                `protobuf:"fixed64,6,opt,name=input_cost_per_1k,json=inputCostPer1k,proto3" json:"input_cost_per_1k,omitempty"`
	OutputCostPer_1K float64                `protobuf:"fixed64,7,opt,name=output_cost_per_1k,json=outputCostPer1k,proto3" json:"output_cost_per_1k,omitempty"`
	Capabilities     []Capability           `protobuf:"varint,8,rep,packed,name=capabilities,proto3,enum=open_foundry.ai.v1.Capability" json:"capabilities,omitempty"`
	Enabled          bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetRid() *common.Uuid {
	if x != nil {
		return x.Rid
	}
	return nil
}

func (x *Model) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Model) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *Model) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Model) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *Model) GetInputCostPer_1K() float64 {
	if x != nil {
		return x.InputCostPer_1K
	}
	return 0
}

func (x *Model) GetOutputCostPer_1K() float64 {
	if x != nil {
		return x.OutputCostPer_1K
	}
	return 0
}

func (x *Model) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RegisterModelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Provider         Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=open_foundry.ai.v1.Provider" json:"provider,omitempty"`
	ModelId          string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ContextWindow    int32                  `protobuf:"varint,4,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	InputCostPer_1K  float64                `protobuf:"fixed64,5,opt,name=input_cost_per_1k,json=inputCostPer1k,proto3" json:"input_cost_per_1k,omitempty"`
	OutputCostPer_1K float64                `protobuf:"fixed64,6,opt,name=output_cost_per_1k,json=outputCostPer1k,proto3" json:"output_cost_per_1k,omitempty"`
	Capabilities     []Capability           `protobuf:"varint,7,rep,packed,name=capabilities,proto3,enum=open_foundry.ai.v1.Capability" json:"capabilities,omitempty"`
	Enabled          bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterModelRequest) Reset() {
	*x = RegisterModelRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelRequest) ProtoMessage() {}

func (x *RegisterModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterModelRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *RegisterModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RegisterModelRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterModelRequest) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *RegisterModelRequest) GetInputCostPer_1K() float64 {
	if x != nil {
		return x.InputCostPer_1K
	}
	return 0
}

func (x *RegisterModelRequest) GetOutputCostPer_1K() float64 {
	if x != nil {
		return x.OutputCostPer_1K
	}
	return 0
}

func (x *RegisterModelRequest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterModelRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters. Empty = no filter.
	Provider      Provider `protobuf:"varint,1,opt,name=provider,proto3,enum=open_foundry.ai.v1.Provider" json:"provider,omitempty"`
	OnlyEnabled   bool     `protobuf:"varint,2,opt,name=only_enabled,json=onlyEnabled,proto3" json:"only_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ListModelsRequest) GetOnlyEnabled() bool {
	if x != nil {
		return x.OnlyEnabled
	}
	return false
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Model               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsResponse) GetData() []*Model {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           *common.Uuid           `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelRequest) GetRid() *common.Uuid {
	if x != nil {
		return x.Rid
	}
	return nil
}

type EnableModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           *common.Uuid           `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableModelRequest) Reset() {
	*x = EnableModelRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableModelRequest) ProtoMessage() {}

func (x *EnableModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableModelRequest.ProtoReflect.Descriptor instead.
func (*EnableModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *EnableModelRequest) GetRid() *common.Uuid {
	if x != nil {
		return x.Rid
	}
	return nil
}

type DisableModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           *common.Uuid           `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableModelRequest) Reset() {
	*x = DisableModelRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableModelRequest) ProtoMessage() {}

func (x *DisableModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableModelRequest.ProtoReflect.Descriptor instead.
func (*DisableModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *DisableModelRequest) GetRid() *common.Uuid {
	if x != nil {
		return x.Rid
	}
	return nil
}

// Wire-compatible chat message — mirrors the OpenAI chat-completions
// shape so apps/web speaks one schema across providers.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // system | user | assistant | tool
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Tool definition (registered for forward-compat — v1 does not execute
// tools, it just round-trips the schema).
type Tool struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJsonSchema string                 `protobuf:"bytes,3,opt,name=parameters_json_schema,json=parametersJsonSchema,proto3" json:"parameters_json_schema,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetParametersJsonSchema() string {
	if x != nil {
		return x.ParametersJsonSchema
	}
	return ""
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRid      *common.Uuid           `protobuf:"bytes,1,opt,name=model_rid,json=modelRid,proto3" json:"model_rid,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Stream        bool                   `protobuf:"varint,6,opt,name=stream,proto3" json:"stream,omitempty"` // hint; server-side stream uses InvokeStream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeRequest) GetModelRid() *common.Uuid {
	if x != nil {
		return x.ModelRid
	}
	return nil
}

func (x *InvokeRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InvokeRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *InvokeRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *InvokeRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *InvokeRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// Usage block mirrors OpenAI {prompt_tokens, completion_tokens,
// total_tokens}. completion_tokens is filled from provider counts when
// available, otherwise estimated.
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	ModelRid      string                 `protobuf:"bytes,3,opt,name=model_rid,json=modelRid,proto3" json:"model_rid,omitempty"` // echo for client correlation
	CostUsd       float64                `protobuf:"fixed64,4,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *InvokeResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InvokeResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *InvokeResponse) GetModelRid() string {
	if x != nil {
		return x.ModelRid
	}
	return ""
}

func (x *InvokeResponse) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

type InvokeStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"` // token / partial content
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`  // last chunk for the stream
	Usage         *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"` // populated on the last chunk only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeStreamChunk) Reset() {
	*x = InvokeStreamChunk{}
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeStreamChunk) ProtoMessage() {}

func (x *InvokeStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_llm_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeStreamChunk.ProtoReflect.Descriptor instead.
func (*InvokeStreamChunk) Descriptor() ([]byte, []int) {
	return file_ai_v1_llm_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *InvokeStreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *InvokeStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *InvokeStreamChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_ai_v1_llm_catalog_proto protoreflect.FileDescriptor

const file_ai_v1_llm_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17ai/v1/llm_catalog.proto\x12\x12open_foundry.ai.v1\x1a\x12common/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x03\n" +
	"\x05Model\x12+\n" +
	"\x03rid\x18\x01 \x01(\v2\x19.open_foundry.common.UuidR\x03rid\x128\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x1c.open_foundry.ai.v1.ProviderR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12%\n" +
	"\x0econtext_window\x18\x05 \x01(\x05R\rcontextWindow\x12)\n" +
	"\x11input_cost_per_1k\x18\x06 \x01(\x01R\x0einputCostPer1k\x12+\n" +
	"\x12output_cost_per_1k\x18\a \x01(\x01R\x0foutputCostPer1k\x12B\n" +
	"\fcapabilities\x18\b \x03(\x0e2\x1e.open_foundry.ai.v1.CapabilityR\fcapabilities\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xeb\x02\n" +
	"\x14RegisterModelRequest\x128\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1c.open_foundry.ai.v1.ProviderR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x0econtext_window\x18\x04 \x01(\x05R\rcontextWindow\x12)\n" +
	"\x11input_cost_per_1k\x18\x05 \x01(\x01R\x0einputCostPer1k\x12+\n" +
	"\x12output_cost_per_1k\x18\x06 \x01(\x01R\x0foutputCostPer1k\x12B\n" +
	"\fcapabilities\x18\a \x03(\x0e2\x1e.open_foundry.ai.v1.CapabilityR\fcapabilities\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"p\n" +
	"\x11ListModelsRequest\x128\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1c.open_foundry.ai.v1.ProviderR\bprovider\x12!\n" +
	"\fonly_enabled\x18\x02 \x01(\bR\vonlyEnabled\"C\n" +
	"\x12ListModelsResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.open_foundry.ai.v1.ModelR\x04data\">\n" +
	"\x0fGetModelRequest\x12+\n" +
	"\x03rid\x18\x01 \x01(\v2\x19.open_foundry.common.UuidR\x03rid\"A\n" +
	"\x12EnableModelRequest\x12+\n" +
	"\x03rid\x18\x01 \x01(\v2\x19.open_foundry.common.UuidR\x03rid\"B\n" +
	"\x13DisableModelRequest\x12+\n" +
	"\x03rid\x18\x01 \x01(\v2\x19.open_foundry.common.UuidR\x03rid\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"r\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x16parameters_json_schema\x18\x03 \x01(\tR\x14parametersJsonSchema\"\x89\x02\n" +
	"\rInvokeRequest\x126\n" +
	"\tmodel_rid\x18\x01 \x01(\v2\x19.open_foundry.common.UuidR\bmodelRid\x127\n" +
	"\bmessages\x18\x02 \x03(\v2\x1b.open_foundry.ai.v1.MessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12.\n" +
	"\x05tools\x18\x05 \x03(\v2\x18.open_foundry.ai.v1.ToolR\x05tools\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\bR\x06stream\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xb2\x01\n" +
	"\x0eInvokeResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.open_foundry.ai.v1.MessageR\bmessages\x12/\n" +
	"\x05usage\x18\x02 \x01(\v2\x19.open_foundry.ai.v1.UsageR\x05usage\x12\x1b\n" +
	"\tmodel_rid\x18\x03 \x01(\tR\bmodelRid\x12\x19\n" +
	"\bcost_usd\x18\x04 \x01(\x01R\acostUsd\"n\n" +
	"\x11InvokeStreamChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12/\n" +
	"\x05usage\x18\x03 \x01(\v2\x19.open_foundry.ai.v1.UsageR\x05usage*X\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tANTHROPIC\x10\x01\x12\n" +
	"\n" +
	"\x06OPENAI\x10\x02\x12\n" +
	"\n" +
	"\x06OLLAMA\x10\x03\x12\v\n" +
	"\aBEDROCK\x10\x04*I\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\n" +
	"\n" +
	"\x06VISION\x10\x02\x12\t\n" +
	"\x05TOOLS\x10\x032\xe5\x04\n" +
	"\x11LlmCatalogService\x12T\n" +
	"\rRegisterModel\x12(.open_foundry.ai.v1.RegisterModelRequest\x1a\x19.open_foundry.ai.v1.Model\x12[\n" +
	"\n" +
	"ListModels\x12%.open_foundry.ai.v1.ListModelsRequest\x1a&.open_foundry.ai.v1.ListModelsResponse\x12J\n" +
	"\bGetModel\x12#.open_foundry.ai.v1.GetModelRequest\x1a\x19.open_foundry.ai.v1.Model\x12P\n" +
	"\vEnableModel\x12&.open_foundry.ai.v1.EnableModelRequest\x1a\x19.open_foundry.ai.v1.Model\x12R\n" +
	"\fDisableModel\x12'.open_foundry.ai.v1.DisableModelRequest\x1a\x19.open_foundry.ai.v1.Model\x12O\n" +
	"\x06Invoke\x12!.open_foundry.ai.v1.InvokeRequest\x1a\".open_foundry.ai.v1.InvokeResponse\x12Z\n" +
	"\fInvokeStream\x12!.open_foundry.ai.v1.InvokeRequest\x1a%.open_foundry.ai.v1.InvokeStreamChunk0\x01B\xd0\x01\n" +
	"\x16com.open_foundry.ai.v1B\x0fLlmCatalogProtoP\x01Z?github.com/openfoundry/openfoundry-go/libs/proto-gen/ai/v1;aiv1\xa2\x02\x03OAX\xaa\x02\x11OpenFoundry.Ai.V1\xca\x02\x11OpenFoundry\\Ai\\V1\xe2\x02\x1dOpenFoundry\\Ai\\V1\\GPBMetadata\xea\x02\x13OpenFoundry::Ai::V1b\x06proto3"

var (
	file_ai_v1_llm_catalog_proto_rawDescOnce sync.Once
	file_ai_v1_llm_catalog_proto_rawDescData []byte
)

func file_ai_v1_llm_catalog_proto_rawDescGZIP() []byte {
	file_ai_v1_llm_catalog_proto_rawDescOnce.Do(func() {
		file_ai_v1_llm_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_llm_catalog_proto_rawDesc), len(file_ai_v1_llm_catalog_proto_rawDesc)))
	})
	return file_ai_v1_llm_catalog_proto_rawDescData
}

var file_ai_v1_llm_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_v1_llm_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ai_v1_llm_catalog_proto_goTypes = []any{
	(Provider)(0),                 // 0: open_foundry.ai.v1.Provider
	(Capability)(0),               // 1: open_foundry.ai.v1.Capability
	(*Model)(nil),                 // 2: open_foundry.ai.v1.Model
	(*RegisterModelRequest)(nil),  // 3: open_foundry.ai.v1.RegisterModelRequest
	(*ListModelsRequest)(nil),     // 4: open_foundry.ai.v1.ListModelsRequest
	(*ListModelsResponse)(nil),    // 5: open_foundry.ai.v1.ListModelsResponse
	(*GetModelRequest)(nil),       // 6: open_foundry.ai.v1.GetModelRequest
	(*EnableModelRequest)(nil),    // 7: open_foundry.ai.v1.EnableModelRequest
	(*DisableModelRequest)(nil),   // 8: open_foundry.ai.v1.DisableModelRequest
	(*Message)(nil),               // 9: open_foundry.ai.v1.Message
	(*Tool)(nil),                  // 10: open_foundry.ai.v1.Tool
	(*InvokeRequest)(nil),         // 11: open_foundry.ai.v1.InvokeRequest
	(*Usage)(nil),                 // 12: open_foundry.ai.v1.Usage
	(*InvokeResponse)(nil),        // 13: open_foundry.ai.v1.InvokeResponse
	(*InvokeStreamChunk)(nil),     // 14: open_foundry.ai.v1.InvokeStreamChunk
	(*common.Uuid)(nil),           // 15: open_foundry.common.Uuid
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_ai_v1_llm_catalog_proto_depIdxs = []int32{
	15, // 0: open_foundry.ai.v1.Model.rid:type_name -> open_foundry.common.Uuid
	0,  // 1: open_foundry.ai.v1.Model.provider:type_name -> open_foundry.ai.v1.Provider
	1,  // 2: open_foundry.ai.v1.Model.capabilities:type_name -> open_foundry.ai.v1.Capability
	16, // 3: open_foundry.ai.v1.Model.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: open_foundry.ai.v1.Model.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: open_foundry.ai.v1.RegisterModelRequest.provider:type_name -> open_foundry.ai.v1.Provider
	1,  // 6: open_foundry.ai.v1.RegisterModelRequest.capabilities:type_name -> open_foundry.ai.v1.Capability
	0,  // 7: open_foundry.ai.v1.ListModelsRequest.provider:type_name -> open_foundry.ai.v1.Provider
	2,  // 8: open_foundry.ai.v1.ListModelsResponse.data:type_name -> open_foundry.ai.v1.Model
	15, // 9: open_foundry.ai.v1.GetModelRequest.rid:type_name -> open_foundry.common.Uuid
	15, // 10: open_foundry.ai.v1.EnableModelRequest.rid:type_name -> open_foundry.common.Uuid
	15, // 11: open_foundry.ai.v1.DisableModelRequest.rid:type_name -> open_foundry.common.Uuid
	15, // 12: open_foundry.ai.v1.InvokeRequest.model_rid:type_name -> open_foundry.common.Uuid
	9,  // 13: open_foundry.ai.v1.InvokeRequest.messages:type_name -> open_foundry.ai.v1.Message
	10, // 14: open_foundry.ai.v1.InvokeRequest.tools:type_name -> open_foundry.ai.v1.Tool
	9,  // 15: open_foundry.ai.v1.InvokeResponse.messages:type_name -> open_foundry.ai.v1.Message
	12, // 16: open_foundry.ai.v1.InvokeResponse.usage:type_name -> open_foundry.ai.v1.Usage
	12, // 17: open_foundry.ai.v1.InvokeStreamChunk.usage:type_name -> open_foundry.ai.v1.Usage
	3,  // 18: open_foundry.ai.v1.LlmCatalogService.RegisterModel:input_type -> open_foundry.ai.v1.RegisterModelRequest
	4,  // 19: open_foundry.ai.v1.LlmCatalogService.ListModels:input_type -> open_foundry.ai.v1.ListModelsRequest
	6,  // 20: open_foundry.ai.v1.LlmCatalogService.GetModel:input_type -> open_foundry.ai.v1.GetModelRequest
	7,  // 21: open_foundry.ai.v1.LlmCatalogService.EnableModel:input_type -> open_foundry.ai.v1.EnableModelRequest
	8,  // 22: open_foundry.ai.v1.LlmCatalogService.DisableModel:input_type -> open_foundry.ai.v1.DisableModelRequest
	11, // 23: open_foundry.ai.v1.LlmCatalogService.Invoke:input_type -> open_foundry.ai.v1.InvokeRequest
	11, // 24: open_foundry.ai.v1.LlmCatalogService.InvokeStream:input_type -> open_foundry.ai.v1.InvokeRequest
	2,  // 25: open_foundry.ai.v1.LlmCatalogService.RegisterModel:output_type -> open_foundry.ai.v1.Model
	5,  // 26: open_foundry.ai.v1.LlmCatalogService.ListModels:output_type -> open_foundry.ai.v1.ListModelsResponse
	2,  // 27: open_foundry.ai.v1.LlmCatalogService.GetModel:output_type -> open_foundry.ai.v1.Model
	2,  // 28: open_foundry.ai.v1.LlmCatalogService.EnableModel:output_type -> open_foundry.ai.v1.Model
	2,  // 29: open_foundry.ai.v1.LlmCatalogService.DisableModel:output_type -> open_foundry.ai.v1.Model
	13, // 30: open_foundry.ai.v1.LlmCatalogService.Invoke:output_type -> open_foundry.ai.v1.InvokeResponse
	14, // 31: open_foundry.ai.v1.LlmCatalogService.InvokeStream:output_type -> open_foundry.ai.v1.InvokeStreamChunk
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ai_v1_llm_catalog_proto_init() }
func file_ai_v1_llm_catalog_proto_init() {
	if File_ai_v1_llm_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_llm_catalog_proto_rawDesc), len(file_ai_v1_llm_catalog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_llm_catalog_proto_goTypes,
		DependencyIndexes: file_ai_v1_llm_catalog_proto_depIdxs,
		EnumInfos:         file_ai_v1_llm_catalog_proto_enumTypes,
		MessageInfos:      file_ai_v1_llm_catalog_proto_msgTypes,
	}.Build()
	File_ai_v1_llm_catalog_proto = out.File
	file_ai_v1_llm_catalog_proto_goTypes = nil
	file_ai_v1_llm_catalog_proto_depIdxs = nil
}
