// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteQueryRequest {
    #[prost(string, tag="1")]
    pub sql: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub limit: i32,
    #[prost(int32, tag="3")]
    pub offset: i32,
    #[prost(map="string, string", tag="4")]
    pub parameters: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryResult {
    #[prost(message, repeated, tag="1")]
    pub columns: ::prost::alloc::vec::Vec<ColumnMeta>,
    #[prost(message, repeated, tag="2")]
    pub rows: ::prost::alloc::vec::Vec<RowData>,
    #[prost(int64, tag="3")]
    pub total_rows: i64,
    #[prost(int64, tag="4")]
    pub execution_time_ms: i64,
    #[prost(int64, tag="5")]
    pub rows_scanned: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ColumnMeta {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub data_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RowData {
    #[prost(string, repeated, tag="1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExplainQueryRequest {
    #[prost(string, tag="1")]
    pub sql: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExplainQueryResponse {
    #[prost(string, tag="1")]
    pub logical_plan: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub physical_plan: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SaveQueryRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub sql: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SavedQuery {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub sql: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub owner_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSavedQueriesRequest {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
    #[prost(string, tag="2")]
    pub search: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSavedQueriesResponse {
    #[prost(message, repeated, tag="1")]
    pub queries: ::prost::alloc::vec::Vec<SavedQuery>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSavedQueryRequest {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSavedQueryResponse {
}
include!("open_foundry.query.tonic.rs");
// @@protoc_insertion_point(module)