// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cell {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub notebook_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub cell_type: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub kernel: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub source: ::prost::alloc::string::String,
    #[prost(int32, tag="6")]
    pub position: i32,
    #[prost(message, optional, tag="7")]
    pub last_output: ::core::option::Option<super::google::protobuf::Value>,
    #[prost(int32, tag="8")]
    pub execution_count: i32,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="10")]
    pub updated_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCellRequest {
    #[prost(string, tag="1")]
    pub notebook_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub cell_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub kernel: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub source: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub position: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateCellRequest {
    #[prost(string, tag="1")]
    pub cell_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub cell_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub kernel: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="5")]
    pub position: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteCellRequest {
    #[prost(string, tag="1")]
    pub cell_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CellOutput {
    #[prost(string, tag="1")]
    pub output_type: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub content: ::core::option::Option<super::google::protobuf::Value>,
    #[prost(int32, tag="3")]
    pub execution_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Session {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub notebook_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub kernel: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub started_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub last_activity: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSessionRequest {
    #[prost(string, tag="1")]
    pub notebook_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub kernel: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopSessionRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSessionsRequest {
    #[prost(string, tag="1")]
    pub notebook_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsResponse {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Notebook {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub owner_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub default_kernel: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub updated_at: ::core::option::Option<super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateNotebookRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub default_kernel: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateNotebookRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub default_kernel: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetNotebookRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListNotebooksRequest {
    #[prost(int32, tag="1")]
    pub page: i32,
    #[prost(int32, tag="2")]
    pub per_page: i32,
    #[prost(string, tag="3")]
    pub search: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListNotebooksResponse {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<Notebook>,
    #[prost(int64, tag="2")]
    pub total: i64,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub per_page: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteNotebookRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
include!("notebook.tonic.rs");
// @@protoc_insertion_point(module)