// This file is generated by `go run ./tools/of-cli docs generate-sdk-typescript`.
// Do not edit manually.

import {
  OpenFoundryClient,
  type OpenFoundryOperationInput,
  type OpenFoundryRequestInit,
} from './index';

export interface OpenFoundryMcpTool {
  name: string;
  description: string;
  operationId: string;
  method: string;
  path: string;
  namespace: string;
  namespaceMember: string;
  inputSchema: Record<string, unknown>;
  apiVersion?: string;
  stability?: string;
}

export const OPENFOUNDRY_MCP_TOOLS: ReadonlyArray<OpenFoundryMcpTool> = [
  {
    name: "openfoundry.auth.assignrole",
    description: "Generated from `open_foundry.auth` RPC `AssignRole` in service `RbacService`.",
    operationId: "open_foundry.auth.RbacService.AssignRole",
    method: "POST",
    path: "/api/v1/auth/assign-role",
    namespace: "auth",
    namespaceMember: "assignrole",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/AssignRoleRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auth.getme",
    description: "Generated from `open_foundry.auth` RPC `GetMe` in service `AuthService`.",
    operationId: "open_foundry.auth.AuthService.GetMe",
    method: "GET",
    path: "/api/v1/auth/get-me",
    namespace: "auth",
    namespaceMember: "getme",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auth.listroles",
    description: "Generated from `open_foundry.auth` RPC `ListRoles` in service `RbacService`.",
    operationId: "open_foundry.auth.RbacService.ListRoles",
    method: "GET",
    path: "/api/v1/auth/list-roles",
    namespace: "auth",
    namespaceMember: "listroles",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auth.login",
    description: "Generated from `open_foundry.auth` RPC `Login` in service `AuthService`.",
    operationId: "open_foundry.auth.AuthService.Login",
    method: "POST",
    path: "/api/v1/auth/login",
    namespace: "auth",
    namespaceMember: "login",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/LoginRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auth.refreshtoken",
    description: "Generated from `open_foundry.auth` RPC `RefreshToken` in service `AuthService`.",
    operationId: "open_foundry.auth.AuthService.RefreshToken",
    method: "POST",
    path: "/api/v1/auth/refresh-token",
    namespace: "auth",
    namespaceMember: "refreshtoken",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RefreshRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auth.register",
    description: "Generated from `open_foundry.auth` RPC `Register` in service `AuthService`.",
    operationId: "open_foundry.auth.AuthService.Register",
    method: "POST",
    path: "/api/v1/auth/register",
    namespace: "auth",
    namespaceMember: "register",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RegisterRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.common.check",
    description: "Generated from `open_foundry.common` RPC `Check` in service `HealthService`.",
    operationId: "open_foundry.common.HealthService.Check",
    method: "POST",
    path: "/api/v1/common/check",
    namespace: "common",
    namespaceMember: "check",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/HealthCheckRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.cancelingestjob",
    description: "Generated from `open_foundry.data_integration` RPC `CancelIngestJob` in service `IngestJobService`.",
    operationId: "open_foundry.data_integration.IngestJobService.CancelIngestJob",
    method: "POST",
    path: "/api/v1/data-integration/cancel-ingest-job",
    namespace: "dataIntegration",
    namespaceMember: "cancelingestjob",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CancelIngestJobRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.createconnection",
    description: "Generated from `open_foundry.data_integration` RPC `CreateConnection` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.CreateConnection",
    method: "POST",
    path: "/api/v1/data-integration/create-connection",
    namespace: "dataIntegration",
    namespaceMember: "createconnection",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateConnectionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.deleteconnection",
    description: "Generated from `open_foundry.data_integration` RPC `DeleteConnection` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.DeleteConnection",
    method: "DELETE",
    path: "/api/v1/data-integration/delete-connection",
    namespace: "dataIntegration",
    namespaceMember: "deleteconnection",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.getingestjob",
    description: "Generated from `open_foundry.data_integration` RPC `GetIngestJob` in service `IngestJobService`.",
    operationId: "open_foundry.data_integration.IngestJobService.GetIngestJob",
    method: "GET",
    path: "/api/v1/data-integration/get-ingest-job",
    namespace: "dataIntegration",
    namespaceMember: "getingestjob",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.inferschema",
    description: "Generated from `open_foundry.data_integration` RPC `InferSchema` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.InferSchema",
    method: "POST",
    path: "/api/v1/data-integration/infer-schema",
    namespace: "dataIntegration",
    namespaceMember: "inferschema",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/InferSchemaRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.listconnections",
    description: "Generated from `open_foundry.data_integration` RPC `ListConnections` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.ListConnections",
    method: "GET",
    path: "/api/v1/data-integration/list-connections",
    namespace: "dataIntegration",
    namespaceMember: "listconnections",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.listingestjobs",
    description: "Generated from `open_foundry.data_integration` RPC `ListIngestJobs` in service `IngestJobService`.",
    operationId: "open_foundry.data_integration.IngestJobService.ListIngestJobs",
    method: "GET",
    path: "/api/v1/data-integration/list-ingest-jobs",
    namespace: "dataIntegration",
    namespaceMember: "listingestjobs",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "connection_id": {
                "$ref": "#/components/schemas/Uuid"
              },
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.queueingestjob",
    description: "Generated from `open_foundry.data_integration` RPC `QueueIngestJob` in service `IngestJobService`.",
    operationId: "open_foundry.data_integration.IngestJobService.QueueIngestJob",
    method: "POST",
    path: "/api/v1/data-integration/queue-ingest-job",
    namespace: "dataIntegration",
    namespaceMember: "queueingestjob",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/QueueIngestJobRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.syncconnection",
    description: "Generated from `open_foundry.data_integration` RPC `SyncConnection` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.SyncConnection",
    method: "POST",
    path: "/api/v1/data-integration/sync-connection",
    namespace: "dataIntegration",
    namespaceMember: "syncconnection",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/SyncConnectionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.testconnection",
    description: "Generated from `open_foundry.data_integration` RPC `TestConnection` in service `ConnectorService`.",
    operationId: "open_foundry.data_integration.ConnectorService.TestConnection",
    method: "POST",
    path: "/api/v1/data-integration/test-connection",
    namespace: "dataIntegration",
    namespaceMember: "testconnection",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/TestConnectionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataIntegration.watchingestjob",
    description: "Generated from `open_foundry.data_integration` RPC `WatchIngestJob` in service `IngestJobService`.",
    operationId: "open_foundry.data_integration.IngestJobService.WatchIngestJob",
    method: "POST",
    path: "/api/v1/data-integration/watch-ingest-job",
    namespace: "dataIntegration",
    namespaceMember: "watchingestjob",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/WatchIngestJobRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.createdataset",
    description: "Generated from `open_foundry.dataset` RPC `CreateDataset` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.CreateDataset",
    method: "POST",
    path: "/api/v1/datasets/create-dataset",
    namespace: "dataset",
    namespaceMember: "createdataset",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateDatasetRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.deletedataset",
    description: "Generated from `open_foundry.dataset` RPC `DeleteDataset` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.DeleteDataset",
    method: "DELETE",
    path: "/api/v1/datasets/delete-dataset",
    namespace: "dataset",
    namespaceMember: "deletedataset",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.getdataset",
    description: "Generated from `open_foundry.dataset` RPC `GetDataset` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.GetDataset",
    method: "GET",
    path: "/api/v1/datasets/get-dataset",
    namespace: "dataset",
    namespaceMember: "getdataset",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.getversions",
    description: "Generated from `open_foundry.dataset` RPC `GetVersions` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.GetVersions",
    method: "GET",
    path: "/api/v1/datasets/get-versions",
    namespace: "dataset",
    namespaceMember: "getversions",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "dataset_id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.listdatasets",
    description: "Generated from `open_foundry.dataset` RPC `ListDatasets` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.ListDatasets",
    method: "GET",
    path: "/api/v1/datasets/list-datasets",
    namespace: "dataset",
    namespaceMember: "listdatasets",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "search": {
                "type": "string"
              },
              "tags": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.previewdata",
    description: "Generated from `open_foundry.dataset` RPC `PreviewData` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.PreviewData",
    method: "POST",
    path: "/api/v1/datasets/preview-data",
    namespace: "dataset",
    namespaceMember: "previewdata",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/PreviewDataRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.dataset.updatedataset",
    description: "Generated from `open_foundry.dataset` RPC `UpdateDataset` in service `DatasetService`.",
    operationId: "open_foundry.dataset.DatasetService.UpdateDataset",
    method: "PATCH",
    path: "/api/v1/datasets/update-dataset",
    namespace: "dataset",
    namespaceMember: "updatedataset",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateDatasetRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.aborttransaction",
    description: "Generated from `open_foundry.media_set` RPC `AbortTransaction` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.AbortTransaction",
    method: "POST",
    path: "/api/v1/media-set/abort-transaction",
    namespace: "mediaSet",
    namespaceMember: "aborttransaction",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/AbortTransactionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.committransaction",
    description: "Generated from `open_foundry.media_set` RPC `CommitTransaction` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.CommitTransaction",
    method: "POST",
    path: "/api/v1/media-set/commit-transaction",
    namespace: "mediaSet",
    namespaceMember: "committransaction",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CommitTransactionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.createmediaset",
    description: "Generated from `open_foundry.media_set` RPC `CreateMediaSet` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.CreateMediaSet",
    method: "POST",
    path: "/api/v1/media-set/create-media-set",
    namespace: "mediaSet",
    namespaceMember: "createmediaset",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateMediaSetRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.deletemediaitem",
    description: "Generated from `open_foundry.media_set` RPC `DeleteMediaItem` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.DeleteMediaItem",
    method: "DELETE",
    path: "/api/v1/media-set/delete-media-item",
    namespace: "mediaSet",
    namespaceMember: "deletemediaitem",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.deletemediaset",
    description: "Generated from `open_foundry.media_set` RPC `DeleteMediaSet` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.DeleteMediaSet",
    method: "DELETE",
    path: "/api/v1/media-set/delete-media-set",
    namespace: "mediaSet",
    namespaceMember: "deletemediaset",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.generatepresigneddownloadurl",
    description: "Generated from `open_foundry.media_set` RPC `GeneratePresignedDownloadUrl` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.GeneratePresignedDownloadUrl",
    method: "POST",
    path: "/api/v1/media-set/generate-presigned-download-url",
    namespace: "mediaSet",
    namespaceMember: "generatepresigneddownloadurl",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/GeneratePresignedDownloadUrlRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.generatepresigneduploadurl",
    description: "Generated from `open_foundry.media_set` RPC `GeneratePresignedUploadUrl` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.GeneratePresignedUploadUrl",
    method: "POST",
    path: "/api/v1/media-set/generate-presigned-upload-url",
    namespace: "mediaSet",
    namespaceMember: "generatepresigneduploadurl",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/GeneratePresignedUploadUrlRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.getmediaitem",
    description: "Generated from `open_foundry.media_set` RPC `GetMediaItem` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.GetMediaItem",
    method: "GET",
    path: "/api/v1/media-set/get-media-item",
    namespace: "mediaSet",
    namespaceMember: "getmediaitem",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.getmediaset",
    description: "Generated from `open_foundry.media_set` RPC `GetMediaSet` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.GetMediaSet",
    method: "GET",
    path: "/api/v1/media-set/get-media-set",
    namespace: "mediaSet",
    namespaceMember: "getmediaset",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.listaccesspatterns",
    description: "Generated from `open_foundry.media_set` RPC `ListAccessPatterns` in service `AccessPatternService`.",
    operationId: "open_foundry.media_set.AccessPatternService.ListAccessPatterns",
    method: "GET",
    path: "/api/v1/media-set/list-access-patterns",
    namespace: "mediaSet",
    namespaceMember: "listaccesspatterns",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "media_set_rid": {
                "type": "string"
              },
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.listmediaitems",
    description: "Generated from `open_foundry.media_set` RPC `ListMediaItems` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.ListMediaItems",
    method: "GET",
    path: "/api/v1/media-set/list-media-items",
    namespace: "mediaSet",
    namespaceMember: "listmediaitems",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "branch": {
                "type": "string"
              },
              "media_set_rid": {
                "type": "string"
              },
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "path_prefix": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.listmediasets",
    description: "Generated from `open_foundry.media_set` RPC `ListMediaSets` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.ListMediaSets",
    method: "GET",
    path: "/api/v1/media-set/list-media-sets",
    namespace: "mediaSet",
    namespaceMember: "listmediasets",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "project_rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.opentransaction",
    description: "Generated from `open_foundry.media_set` RPC `OpenTransaction` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.OpenTransaction",
    method: "POST",
    path: "/api/v1/media-set/open-transaction",
    namespace: "mediaSet",
    namespaceMember: "opentransaction",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/OpenTransactionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.registeraccesspattern",
    description: "Generated from `open_foundry.media_set` RPC `RegisterAccessPattern` in service `AccessPatternService`.",
    operationId: "open_foundry.media_set.AccessPatternService.RegisterAccessPattern",
    method: "POST",
    path: "/api/v1/media-set/register-access-pattern",
    namespace: "mediaSet",
    namespaceMember: "registeraccesspattern",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RegisterAccessPatternRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.registervirtualmediaitem",
    description: "Generated from `open_foundry.media_set` RPC `RegisterVirtualMediaItem` in service `MediaSetService`.",
    operationId: "open_foundry.media_set.MediaSetService.RegisterVirtualMediaItem",
    method: "POST",
    path: "/api/v1/media-set/register-virtual-media-item",
    namespace: "mediaSet",
    namespaceMember: "registervirtualmediaitem",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RegisterVirtualMediaItemRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.mediaSet.runaccesspattern",
    description: "Generated from `open_foundry.media_set` RPC `RunAccessPattern` in service `AccessPatternService`.",
    operationId: "open_foundry.media_set.AccessPatternService.RunAccessPattern",
    method: "POST",
    path: "/api/v1/media-set/run-access-pattern",
    namespace: "mediaSet",
    namespaceMember: "runaccesspattern",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RunAccessPatternRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.createnotebook",
    description: "Generated from `notebook` RPC `CreateNotebook` in service `NotebookService`.",
    operationId: "notebook.NotebookService.CreateNotebook",
    method: "POST",
    path: "/api/v1/notebook/create-notebook",
    namespace: "notebook",
    namespaceMember: "createnotebook",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateNotebookRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.createsession",
    description: "Generated from `notebook` RPC `CreateSession` in service `KernelService`.",
    operationId: "notebook.KernelService.CreateSession",
    method: "POST",
    path: "/api/v1/notebook/create-session",
    namespace: "notebook",
    namespaceMember: "createsession",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateSessionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.deletenotebook",
    description: "Generated from `notebook` RPC `DeleteNotebook` in service `NotebookService`.",
    operationId: "notebook.NotebookService.DeleteNotebook",
    method: "DELETE",
    path: "/api/v1/notebook/delete-notebook",
    namespace: "notebook",
    namespaceMember: "deletenotebook",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.getnotebook",
    description: "Generated from `notebook` RPC `GetNotebook` in service `NotebookService`.",
    operationId: "notebook.NotebookService.GetNotebook",
    method: "GET",
    path: "/api/v1/notebook/get-notebook",
    namespace: "notebook",
    namespaceMember: "getnotebook",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.listnotebooks",
    description: "Generated from `notebook` RPC `ListNotebooks` in service `NotebookService`.",
    operationId: "notebook.NotebookService.ListNotebooks",
    method: "GET",
    path: "/api/v1/notebook/list-notebooks",
    namespace: "notebook",
    namespaceMember: "listnotebooks",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "page": {
                "format": "int32",
                "type": "integer"
              },
              "per_page": {
                "format": "int32",
                "type": "integer"
              },
              "search": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.listsessions",
    description: "Generated from `notebook` RPC `ListSessions` in service `KernelService`.",
    operationId: "notebook.KernelService.ListSessions",
    method: "GET",
    path: "/api/v1/notebook/list-sessions",
    namespace: "notebook",
    namespaceMember: "listsessions",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "notebook_id": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.stopsession",
    description: "Generated from `notebook` RPC `StopSession` in service `KernelService`.",
    operationId: "notebook.KernelService.StopSession",
    method: "POST",
    path: "/api/v1/notebook/stop-session",
    namespace: "notebook",
    namespaceMember: "stopsession",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/StopSessionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.notebook.updatenotebook",
    description: "Generated from `notebook` RPC `UpdateNotebook` in service `NotebookService`.",
    operationId: "notebook.NotebookService.UpdateNotebook",
    method: "PATCH",
    path: "/api/v1/notebook/update-notebook",
    namespace: "notebook",
    namespaceMember: "updatenotebook",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateNotebookRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.binddataset",
    description: "Generated from `open_foundry.ontology` RPC `BindDataset` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.BindDataset",
    method: "POST",
    path: "/api/v1/ontology/bind-dataset",
    namespace: "ontology",
    namespaceMember: "binddataset",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/BindDatasetRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.createlinktype",
    description: "Generated from `open_foundry.ontology` RPC `CreateLinkType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.CreateLinkType",
    method: "POST",
    path: "/api/v1/ontology/create-link-type",
    namespace: "ontology",
    namespaceMember: "createlinktype",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateLinkTypeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.createobject",
    description: "Generated from `open_foundry.ontology` RPC `CreateObject` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.CreateObject",
    method: "POST",
    path: "/api/v1/ontology/create-object",
    namespace: "ontology",
    namespaceMember: "createobject",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateObjectRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.createobjecttype",
    description: "Generated from `open_foundry.ontology` RPC `CreateObjectType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.CreateObjectType",
    method: "POST",
    path: "/api/v1/ontology/create-object-type",
    namespace: "ontology",
    namespaceMember: "createobjecttype",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateObjectTypeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.createproperty",
    description: "Generated from `open_foundry.ontology` RPC `CreateProperty` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.CreateProperty",
    method: "POST",
    path: "/api/v1/ontology/create-property",
    namespace: "ontology",
    namespaceMember: "createproperty",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreatePropertyRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.deletelinktype",
    description: "Generated from `open_foundry.ontology` RPC `DeleteLinkType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.DeleteLinkType",
    method: "DELETE",
    path: "/api/v1/ontology/delete-link-type",
    namespace: "ontology",
    namespaceMember: "deletelinktype",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.deleteobject",
    description: "Generated from `open_foundry.ontology` RPC `DeleteObject` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.DeleteObject",
    method: "DELETE",
    path: "/api/v1/ontology/delete-object",
    namespace: "ontology",
    namespaceMember: "deleteobject",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "object_type_id": {
                "type": "string"
              },
              "primary_key": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.deleteobjecttype",
    description: "Generated from `open_foundry.ontology` RPC `DeleteObjectType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.DeleteObjectType",
    method: "DELETE",
    path: "/api/v1/ontology/delete-object-type",
    namespace: "ontology",
    namespaceMember: "deleteobjecttype",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.getobject",
    description: "Generated from `open_foundry.ontology` RPC `GetObject` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.GetObject",
    method: "GET",
    path: "/api/v1/ontology/get-object",
    namespace: "ontology",
    namespaceMember: "getobject",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "object_type_id": {
                "type": "string"
              },
              "primary_key": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.getobjecttype",
    description: "Generated from `open_foundry.ontology` RPC `GetObjectType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.GetObjectType",
    method: "GET",
    path: "/api/v1/ontology/get-object-type",
    namespace: "ontology",
    namespaceMember: "getobjecttype",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.listlinktypes",
    description: "Generated from `open_foundry.ontology` RPC `ListLinkTypes` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.ListLinkTypes",
    method: "GET",
    path: "/api/v1/ontology/list-link-types",
    namespace: "ontology",
    namespaceMember: "listlinktypes",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "object_type_id": {
                "$ref": "#/components/schemas/Uuid"
              },
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.listobjecttypes",
    description: "Generated from `open_foundry.ontology` RPC `ListObjectTypes` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.ListObjectTypes",
    method: "GET",
    path: "/api/v1/ontology/list-object-types",
    namespace: "ontology",
    namespaceMember: "listobjecttypes",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "search": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.listobjects",
    description: "Generated from `open_foundry.ontology` RPC `ListObjects` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.ListObjects",
    method: "GET",
    path: "/api/v1/ontology/list-objects",
    namespace: "ontology",
    namespaceMember: "listobjects",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "cursor": {
                "type": "string"
              },
              "filters": {
                "items": {
                  "$ref": "#/components/schemas/PropertyFilter"
                },
                "type": "array"
              },
              "object_type_id": {
                "type": "string"
              },
              "page_size": {
                "format": "int32",
                "type": "integer"
              },
              "sort": {
                "items": {
                  "$ref": "#/components/schemas/PropertySort"
                },
                "type": "array"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.listproperties",
    description: "Generated from `open_foundry.ontology` RPC `ListProperties` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.ListProperties",
    method: "GET",
    path: "/api/v1/ontology/list-properties",
    namespace: "ontology",
    namespaceMember: "listproperties",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "object_type_id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.materializebinding",
    description: "Generated from `open_foundry.ontology` RPC `MaterializeBinding` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.MaterializeBinding",
    method: "POST",
    path: "/api/v1/ontology/materialize-binding",
    namespace: "ontology",
    namespaceMember: "materializebinding",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/MaterializeBindingRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.searchobjects",
    description: "Generated from `open_foundry.ontology` RPC `SearchObjects` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.SearchObjects",
    method: "POST",
    path: "/api/v1/ontology/search-objects",
    namespace: "ontology",
    namespaceMember: "searchobjects",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/SearchObjectsRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.traverselinks",
    description: "Generated from `open_foundry.ontology` RPC `TraverseLinks` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.TraverseLinks",
    method: "POST",
    path: "/api/v1/ontology/traverse-links",
    namespace: "ontology",
    namespaceMember: "traverselinks",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/TraverseLinksRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.unbinddataset",
    description: "Generated from `open_foundry.ontology` RPC `UnbindDataset` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.UnbindDataset",
    method: "POST",
    path: "/api/v1/ontology/unbind-dataset",
    namespace: "ontology",
    namespaceMember: "unbinddataset",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UnbindDatasetRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.updateobject",
    description: "Generated from `open_foundry.ontology` RPC `UpdateObject` in service `OntologyObjectService`.",
    operationId: "open_foundry.ontology.OntologyObjectService.UpdateObject",
    method: "PATCH",
    path: "/api/v1/ontology/update-object",
    namespace: "ontology",
    namespaceMember: "updateobject",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateObjectRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.ontology.updateobjecttype",
    description: "Generated from `open_foundry.ontology` RPC `UpdateObjectType` in service `OntologyService`.",
    operationId: "open_foundry.ontology.OntologyService.UpdateObjectType",
    method: "PATCH",
    path: "/api/v1/ontology/update-object-type",
    namespace: "ontology",
    namespaceMember: "updateobjecttype",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateObjectTypeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.createpipeline",
    description: "Generated from `open_foundry.pipeline` RPC `CreatePipeline` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.CreatePipeline",
    method: "POST",
    path: "/api/v1/pipelines/create-pipeline",
    namespace: "pipeline",
    namespaceMember: "createpipeline",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreatePipelineRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.createschedule",
    description: "Generated from `open_foundry.pipeline` RPC `CreateSchedule` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.CreateSchedule",
    method: "POST",
    path: "/api/v1/pipelines/create-schedule",
    namespace: "pipeline",
    namespaceMember: "createschedule",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateScheduleRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.deletepipeline",
    description: "Generated from `open_foundry.pipeline` RPC `DeletePipeline` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.DeletePipeline",
    method: "DELETE",
    path: "/api/v1/pipelines/delete-pipeline",
    namespace: "pipeline",
    namespaceMember: "deletepipeline",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.deleteschedule",
    description: "Generated from `open_foundry.pipeline` RPC `DeleteSchedule` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.DeleteSchedule",
    method: "DELETE",
    path: "/api/v1/pipelines/delete-schedule",
    namespace: "pipeline",
    namespaceMember: "deleteschedule",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.getdatasetlineage",
    description: "Generated from `open_foundry.pipeline` RPC `GetDatasetLineage` in service `LineageService`.",
    operationId: "open_foundry.pipeline.LineageService.GetDatasetLineage",
    method: "GET",
    path: "/api/v1/pipelines/get-dataset-lineage",
    namespace: "pipeline",
    namespaceMember: "getdatasetlineage",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "dataset_id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.getfulllineage",
    description: "Generated from `open_foundry.pipeline` RPC `GetFullLineage` in service `LineageService`.",
    operationId: "open_foundry.pipeline.LineageService.GetFullLineage",
    method: "GET",
    path: "/api/v1/pipelines/get-full-lineage",
    namespace: "pipeline",
    namespaceMember: "getfulllineage",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.getpipeline",
    description: "Generated from `open_foundry.pipeline` RPC `GetPipeline` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.GetPipeline",
    method: "GET",
    path: "/api/v1/pipelines/get-pipeline",
    namespace: "pipeline",
    namespaceMember: "getpipeline",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.getrun",
    description: "Generated from `open_foundry.pipeline` RPC `GetRun` in service `ScheduleRunsService`.",
    operationId: "open_foundry.pipeline.ScheduleRunsService.GetRun",
    method: "GET",
    path: "/api/v1/pipelines/get-run",
    namespace: "pipeline",
    namespaceMember: "getrun",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.getschedule",
    description: "Generated from `open_foundry.pipeline` RPC `GetSchedule` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.GetSchedule",
    method: "GET",
    path: "/api/v1/pipelines/get-schedule",
    namespace: "pipeline",
    namespaceMember: "getschedule",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.listpipelines",
    description: "Generated from `open_foundry.pipeline` RPC `ListPipelines` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.ListPipelines",
    method: "GET",
    path: "/api/v1/pipelines/list-pipelines",
    namespace: "pipeline",
    namespaceMember: "listpipelines",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "search": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.listruns",
    description: "Generated from `open_foundry.pipeline` RPC `ListRuns` in service `ScheduleRunsService`.",
    operationId: "open_foundry.pipeline.ScheduleRunsService.ListRuns",
    method: "GET",
    path: "/api/v1/pipelines/list-runs",
    namespace: "pipeline",
    namespaceMember: "listruns",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "limit": {
                "format": "int32",
                "type": "integer"
              },
              "offset": {
                "format": "int32",
                "type": "integer"
              },
              "outcome": {
                "$ref": "#/components/schemas/RunOutcome"
              },
              "schedule_rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.listschedules",
    description: "Generated from `open_foundry.pipeline` RPC `ListSchedules` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.ListSchedules",
    method: "GET",
    path: "/api/v1/pipelines/list-schedules",
    namespace: "pipeline",
    namespaceMember: "listschedules",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "include_paused": {
                "type": "boolean"
              },
              "owner": {
                "type": "string"
              },
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "project_rid": {
                "type": "string"
              },
              "query": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.previewnextfires",
    description: "Generated from `open_foundry.pipeline` RPC `PreviewNextFires` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.PreviewNextFires",
    method: "POST",
    path: "/api/v1/pipelines/preview-next-fires",
    namespace: "pipeline",
    namespaceMember: "previewnextfires",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/PreviewNextFiresRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.recordlineage",
    description: "Generated from `open_foundry.pipeline` RPC `RecordLineage` in service `LineageService`.",
    operationId: "open_foundry.pipeline.LineageService.RecordLineage",
    method: "POST",
    path: "/api/v1/pipelines/record-lineage",
    namespace: "pipeline",
    namespaceMember: "recordlineage",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RecordLineageRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.runschedulenow",
    description: "Generated from `open_foundry.pipeline` RPC `RunScheduleNow` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.RunScheduleNow",
    method: "POST",
    path: "/api/v1/pipelines/run-schedule-now",
    namespace: "pipeline",
    namespaceMember: "runschedulenow",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RunScheduleNowRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.triggerrun",
    description: "Generated from `open_foundry.pipeline` RPC `TriggerRun` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.TriggerRun",
    method: "POST",
    path: "/api/v1/pipelines/trigger-run",
    namespace: "pipeline",
    namespaceMember: "triggerrun",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/TriggerRunRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.updatepipeline",
    description: "Generated from `open_foundry.pipeline` RPC `UpdatePipeline` in service `PipelineService`.",
    operationId: "open_foundry.pipeline.PipelineService.UpdatePipeline",
    method: "PATCH",
    path: "/api/v1/pipelines/update-pipeline",
    namespace: "pipeline",
    namespaceMember: "updatepipeline",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdatePipelineRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.pipeline.updateschedule",
    description: "Generated from `open_foundry.pipeline` RPC `UpdateSchedule` in service `ScheduleService`.",
    operationId: "open_foundry.pipeline.ScheduleService.UpdateSchedule",
    method: "PATCH",
    path: "/api/v1/pipelines/update-schedule",
    namespace: "pipeline",
    namespaceMember: "updateschedule",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateScheduleRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.query.deletesavedquery",
    description: "Generated from `open_foundry.query` RPC `DeleteSavedQuery` in service `QueryService`.",
    operationId: "open_foundry.query.QueryService.DeleteSavedQuery",
    method: "DELETE",
    path: "/api/v1/queries/delete-saved-query",
    namespace: "query",
    namespaceMember: "deletesavedquery",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "id": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.query.executequery",
    description: "Generated from `open_foundry.query` RPC `ExecuteQuery` in service `QueryService`.",
    operationId: "open_foundry.query.QueryService.ExecuteQuery",
    method: "POST",
    path: "/api/v1/queries/execute-query",
    namespace: "query",
    namespaceMember: "executequery",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExecuteQueryRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.query.explainquery",
    description: "Generated from `open_foundry.query` RPC `ExplainQuery` in service `QueryService`.",
    operationId: "open_foundry.query.QueryService.ExplainQuery",
    method: "POST",
    path: "/api/v1/queries/explain-query",
    namespace: "query",
    namespaceMember: "explainquery",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExplainQueryRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.query.listsavedqueries",
    description: "Generated from `open_foundry.query` RPC `ListSavedQueries` in service `QueryService`.",
    operationId: "open_foundry.query.QueryService.ListSavedQueries",
    method: "GET",
    path: "/api/v1/queries/list-saved-queries",
    namespace: "query",
    namespaceMember: "listsavedqueries",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "pagination": {
                "$ref": "#/components/schemas/PageRequest"
              },
              "search": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.query.savequery",
    description: "Generated from `open_foundry.query` RPC `SaveQuery` in service `QueryService`.",
    operationId: "open_foundry.query.QueryService.SaveQuery",
    method: "POST",
    path: "/api/v1/queries/save-query",
    namespace: "query",
    namespaceMember: "savequery",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/SaveQueryRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.runtime.dropsession",
    description: "Generated from `runtime` RPC `DropSession` in service `PythonRuntimeService`.",
    operationId: "runtime.PythonRuntimeService.DropSession",
    method: "POST",
    path: "/api/v1/runtime/drop-session",
    namespace: "runtime",
    namespaceMember: "dropsession",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/DropSessionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.runtime.ensuresession",
    description: "Generated from `runtime` RPC `EnsureSession` in service `PythonRuntimeService`.",
    operationId: "runtime.PythonRuntimeService.EnsureSession",
    method: "POST",
    path: "/api/v1/runtime/ensure-session",
    namespace: "runtime",
    namespaceMember: "ensuresession",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/EnsureSessionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.runtime.executeinlinefunction",
    description: "Generated from `runtime` RPC `ExecuteInlineFunction` in service `PythonRuntimeService`.",
    operationId: "runtime.PythonRuntimeService.ExecuteInlineFunction",
    method: "POST",
    path: "/api/v1/runtime/execute-inline-function",
    namespace: "runtime",
    namespaceMember: "executeinlinefunction",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExecuteInlineFunctionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.runtime.executenotebookcell",
    description: "Generated from `runtime` RPC `ExecuteNotebookCell` in service `PythonRuntimeService`.",
    operationId: "runtime.PythonRuntimeService.ExecuteNotebookCell",
    method: "POST",
    path: "/api/v1/runtime/execute-notebook-cell",
    namespace: "runtime",
    namespaceMember: "executenotebookcell",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExecuteNotebookCellRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.runtime.executepipelinetransform",
    description: "Generated from `runtime` RPC `ExecutePipelineTransform` in service `PythonRuntimeService`.",
    operationId: "runtime.PythonRuntimeService.ExecutePipelineTransform",
    method: "POST",
    path: "/api/v1/runtime/execute-pipeline-transform",
    namespace: "runtime",
    namespaceMember: "executepipelinetransform",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExecutePipelineTransformRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.createproduct",
    description: "Generated from `open_foundry.marketplace.v1` RPC `CreateProduct` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.CreateProduct",
    method: "POST",
    path: "/api/v1/v1/create-product",
    namespace: "marketplaceV1",
    namespaceMember: "createproduct",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateProductRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.disablemodel",
    description: "Generated from `open_foundry.ai.v1` RPC `DisableModel` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.DisableModel",
    method: "POST",
    path: "/api/v1/v1/disable-model",
    namespace: "aiV1",
    namespaceMember: "disablemodel",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/DisableModelRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.enablemodel",
    description: "Generated from `open_foundry.ai.v1` RPC `EnableModel` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.EnableModel",
    method: "POST",
    path: "/api/v1/v1/enable-model",
    namespace: "aiV1",
    namespaceMember: "enablemodel",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/EnableModelRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auditV1.exportevents",
    description: "Generated from `open_foundry.audit.v1` RPC `ExportEvents` in service `AuditService`.",
    operationId: "open_foundry.audit.v1.AuditService.ExportEvents",
    method: "POST",
    path: "/api/v1/v1/export-events",
    namespace: "auditV1",
    namespaceMember: "exportevents",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/ExportEventsRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.getmodel",
    description: "Generated from `open_foundry.ai.v1` RPC `GetModel` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.GetModel",
    method: "GET",
    path: "/api/v1/v1/get-model",
    namespace: "aiV1",
    namespaceMember: "getmodel",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "$ref": "#/components/schemas/Uuid"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.getproduct",
    description: "Generated from `open_foundry.marketplace.v1` RPC `GetProduct` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.GetProduct",
    method: "GET",
    path: "/api/v1/v1/get-product",
    namespace: "marketplaceV1",
    namespaceMember: "getproduct",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.installproduct",
    description: "Generated from `open_foundry.marketplace.v1` RPC `InstallProduct` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.InstallProduct",
    method: "POST",
    path: "/api/v1/v1/install-product",
    namespace: "marketplaceV1",
    namespaceMember: "installproduct",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/InstallProductRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.invoke",
    description: "Generated from `open_foundry.ai.v1` RPC `Invoke` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.Invoke",
    method: "POST",
    path: "/api/v1/v1/invoke",
    namespace: "aiV1",
    namespaceMember: "invoke",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/InvokeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.invokestream",
    description: "Generated from `open_foundry.ai.v1` RPC `InvokeStream` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.InvokeStream",
    method: "POST",
    path: "/api/v1/v1/invoke-stream",
    namespace: "aiV1",
    namespaceMember: "invokestream",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/InvokeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.listinstallations",
    description: "Generated from `open_foundry.marketplace.v1` RPC `ListInstallations` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.ListInstallations",
    method: "GET",
    path: "/api/v1/v1/list-installations",
    namespace: "marketplaceV1",
    namespaceMember: "listinstallations",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "limit": {
                "format": "int32",
                "type": "integer"
              },
              "offset": {
                "format": "int32",
                "type": "integer"
              },
              "product_rid": {
                "type": "string"
              },
              "target_workspace_rid": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.listmodels",
    description: "Generated from `open_foundry.ai.v1` RPC `ListModels` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.ListModels",
    method: "GET",
    path: "/api/v1/v1/list-models",
    namespace: "aiV1",
    namespaceMember: "listmodels",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "only_enabled": {
                "type": "boolean"
              },
              "provider": {
                "$ref": "#/components/schemas/Provider"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.listproducts",
    description: "Generated from `open_foundry.marketplace.v1` RPC `ListProducts` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.ListProducts",
    method: "GET",
    path: "/api/v1/v1/list-products",
    namespace: "marketplaceV1",
    namespaceMember: "listproducts",
    inputSchema:
      {
        "properties": {
          "query": {
            "properties": {
              "limit": {
                "format": "int32",
                "type": "integer"
              },
              "offset": {
                "format": "int32",
                "type": "integer"
              },
              "status": {
                "$ref": "#/components/schemas/ProductStatus"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.openfoundryStreamingRouterV1.publish",
    description: "Generated from `openfoundry.streaming.router.v1` RPC `Publish` in service `EventRouter`.",
    operationId: "openfoundry.streaming.router.v1.EventRouter.Publish",
    method: "POST",
    path: "/api/v1/v1/publish",
    namespace: "openfoundryStreamingRouterV1",
    namespaceMember: "publish",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/PublishRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.publishversion",
    description: "Generated from `open_foundry.marketplace.v1` RPC `PublishVersion` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.PublishVersion",
    method: "POST",
    path: "/api/v1/v1/publish-version",
    namespace: "marketplaceV1",
    namespaceMember: "publishversion",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/PublishVersionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auditV1.queryevents",
    description: "Generated from `open_foundry.audit.v1` RPC `QueryEvents` in service `AuditService`.",
    operationId: "open_foundry.audit.v1.AuditService.QueryEvents",
    method: "POST",
    path: "/api/v1/v1/query-events",
    namespace: "auditV1",
    namespaceMember: "queryevents",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/QueryEventsRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.auditV1.recordevent",
    description: "Generated from `open_foundry.audit.v1` RPC `RecordEvent` in service `AuditService`.",
    operationId: "open_foundry.audit.v1.AuditService.RecordEvent",
    method: "POST",
    path: "/api/v1/v1/record-event",
    namespace: "auditV1",
    namespaceMember: "recordevent",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RecordEventRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.aiV1.registermodel",
    description: "Generated from `open_foundry.ai.v1` RPC `RegisterModel` in service `LlmCatalogService`.",
    operationId: "open_foundry.ai.v1.LlmCatalogService.RegisterModel",
    method: "POST",
    path: "/api/v1/v1/register-model",
    namespace: "aiV1",
    namespaceMember: "registermodel",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/RegisterModelRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.openfoundryStreamingRouterV1.subscribe",
    description: "Generated from `openfoundry.streaming.router.v1` RPC `Subscribe` in service `EventRouter`.",
    operationId: "openfoundry.streaming.router.v1.EventRouter.Subscribe",
    method: "POST",
    path: "/api/v1/v1/subscribe",
    namespace: "openfoundryStreamingRouterV1",
    namespaceMember: "subscribe",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/SubscribeRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.marketplaceV1.uninstall",
    description: "Generated from `open_foundry.marketplace.v1` RPC `Uninstall` in service `MarketplaceProductService`.",
    operationId: "open_foundry.marketplace.v1.MarketplaceProductService.Uninstall",
    method: "POST",
    path: "/api/v1/v1/uninstall",
    namespace: "marketplaceV1",
    namespaceMember: "uninstall",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UninstallRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v1",
    stability: "beta",
  },
  {
    name: "openfoundry.adminV2.getcontrolpanel",
    description: "Curated REST overlay for `rest.admin.v2.getControlPanel`.",
    operationId: "rest.admin.v2.getControlPanel",
    method: "GET",
    path: "/api/v2/admin/control-panel",
    namespace: "adminV2",
    namespaceMember: "getcontrolpanel",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.updatecontrolpanel",
    description: "Curated REST overlay for `rest.admin.v2.updateControlPanel`.",
    operationId: "rest.admin.v2.updateControlPanel",
    method: "PUT",
    path: "/api/v2/admin/control-panel",
    namespace: "adminV2",
    namespaceMember: "updatecontrolpanel",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateControlPanelRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.listgroups",
    description: "Curated REST overlay for `rest.admin.v2.listGroups`.",
    operationId: "rest.admin.v2.listGroups",
    method: "GET",
    path: "/api/v2/admin/groups",
    namespace: "adminV2",
    namespaceMember: "listgroups",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.creategroup",
    description: "Curated REST overlay for `rest.admin.v2.createGroup`.",
    operationId: "rest.admin.v2.createGroup",
    method: "POST",
    path: "/api/v2/admin/groups",
    namespace: "adminV2",
    namespaceMember: "creategroup",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateGroupRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.updategroup",
    description: "Curated REST overlay for `rest.admin.v2.updateGroup`.",
    operationId: "rest.admin.v2.updateGroup",
    method: "PUT",
    path: "/api/v2/admin/groups/{id}",
    namespace: "adminV2",
    namespaceMember: "updategroup",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateGroupRequest"
          },
          "path": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "required": [
              "id"
            ],
            "type": "object"
          }
        },
        "required": [
          "body",
          "path"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.listpermissions",
    description: "Curated REST overlay for `rest.admin.v2.listPermissions`.",
    operationId: "rest.admin.v2.listPermissions",
    method: "GET",
    path: "/api/v2/admin/permissions",
    namespace: "adminV2",
    namespaceMember: "listpermissions",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.createpermission",
    description: "Curated REST overlay for `rest.admin.v2.createPermission`.",
    operationId: "rest.admin.v2.createPermission",
    method: "POST",
    path: "/api/v2/admin/permissions",
    namespace: "adminV2",
    namespaceMember: "createpermission",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreatePermissionRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.listpolicies",
    description: "Curated REST overlay for `rest.admin.v2.listPolicies`.",
    operationId: "rest.admin.v2.listPolicies",
    method: "GET",
    path: "/api/v2/admin/policies",
    namespace: "adminV2",
    namespaceMember: "listpolicies",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.createpolicy",
    description: "Curated REST overlay for `rest.admin.v2.createPolicy`.",
    operationId: "rest.admin.v2.createPolicy",
    method: "POST",
    path: "/api/v2/admin/policies",
    namespace: "adminV2",
    namespaceMember: "createpolicy",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpsertPolicyRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.evaluatepolicy",
    description: "Curated REST overlay for `rest.admin.v2.evaluatePolicy`.",
    operationId: "rest.admin.v2.evaluatePolicy",
    method: "POST",
    path: "/api/v2/admin/policies/evaluate",
    namespace: "adminV2",
    namespaceMember: "evaluatepolicy",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/EvaluatePolicyRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.updatepolicy",
    description: "Curated REST overlay for `rest.admin.v2.updatePolicy`.",
    operationId: "rest.admin.v2.updatePolicy",
    method: "PATCH",
    path: "/api/v2/admin/policies/{id}",
    namespace: "adminV2",
    namespaceMember: "updatepolicy",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpsertPolicyRequest"
          },
          "path": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "required": [
              "id"
            ],
            "type": "object"
          }
        },
        "required": [
          "body",
          "path"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.listroles",
    description: "Curated REST overlay for `rest.admin.v2.listRoles`.",
    operationId: "rest.admin.v2.listRoles",
    method: "GET",
    path: "/api/v2/admin/roles",
    namespace: "adminV2",
    namespaceMember: "listroles",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.createrole",
    description: "Curated REST overlay for `rest.admin.v2.createRole`.",
    operationId: "rest.admin.v2.createRole",
    method: "POST",
    path: "/api/v2/admin/roles",
    namespace: "adminV2",
    namespaceMember: "createrole",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/CreateRoleRequest"
          }
        },
        "required": [
          "body"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.updaterole",
    description: "Curated REST overlay for `rest.admin.v2.updateRole`.",
    operationId: "rest.admin.v2.updateRole",
    method: "PUT",
    path: "/api/v2/admin/roles/{id}",
    namespace: "adminV2",
    namespaceMember: "updaterole",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateRoleRequest"
          },
          "path": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "required": [
              "id"
            ],
            "type": "object"
          }
        },
        "required": [
          "body",
          "path"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.listusers",
    description: "Curated REST overlay for `rest.admin.v2.listUsers`.",
    operationId: "rest.admin.v2.listUsers",
    method: "GET",
    path: "/api/v2/admin/users",
    namespace: "adminV2",
    namespaceMember: "listusers",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.getcurrentuser",
    description: "Curated REST overlay for `rest.admin.v2.getCurrentUser`.",
    operationId: "rest.admin.v2.getCurrentUser",
    method: "GET",
    path: "/api/v2/admin/users/me",
    namespace: "adminV2",
    namespaceMember: "getcurrentuser",
    inputSchema:
      {
        "properties": {},
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.adminV2.updateuser",
    description: "Curated REST overlay for `rest.admin.v2.updateUser`.",
    operationId: "rest.admin.v2.updateUser",
    method: "PATCH",
    path: "/api/v2/admin/users/{id}",
    namespace: "adminV2",
    namespaceMember: "updateuser",
    inputSchema:
      {
        "properties": {
          "body": {
            "$ref": "#/components/schemas/UpdateUserRequest"
          },
          "path": {
            "properties": {
              "id": {
                "type": "string"
              }
            },
            "required": [
              "id"
            ],
            "type": "object"
          }
        },
        "required": [
          "body",
          "path"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
  {
    name: "openfoundry.filesystemV2.getdatasetfilesystem",
    description: "Curated REST overlay for `rest.filesystem.v2.getDatasetFilesystem`.",
    operationId: "rest.filesystem.v2.getDatasetFilesystem",
    method: "GET",
    path: "/api/v2/filesystem/datasets/{dataset_id}",
    namespace: "filesystemV2",
    namespaceMember: "getdatasetfilesystem",
    inputSchema:
      {
        "properties": {
          "path": {
            "properties": {
              "dataset_id": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id"
            ],
            "type": "object"
          },
          "query": {
            "properties": {
              "path": {
                "type": "string"
              }
            },
            "type": "object"
          }
        },
        "required": [
          "path"
        ],
        "type": "object"
      }
    ,
    apiVersion: "v2",
    stability: "stable",
  },
];

export function listOpenFoundryMcpTools(): ReadonlyArray<OpenFoundryMcpTool> {
  return OPENFOUNDRY_MCP_TOOLS;
}

export async function callOpenFoundryMcpTool(
  client: OpenFoundryClient,
  toolName: string,
  input: OpenFoundryOperationInput = {}, 
  init: OpenFoundryRequestInit = {}, 
): Promise<unknown> {
  const tool = OPENFOUNDRY_MCP_TOOLS.find((entry) => entry.name === toolName);
  if (!tool) {
    throw new Error(`Unknown OpenFoundry MCP tool: ${toolName}`);
  }
  return client.callOperation(tool.operationId, input, init);
}