// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublishRequest {
    /// Subject / topic to publish to (e.g. "ctrl.heartbeat", "data.orders.v1").
    #[prost(string, tag="1")]
    pub topic: ::prost::alloc::string::String,
    /// Opaque payload. The router does not interpret it (schema validation is
    /// optional and lives outside this PR).
    #[prost(bytes="vec", tag="2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Free-form headers propagated to the backend when the backend supports them.
    #[prost(map="string, string", tag="3")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Optional schema id (Apicurio artifact id). Reserved for PR 3.
    #[prost(string, optional, tag="4")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublishResponse {
    /// Identifier of the backend that handled the publish ("nats" or "kafka").
    #[prost(string, tag="1")]
    pub backend: ::prost::alloc::string::String,
    /// Pattern that matched the topic, or "<default>" when the default backend
    /// was used.
    #[prost(string, tag="2")]
    pub matched_pattern: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeRequest {
    /// Topic pattern. Same glob syntax as the routing table entries.
    #[prost(string, tag="1")]
    pub pattern: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMessage {
    /// Concrete topic the event was received on (without wildcards).
    #[prost(string, tag="1")]
    pub topic: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(map="string, string", tag="3")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub schema_id: ::core::option::Option<::prost::alloc::string::String>,
}
include!("openfoundry.streaming.router.v1.tonic.rs");
// @@protoc_insertion_point(module)