# This file is generated by `go run ./tools/of-cli docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

import json
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Mapping

from . import models

OPENFOUNDRY_SDK_VERSION = "0.1.0"

class OpenFoundryApiError(RuntimeError):
    pass

class _OperationNamespace:
    def __init__(self, **methods: Any) -> None:
        for name, method in methods.items():
            setattr(self, name, method)

class OpenFoundryClient:
    def __init__(self, base_url: str, headers: Mapping[str, str] | None = None, token: str | None = None, timeout_seconds: float = 30.0, max_retries: int = 1, retry_backoff_seconds: float = 0.25, user_agent: str | None = None) -> None:
        self.base_url = base_url.rstrip('/')
        self.default_headers = dict(headers or {})
        self.token = token
        self.timeout_seconds = timeout_seconds
        self.max_retries = max(1, max_retries)
        self.retry_backoff_seconds = retry_backoff_seconds
        self.user_agent = user_agent
        self.adminV2 = _OperationNamespace(getcontrolpanel=self.admin_v2_getcontrolpanel, updatecontrolpanel=self.admin_v2_updatecontrolpanel, listgroups=self.admin_v2_listgroups, creategroup=self.admin_v2_creategroup, updategroup=self.admin_v2_updategroup, listpermissions=self.admin_v2_listpermissions, createpermission=self.admin_v2_createpermission, listpolicies=self.admin_v2_listpolicies, createpolicy=self.admin_v2_createpolicy, evaluatepolicy=self.admin_v2_evaluatepolicy, updatepolicy=self.admin_v2_updatepolicy, listroles=self.admin_v2_listroles, createrole=self.admin_v2_createrole, updaterole=self.admin_v2_updaterole, listusers=self.admin_v2_listusers, getcurrentuser=self.admin_v2_getcurrentuser, updateuser=self.admin_v2_updateuser)
        self.aiV1 = _OperationNamespace(disablemodel=self.v1_llmcatalog_disablemodel, enablemodel=self.v1_llmcatalog_enablemodel, getmodel=self.v1_llmcatalog_getmodel, invoke=self.v1_llmcatalog_invoke, invokestream=self.v1_llmcatalog_invokestream, listmodels=self.v1_llmcatalog_listmodels, registermodel=self.v1_llmcatalog_registermodel)
        self.auditV1 = _OperationNamespace(exportevents=self.v1_audit_exportevents, queryevents=self.v1_audit_queryevents, recordevent=self.v1_audit_recordevent)
        self.auth = _OperationNamespace(assignrole=self.auth_rbac_assignrole, getme=self.auth_auth_getme, listroles=self.auth_rbac_listroles, login=self.auth_auth_login, refreshtoken=self.auth_auth_refreshtoken, register=self.auth_auth_register)
        self.common = _OperationNamespace(check=self.common_health_check)
        self.dataIntegration = _OperationNamespace(cancelingestjob=self.data_integration_ingestjob_cancelingestjob, createconnection=self.data_integration_connector_createconnection, deleteconnection=self.data_integration_connector_deleteconnection, getingestjob=self.data_integration_ingestjob_getingestjob, inferschema=self.data_integration_connector_inferschema, listconnections=self.data_integration_connector_listconnections, listingestjobs=self.data_integration_ingestjob_listingestjobs, queueingestjob=self.data_integration_ingestjob_queueingestjob, syncconnection=self.data_integration_connector_syncconnection, testconnection=self.data_integration_connector_testconnection, watchingestjob=self.data_integration_ingestjob_watchingestjob)
        self.dataset = _OperationNamespace(createdataset=self.dataset_dataset_createdataset, deletedataset=self.dataset_dataset_deletedataset, getdataset=self.dataset_dataset_getdataset, getversions=self.dataset_dataset_getversions, listdatasets=self.dataset_dataset_listdatasets, previewdata=self.dataset_dataset_previewdata, updatedataset=self.dataset_dataset_updatedataset)
        self.filesystemV2 = _OperationNamespace(getdatasetfilesystem=self.filesystem_v2_getdatasetfilesystem)
        self.marketplaceV1 = _OperationNamespace(createproduct=self.v1_marketplaceproduct_createproduct, getproduct=self.v1_marketplaceproduct_getproduct, installproduct=self.v1_marketplaceproduct_installproduct, listinstallations=self.v1_marketplaceproduct_listinstallations, listproducts=self.v1_marketplaceproduct_listproducts, publishversion=self.v1_marketplaceproduct_publishversion, uninstall=self.v1_marketplaceproduct_uninstall)
        self.mediaSet = _OperationNamespace(aborttransaction=self.media_set_mediaset_aborttransaction, committransaction=self.media_set_mediaset_committransaction, createmediaset=self.media_set_mediaset_createmediaset, deletemediaitem=self.media_set_mediaset_deletemediaitem, deletemediaset=self.media_set_mediaset_deletemediaset, generatepresigneddownloadurl=self.media_set_mediaset_generatepresigneddownloadurl, generatepresigneduploadurl=self.media_set_mediaset_generatepresigneduploadurl, getmediaitem=self.media_set_mediaset_getmediaitem, getmediaset=self.media_set_mediaset_getmediaset, listaccesspatterns=self.media_set_accesspattern_listaccesspatterns, listmediaitems=self.media_set_mediaset_listmediaitems, listmediasets=self.media_set_mediaset_listmediasets, opentransaction=self.media_set_mediaset_opentransaction, registeraccesspattern=self.media_set_accesspattern_registeraccesspattern, registervirtualmediaitem=self.media_set_mediaset_registervirtualmediaitem, runaccesspattern=self.media_set_accesspattern_runaccesspattern)
        self.notebook = _OperationNamespace(createnotebook=self.notebook_notebook_createnotebook, createsession=self.notebook_kernel_createsession, deletenotebook=self.notebook_notebook_deletenotebook, getnotebook=self.notebook_notebook_getnotebook, listnotebooks=self.notebook_notebook_listnotebooks, listsessions=self.notebook_kernel_listsessions, stopsession=self.notebook_kernel_stopsession, updatenotebook=self.notebook_notebook_updatenotebook)
        self.ontology = _OperationNamespace(binddataset=self.ontology_ontology_binddataset, createlinktype=self.ontology_ontology_createlinktype, createobject=self.ontology_ontologyobject_createobject, createobjecttype=self.ontology_ontology_createobjecttype, createproperty=self.ontology_ontology_createproperty, deletelinktype=self.ontology_ontology_deletelinktype, deleteobject=self.ontology_ontologyobject_deleteobject, deleteobjecttype=self.ontology_ontology_deleteobjecttype, getobject=self.ontology_ontologyobject_getobject, getobjecttype=self.ontology_ontology_getobjecttype, listlinktypes=self.ontology_ontology_listlinktypes, listobjecttypes=self.ontology_ontology_listobjecttypes, listobjects=self.ontology_ontologyobject_listobjects, listproperties=self.ontology_ontology_listproperties, materializebinding=self.ontology_ontology_materializebinding, searchobjects=self.ontology_ontologyobject_searchobjects, traverselinks=self.ontology_ontologyobject_traverselinks, unbinddataset=self.ontology_ontology_unbinddataset, updateobject=self.ontology_ontologyobject_updateobject, updateobjecttype=self.ontology_ontology_updateobjecttype)
        self.openfoundryStreamingRouterV1 = _OperationNamespace(publish=self.v1_eventrouter_publish, subscribe=self.v1_eventrouter_subscribe)
        self.pipeline = _OperationNamespace(createpipeline=self.pipeline_pipeline_createpipeline, createschedule=self.pipeline_schedule_createschedule, deletepipeline=self.pipeline_pipeline_deletepipeline, deleteschedule=self.pipeline_schedule_deleteschedule, getdatasetlineage=self.pipeline_lineage_getdatasetlineage, getfulllineage=self.pipeline_lineage_getfulllineage, getpipeline=self.pipeline_pipeline_getpipeline, getrun=self.pipeline_scheduleruns_getrun, getschedule=self.pipeline_schedule_getschedule, listpipelines=self.pipeline_pipeline_listpipelines, listruns=self.pipeline_scheduleruns_listruns, listschedules=self.pipeline_schedule_listschedules, previewnextfires=self.pipeline_schedule_previewnextfires, recordlineage=self.pipeline_lineage_recordlineage, runschedulenow=self.pipeline_schedule_runschedulenow, triggerrun=self.pipeline_pipeline_triggerrun, updatepipeline=self.pipeline_pipeline_updatepipeline, updateschedule=self.pipeline_schedule_updateschedule)
        self.query = _OperationNamespace(deletesavedquery=self.query_query_deletesavedquery, executequery=self.query_query_executequery, explainquery=self.query_query_explainquery, listsavedqueries=self.query_query_listsavedqueries, savequery=self.query_query_savequery)
        self.runtime = _OperationNamespace(dropsession=self.runtime_pythonruntime_dropsession, ensuresession=self.runtime_pythonruntime_ensuresession, executeinlinefunction=self.runtime_pythonruntime_executeinlinefunction, executenotebookcell=self.runtime_pythonruntime_executenotebookcell, executepipelinetransform=self.runtime_pythonruntime_executepipelinetransform)

    def clone(self, **overrides: Any) -> "OpenFoundryClient":
        return OpenFoundryClient(base_url=overrides.get("base_url", self.base_url), headers=overrides.get("headers", self.default_headers), token=overrides.get("token", self.token), timeout_seconds=overrides.get("timeout_seconds", self.timeout_seconds), max_retries=overrides.get("max_retries", self.max_retries), retry_backoff_seconds=overrides.get("retry_backoff_seconds", self.retry_backoff_seconds), user_agent=overrides.get("user_agent", self.user_agent))

    def with_bearer_token(self, token: str) -> "OpenFoundryClient":
        return self.clone(token=token)

    def auth_rbac_assignrole(self, body: models.AssignRoleRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/auth/assign-role", None, None, body, headers=headers)

    def auth_auth_getme(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/auth/get-me", None, None, None, headers=headers)

    def auth_rbac_listroles(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/auth/list-roles", None, None, None, headers=headers)

    def auth_auth_login(self, body: models.LoginRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/auth/login", None, None, body, headers=headers)

    def auth_auth_refreshtoken(self, body: models.RefreshRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/auth/refresh-token", None, None, body, headers=headers)

    def auth_auth_register(self, body: models.RegisterRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/auth/register", None, None, body, headers=headers)

    def common_health_check(self, body: models.HealthCheckRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/common/check", None, None, body, headers=headers)

    def data_integration_ingestjob_cancelingestjob(self, body: models.CancelIngestJobRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/cancel-ingest-job", None, None, body, headers=headers)

    def data_integration_connector_createconnection(self, body: models.CreateConnectionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/create-connection", None, None, body, headers=headers)

    def data_integration_connector_deleteconnection(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/data-integration/delete-connection", None, {"id": id}, None, headers=headers)

    def data_integration_ingestjob_getingestjob(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/data-integration/get-ingest-job", None, {"id": id}, None, headers=headers)

    def data_integration_connector_inferschema(self, body: models.InferSchemaRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/infer-schema", None, None, body, headers=headers)

    def data_integration_connector_listconnections(self, pagination: PageRequest | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/data-integration/list-connections", None, {"pagination": pagination}, None, headers=headers)

    def data_integration_ingestjob_listingestjobs(self, connection_id: Uuid | None = None, pagination: PageRequest | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/data-integration/list-ingest-jobs", None, {"connection_id": connection_id, "pagination": pagination}, None, headers=headers)

    def data_integration_ingestjob_queueingestjob(self, body: models.QueueIngestJobRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/queue-ingest-job", None, None, body, headers=headers)

    def data_integration_connector_syncconnection(self, body: models.SyncConnectionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/sync-connection", None, None, body, headers=headers)

    def data_integration_connector_testconnection(self, body: models.TestConnectionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/test-connection", None, None, body, headers=headers)

    def data_integration_ingestjob_watchingestjob(self, body: models.WatchIngestJobRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/data-integration/watch-ingest-job", None, None, body, headers=headers)

    def dataset_dataset_createdataset(self, body: models.CreateDatasetRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/datasets/create-dataset", None, None, body, headers=headers)

    def dataset_dataset_deletedataset(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/datasets/delete-dataset", None, {"id": id}, None, headers=headers)

    def dataset_dataset_getdataset(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/datasets/get-dataset", None, {"id": id}, None, headers=headers)

    def dataset_dataset_getversions(self, dataset_id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/datasets/get-versions", None, {"dataset_id": dataset_id}, None, headers=headers)

    def dataset_dataset_listdatasets(self, pagination: PageRequest | None = None, search: str | None = None, tags: list[str] | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/datasets/list-datasets", None, {"pagination": pagination, "search": search, "tags": tags}, None, headers=headers)

    def dataset_dataset_previewdata(self, body: models.PreviewDataRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/datasets/preview-data", None, None, body, headers=headers)

    def dataset_dataset_updatedataset(self, body: models.UpdateDatasetRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/datasets/update-dataset", None, None, body, headers=headers)

    def media_set_mediaset_aborttransaction(self, body: models.AbortTransactionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/abort-transaction", None, None, body, headers=headers)

    def media_set_mediaset_committransaction(self, body: models.CommitTransactionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/commit-transaction", None, None, body, headers=headers)

    def media_set_mediaset_createmediaset(self, body: models.CreateMediaSetRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/create-media-set", None, None, body, headers=headers)

    def media_set_mediaset_deletemediaitem(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/media-set/delete-media-item", None, {"rid": rid}, None, headers=headers)

    def media_set_mediaset_deletemediaset(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/media-set/delete-media-set", None, {"rid": rid}, None, headers=headers)

    def media_set_mediaset_generatepresigneddownloadurl(self, body: models.GeneratePresignedDownloadUrlRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/generate-presigned-download-url", None, None, body, headers=headers)

    def media_set_mediaset_generatepresigneduploadurl(self, body: models.GeneratePresignedUploadUrlRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/generate-presigned-upload-url", None, None, body, headers=headers)

    def media_set_mediaset_getmediaitem(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/media-set/get-media-item", None, {"rid": rid}, None, headers=headers)

    def media_set_mediaset_getmediaset(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/media-set/get-media-set", None, {"rid": rid}, None, headers=headers)

    def media_set_accesspattern_listaccesspatterns(self, media_set_rid: str | None = None, pagination: PageRequest | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/media-set/list-access-patterns", None, {"media_set_rid": media_set_rid, "pagination": pagination}, None, headers=headers)

    def media_set_mediaset_listmediaitems(self, branch: str | None = None, media_set_rid: str | None = None, pagination: PageRequest | None = None, path_prefix: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/media-set/list-media-items", None, {"branch": branch, "media_set_rid": media_set_rid, "pagination": pagination, "path_prefix": path_prefix}, None, headers=headers)

    def media_set_mediaset_listmediasets(self, pagination: PageRequest | None = None, project_rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/media-set/list-media-sets", None, {"pagination": pagination, "project_rid": project_rid}, None, headers=headers)

    def media_set_mediaset_opentransaction(self, body: models.OpenTransactionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/open-transaction", None, None, body, headers=headers)

    def media_set_accesspattern_registeraccesspattern(self, body: models.RegisterAccessPatternRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/register-access-pattern", None, None, body, headers=headers)

    def media_set_mediaset_registervirtualmediaitem(self, body: models.RegisterVirtualMediaItemRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/register-virtual-media-item", None, None, body, headers=headers)

    def media_set_accesspattern_runaccesspattern(self, body: models.RunAccessPatternRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/media-set/run-access-pattern", None, None, body, headers=headers)

    def notebook_notebook_createnotebook(self, body: models.CreateNotebookRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/notebook/create-notebook", None, None, body, headers=headers)

    def notebook_kernel_createsession(self, body: models.CreateSessionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/notebook/create-session", None, None, body, headers=headers)

    def notebook_notebook_deletenotebook(self, id: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/notebook/delete-notebook", None, {"id": id}, None, headers=headers)

    def notebook_notebook_getnotebook(self, id: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/notebook/get-notebook", None, {"id": id}, None, headers=headers)

    def notebook_notebook_listnotebooks(self, page: int | None = None, per_page: int | None = None, search: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/notebook/list-notebooks", None, {"page": page, "per_page": per_page, "search": search}, None, headers=headers)

    def notebook_kernel_listsessions(self, notebook_id: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/notebook/list-sessions", None, {"notebook_id": notebook_id}, None, headers=headers)

    def notebook_kernel_stopsession(self, body: models.StopSessionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/notebook/stop-session", None, None, body, headers=headers)

    def notebook_notebook_updatenotebook(self, body: models.UpdateNotebookRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/notebook/update-notebook", None, None, body, headers=headers)

    def ontology_ontology_binddataset(self, body: models.BindDatasetRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/bind-dataset", None, None, body, headers=headers)

    def ontology_ontology_createlinktype(self, body: models.CreateLinkTypeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/create-link-type", None, None, body, headers=headers)

    def ontology_ontologyobject_createobject(self, body: models.CreateObjectRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/create-object", None, None, body, headers=headers)

    def ontology_ontology_createobjecttype(self, body: models.CreateObjectTypeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/create-object-type", None, None, body, headers=headers)

    def ontology_ontology_createproperty(self, body: models.CreatePropertyRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/create-property", None, None, body, headers=headers)

    def ontology_ontology_deletelinktype(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/ontology/delete-link-type", None, {"id": id}, None, headers=headers)

    def ontology_ontologyobject_deleteobject(self, object_type_id: str | None = None, primary_key: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/ontology/delete-object", None, {"object_type_id": object_type_id, "primary_key": primary_key}, None, headers=headers)

    def ontology_ontology_deleteobjecttype(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/ontology/delete-object-type", None, {"id": id}, None, headers=headers)

    def ontology_ontologyobject_getobject(self, object_type_id: str | None = None, primary_key: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/get-object", None, {"object_type_id": object_type_id, "primary_key": primary_key}, None, headers=headers)

    def ontology_ontology_getobjecttype(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/get-object-type", None, {"id": id}, None, headers=headers)

    def ontology_ontology_listlinktypes(self, object_type_id: Uuid | None = None, pagination: PageRequest | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/list-link-types", None, {"object_type_id": object_type_id, "pagination": pagination}, None, headers=headers)

    def ontology_ontology_listobjecttypes(self, pagination: PageRequest | None = None, search: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/list-object-types", None, {"pagination": pagination, "search": search}, None, headers=headers)

    def ontology_ontologyobject_listobjects(self, cursor: str | None = None, filters: list[PropertyFilter] | None = None, object_type_id: str | None = None, page_size: int | None = None, sort: list[PropertySort] | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/list-objects", None, {"cursor": cursor, "filters": filters, "object_type_id": object_type_id, "page_size": page_size, "sort": sort}, None, headers=headers)

    def ontology_ontology_listproperties(self, object_type_id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/ontology/list-properties", None, {"object_type_id": object_type_id}, None, headers=headers)

    def ontology_ontology_materializebinding(self, body: models.MaterializeBindingRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/materialize-binding", None, None, body, headers=headers)

    def ontology_ontologyobject_searchobjects(self, body: models.SearchObjectsRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/search-objects", None, None, body, headers=headers)

    def ontology_ontologyobject_traverselinks(self, body: models.TraverseLinksRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/traverse-links", None, None, body, headers=headers)

    def ontology_ontology_unbinddataset(self, body: models.UnbindDatasetRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/ontology/unbind-dataset", None, None, body, headers=headers)

    def ontology_ontologyobject_updateobject(self, body: models.UpdateObjectRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/ontology/update-object", None, None, body, headers=headers)

    def ontology_ontology_updateobjecttype(self, body: models.UpdateObjectTypeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/ontology/update-object-type", None, None, body, headers=headers)

    def pipeline_pipeline_createpipeline(self, body: models.CreatePipelineRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/create-pipeline", None, None, body, headers=headers)

    def pipeline_schedule_createschedule(self, body: models.CreateScheduleRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/create-schedule", None, None, body, headers=headers)

    def pipeline_pipeline_deletepipeline(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/pipelines/delete-pipeline", None, {"id": id}, None, headers=headers)

    def pipeline_schedule_deleteschedule(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/pipelines/delete-schedule", None, {"rid": rid}, None, headers=headers)

    def pipeline_lineage_getdatasetlineage(self, dataset_id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/get-dataset-lineage", None, {"dataset_id": dataset_id}, None, headers=headers)

    def pipeline_lineage_getfulllineage(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/get-full-lineage", None, None, None, headers=headers)

    def pipeline_pipeline_getpipeline(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/get-pipeline", None, {"id": id}, None, headers=headers)

    def pipeline_scheduleruns_getrun(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/get-run", None, {"rid": rid}, None, headers=headers)

    def pipeline_schedule_getschedule(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/get-schedule", None, {"rid": rid}, None, headers=headers)

    def pipeline_pipeline_listpipelines(self, pagination: PageRequest | None = None, search: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/list-pipelines", None, {"pagination": pagination, "search": search}, None, headers=headers)

    def pipeline_scheduleruns_listruns(self, limit: int | None = None, offset: int | None = None, outcome: RunOutcome | None = None, schedule_rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/list-runs", None, {"limit": limit, "offset": offset, "outcome": outcome, "schedule_rid": schedule_rid}, None, headers=headers)

    def pipeline_schedule_listschedules(self, include_paused: bool | None = None, owner: str | None = None, pagination: PageRequest | None = None, project_rid: str | None = None, query: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/pipelines/list-schedules", None, {"include_paused": include_paused, "owner": owner, "pagination": pagination, "project_rid": project_rid, "query": query}, None, headers=headers)

    def pipeline_schedule_previewnextfires(self, body: models.PreviewNextFiresRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/preview-next-fires", None, None, body, headers=headers)

    def pipeline_lineage_recordlineage(self, body: models.RecordLineageRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/record-lineage", None, None, body, headers=headers)

    def pipeline_schedule_runschedulenow(self, body: models.RunScheduleNowRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/run-schedule-now", None, None, body, headers=headers)

    def pipeline_pipeline_triggerrun(self, body: models.TriggerRunRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/pipelines/trigger-run", None, None, body, headers=headers)

    def pipeline_pipeline_updatepipeline(self, body: models.UpdatePipelineRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/pipelines/update-pipeline", None, None, body, headers=headers)

    def pipeline_schedule_updateschedule(self, body: models.UpdateScheduleRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v1/pipelines/update-schedule", None, None, body, headers=headers)

    def query_query_deletesavedquery(self, id: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("DELETE", "/api/v1/queries/delete-saved-query", None, {"id": id}, None, headers=headers)

    def query_query_executequery(self, body: models.ExecuteQueryRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/queries/execute-query", None, None, body, headers=headers)

    def query_query_explainquery(self, body: models.ExplainQueryRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/queries/explain-query", None, None, body, headers=headers)

    def query_query_listsavedqueries(self, pagination: PageRequest | None = None, search: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/queries/list-saved-queries", None, {"pagination": pagination, "search": search}, None, headers=headers)

    def query_query_savequery(self, body: models.SaveQueryRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/queries/save-query", None, None, body, headers=headers)

    def runtime_pythonruntime_dropsession(self, body: models.DropSessionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/runtime/drop-session", None, None, body, headers=headers)

    def runtime_pythonruntime_ensuresession(self, body: models.EnsureSessionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/runtime/ensure-session", None, None, body, headers=headers)

    def runtime_pythonruntime_executeinlinefunction(self, body: models.ExecuteInlineFunctionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/runtime/execute-inline-function", None, None, body, headers=headers)

    def runtime_pythonruntime_executenotebookcell(self, body: models.ExecuteNotebookCellRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/runtime/execute-notebook-cell", None, None, body, headers=headers)

    def runtime_pythonruntime_executepipelinetransform(self, body: models.ExecutePipelineTransformRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/runtime/execute-pipeline-transform", None, None, body, headers=headers)

    def v1_marketplaceproduct_createproduct(self, body: models.CreateProductRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/create-product", None, None, body, headers=headers)

    def v1_llmcatalog_disablemodel(self, body: models.DisableModelRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/disable-model", None, None, body, headers=headers)

    def v1_llmcatalog_enablemodel(self, body: models.EnableModelRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/enable-model", None, None, body, headers=headers)

    def v1_audit_exportevents(self, body: models.ExportEventsRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/export-events", None, None, body, headers=headers)

    def v1_llmcatalog_getmodel(self, rid: Uuid | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/v1/get-model", None, {"rid": rid}, None, headers=headers)

    def v1_marketplaceproduct_getproduct(self, rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/v1/get-product", None, {"rid": rid}, None, headers=headers)

    def v1_marketplaceproduct_installproduct(self, body: models.InstallProductRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/install-product", None, None, body, headers=headers)

    def v1_llmcatalog_invoke(self, body: models.InvokeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/invoke", None, None, body, headers=headers)

    def v1_llmcatalog_invokestream(self, body: models.InvokeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/invoke-stream", None, None, body, headers=headers)

    def v1_marketplaceproduct_listinstallations(self, limit: int | None = None, offset: int | None = None, product_rid: str | None = None, target_workspace_rid: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/v1/list-installations", None, {"limit": limit, "offset": offset, "product_rid": product_rid, "target_workspace_rid": target_workspace_rid}, None, headers=headers)

    def v1_llmcatalog_listmodels(self, only_enabled: bool | None = None, provider: Provider | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/v1/list-models", None, {"only_enabled": only_enabled, "provider": provider}, None, headers=headers)

    def v1_marketplaceproduct_listproducts(self, limit: int | None = None, offset: int | None = None, status: ProductStatus | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v1/v1/list-products", None, {"limit": limit, "offset": offset, "status": status}, None, headers=headers)

    def v1_eventrouter_publish(self, body: models.PublishRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/publish", None, None, body, headers=headers)

    def v1_marketplaceproduct_publishversion(self, body: models.PublishVersionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/publish-version", None, None, body, headers=headers)

    def v1_audit_queryevents(self, body: models.QueryEventsRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/query-events", None, None, body, headers=headers)

    def v1_audit_recordevent(self, body: models.RecordEventRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/record-event", None, None, body, headers=headers)

    def v1_llmcatalog_registermodel(self, body: models.RegisterModelRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/register-model", None, None, body, headers=headers)

    def v1_eventrouter_subscribe(self, body: models.SubscribeRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/subscribe", None, None, body, headers=headers)

    def v1_marketplaceproduct_uninstall(self, body: models.UninstallRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v1/v1/uninstall", None, None, body, headers=headers)

    def admin_v2_getcontrolpanel(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/control-panel", None, None, None, headers=headers)

    def admin_v2_updatecontrolpanel(self, body: models.UpdateControlPanelRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PUT", "/api/v2/admin/control-panel", None, None, body, headers=headers)

    def admin_v2_listgroups(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/groups", None, None, None, headers=headers)

    def admin_v2_creategroup(self, body: models.CreateGroupRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v2/admin/groups", None, None, body, headers=headers)

    def admin_v2_updategroup(self, id: str, body: models.UpdateGroupRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PUT", "/api/v2/admin/groups/{id}", {"id": id}, None, body, headers=headers)

    def admin_v2_listpermissions(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/permissions", None, None, None, headers=headers)

    def admin_v2_createpermission(self, body: models.CreatePermissionRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v2/admin/permissions", None, None, body, headers=headers)

    def admin_v2_listpolicies(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/policies", None, None, None, headers=headers)

    def admin_v2_createpolicy(self, body: models.UpsertPolicyRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v2/admin/policies", None, None, body, headers=headers)

    def admin_v2_evaluatepolicy(self, body: models.EvaluatePolicyRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v2/admin/policies/evaluate", None, None, body, headers=headers)

    def admin_v2_updatepolicy(self, id: str, body: models.UpsertPolicyRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v2/admin/policies/{id}", {"id": id}, None, body, headers=headers)

    def admin_v2_listroles(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/roles", None, None, None, headers=headers)

    def admin_v2_createrole(self, body: models.CreateRoleRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("POST", "/api/v2/admin/roles", None, None, body, headers=headers)

    def admin_v2_updaterole(self, id: str, body: models.UpdateRoleRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PUT", "/api/v2/admin/roles/{id}", {"id": id}, None, body, headers=headers)

    def admin_v2_listusers(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/users", None, None, None, headers=headers)

    def admin_v2_getcurrentuser(self, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/admin/users/me", None, None, None, headers=headers)

    def admin_v2_updateuser(self, id: str, body: models.UpdateUserRequest, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("PATCH", "/api/v2/admin/users/{id}", {"id": id}, None, body, headers=headers)

    def filesystem_v2_getdatasetfilesystem(self, dataset_id: str, path: str | None = None, headers: Mapping[str, str] | None = None) -> Any:
        return self._request("GET", "/api/v2/filesystem/datasets/{dataset_id}", {"dataset_id": dataset_id}, {"path": path}, None, headers=headers)

    def call_operation(self, operation_id: str, input: Mapping[str, Any] | None = None, headers: Mapping[str, str] | None = None) -> Any:
        payload = dict(input or {})
        match operation_id:
            case "open_foundry.auth.RbacService.AssignRole":
                return self.auth_rbac_assignrole(payload.get('body', payload), headers=headers)
            case "open_foundry.auth.AuthService.GetMe":
                return self.auth_auth_getme(headers=headers)
            case "open_foundry.auth.RbacService.ListRoles":
                return self.auth_rbac_listroles(headers=headers)
            case "open_foundry.auth.AuthService.Login":
                return self.auth_auth_login(payload.get('body', payload), headers=headers)
            case "open_foundry.auth.AuthService.RefreshToken":
                return self.auth_auth_refreshtoken(payload.get('body', payload), headers=headers)
            case "open_foundry.auth.AuthService.Register":
                return self.auth_auth_register(payload.get('body', payload), headers=headers)
            case "open_foundry.common.HealthService.Check":
                return self.common_health_check(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.IngestJobService.CancelIngestJob":
                return self.data_integration_ingestjob_cancelingestjob(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.ConnectorService.CreateConnection":
                return self.data_integration_connector_createconnection(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.ConnectorService.DeleteConnection":
                return self.data_integration_connector_deleteconnection((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.data_integration.IngestJobService.GetIngestJob":
                return self.data_integration_ingestjob_getingestjob((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.data_integration.ConnectorService.InferSchema":
                return self.data_integration_connector_inferschema(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.ConnectorService.ListConnections":
                return self.data_integration_connector_listconnections((payload.get('query') or {}).get("pagination"), headers=headers)
            case "open_foundry.data_integration.IngestJobService.ListIngestJobs":
                return self.data_integration_ingestjob_listingestjobs((payload.get('query') or {}).get("connection_id"), (payload.get('query') or {}).get("pagination"), headers=headers)
            case "open_foundry.data_integration.IngestJobService.QueueIngestJob":
                return self.data_integration_ingestjob_queueingestjob(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.ConnectorService.SyncConnection":
                return self.data_integration_connector_syncconnection(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.ConnectorService.TestConnection":
                return self.data_integration_connector_testconnection(payload.get('body', payload), headers=headers)
            case "open_foundry.data_integration.IngestJobService.WatchIngestJob":
                return self.data_integration_ingestjob_watchingestjob(payload.get('body', payload), headers=headers)
            case "open_foundry.dataset.DatasetService.CreateDataset":
                return self.dataset_dataset_createdataset(payload.get('body', payload), headers=headers)
            case "open_foundry.dataset.DatasetService.DeleteDataset":
                return self.dataset_dataset_deletedataset((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.dataset.DatasetService.GetDataset":
                return self.dataset_dataset_getdataset((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.dataset.DatasetService.GetVersions":
                return self.dataset_dataset_getversions((payload.get('query') or {}).get("dataset_id"), headers=headers)
            case "open_foundry.dataset.DatasetService.ListDatasets":
                return self.dataset_dataset_listdatasets((payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("search"), (payload.get('query') or {}).get("tags"), headers=headers)
            case "open_foundry.dataset.DatasetService.PreviewData":
                return self.dataset_dataset_previewdata(payload.get('body', payload), headers=headers)
            case "open_foundry.dataset.DatasetService.UpdateDataset":
                return self.dataset_dataset_updatedataset(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.AbortTransaction":
                return self.media_set_mediaset_aborttransaction(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.CommitTransaction":
                return self.media_set_mediaset_committransaction(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.CreateMediaSet":
                return self.media_set_mediaset_createmediaset(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.DeleteMediaItem":
                return self.media_set_mediaset_deletemediaitem((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.media_set.MediaSetService.DeleteMediaSet":
                return self.media_set_mediaset_deletemediaset((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.media_set.MediaSetService.GeneratePresignedDownloadUrl":
                return self.media_set_mediaset_generatepresigneddownloadurl(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.GeneratePresignedUploadUrl":
                return self.media_set_mediaset_generatepresigneduploadurl(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.GetMediaItem":
                return self.media_set_mediaset_getmediaitem((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.media_set.MediaSetService.GetMediaSet":
                return self.media_set_mediaset_getmediaset((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.media_set.AccessPatternService.ListAccessPatterns":
                return self.media_set_accesspattern_listaccesspatterns((payload.get('query') or {}).get("media_set_rid"), (payload.get('query') or {}).get("pagination"), headers=headers)
            case "open_foundry.media_set.MediaSetService.ListMediaItems":
                return self.media_set_mediaset_listmediaitems((payload.get('query') or {}).get("branch"), (payload.get('query') or {}).get("media_set_rid"), (payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("path_prefix"), headers=headers)
            case "open_foundry.media_set.MediaSetService.ListMediaSets":
                return self.media_set_mediaset_listmediasets((payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("project_rid"), headers=headers)
            case "open_foundry.media_set.MediaSetService.OpenTransaction":
                return self.media_set_mediaset_opentransaction(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.AccessPatternService.RegisterAccessPattern":
                return self.media_set_accesspattern_registeraccesspattern(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.MediaSetService.RegisterVirtualMediaItem":
                return self.media_set_mediaset_registervirtualmediaitem(payload.get('body', payload), headers=headers)
            case "open_foundry.media_set.AccessPatternService.RunAccessPattern":
                return self.media_set_accesspattern_runaccesspattern(payload.get('body', payload), headers=headers)
            case "notebook.NotebookService.CreateNotebook":
                return self.notebook_notebook_createnotebook(payload.get('body', payload), headers=headers)
            case "notebook.KernelService.CreateSession":
                return self.notebook_kernel_createsession(payload.get('body', payload), headers=headers)
            case "notebook.NotebookService.DeleteNotebook":
                return self.notebook_notebook_deletenotebook((payload.get('query') or {}).get("id"), headers=headers)
            case "notebook.NotebookService.GetNotebook":
                return self.notebook_notebook_getnotebook((payload.get('query') or {}).get("id"), headers=headers)
            case "notebook.NotebookService.ListNotebooks":
                return self.notebook_notebook_listnotebooks((payload.get('query') or {}).get("page"), (payload.get('query') or {}).get("per_page"), (payload.get('query') or {}).get("search"), headers=headers)
            case "notebook.KernelService.ListSessions":
                return self.notebook_kernel_listsessions((payload.get('query') or {}).get("notebook_id"), headers=headers)
            case "notebook.KernelService.StopSession":
                return self.notebook_kernel_stopsession(payload.get('body', payload), headers=headers)
            case "notebook.NotebookService.UpdateNotebook":
                return self.notebook_notebook_updatenotebook(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.BindDataset":
                return self.ontology_ontology_binddataset(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.CreateLinkType":
                return self.ontology_ontology_createlinktype(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.CreateObject":
                return self.ontology_ontologyobject_createobject(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.CreateObjectType":
                return self.ontology_ontology_createobjecttype(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.CreateProperty":
                return self.ontology_ontology_createproperty(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.DeleteLinkType":
                return self.ontology_ontology_deletelinktype((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.DeleteObject":
                return self.ontology_ontologyobject_deleteobject((payload.get('query') or {}).get("object_type_id"), (payload.get('query') or {}).get("primary_key"), headers=headers)
            case "open_foundry.ontology.OntologyService.DeleteObjectType":
                return self.ontology_ontology_deleteobjecttype((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.GetObject":
                return self.ontology_ontologyobject_getobject((payload.get('query') or {}).get("object_type_id"), (payload.get('query') or {}).get("primary_key"), headers=headers)
            case "open_foundry.ontology.OntologyService.GetObjectType":
                return self.ontology_ontology_getobjecttype((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.ontology.OntologyService.ListLinkTypes":
                return self.ontology_ontology_listlinktypes((payload.get('query') or {}).get("object_type_id"), (payload.get('query') or {}).get("pagination"), headers=headers)
            case "open_foundry.ontology.OntologyService.ListObjectTypes":
                return self.ontology_ontology_listobjecttypes((payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("search"), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.ListObjects":
                return self.ontology_ontologyobject_listobjects((payload.get('query') or {}).get("cursor"), (payload.get('query') or {}).get("filters"), (payload.get('query') or {}).get("object_type_id"), (payload.get('query') or {}).get("page_size"), (payload.get('query') or {}).get("sort"), headers=headers)
            case "open_foundry.ontology.OntologyService.ListProperties":
                return self.ontology_ontology_listproperties((payload.get('query') or {}).get("object_type_id"), headers=headers)
            case "open_foundry.ontology.OntologyService.MaterializeBinding":
                return self.ontology_ontology_materializebinding(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.SearchObjects":
                return self.ontology_ontologyobject_searchobjects(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.TraverseLinks":
                return self.ontology_ontologyobject_traverselinks(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.UnbindDataset":
                return self.ontology_ontology_unbinddataset(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyObjectService.UpdateObject":
                return self.ontology_ontologyobject_updateobject(payload.get('body', payload), headers=headers)
            case "open_foundry.ontology.OntologyService.UpdateObjectType":
                return self.ontology_ontology_updateobjecttype(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.PipelineService.CreatePipeline":
                return self.pipeline_pipeline_createpipeline(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.ScheduleService.CreateSchedule":
                return self.pipeline_schedule_createschedule(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.PipelineService.DeletePipeline":
                return self.pipeline_pipeline_deletepipeline((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.pipeline.ScheduleService.DeleteSchedule":
                return self.pipeline_schedule_deleteschedule((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.pipeline.LineageService.GetDatasetLineage":
                return self.pipeline_lineage_getdatasetlineage((payload.get('query') or {}).get("dataset_id"), headers=headers)
            case "open_foundry.pipeline.LineageService.GetFullLineage":
                return self.pipeline_lineage_getfulllineage(headers=headers)
            case "open_foundry.pipeline.PipelineService.GetPipeline":
                return self.pipeline_pipeline_getpipeline((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.pipeline.ScheduleRunsService.GetRun":
                return self.pipeline_scheduleruns_getrun((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.pipeline.ScheduleService.GetSchedule":
                return self.pipeline_schedule_getschedule((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.pipeline.PipelineService.ListPipelines":
                return self.pipeline_pipeline_listpipelines((payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("search"), headers=headers)
            case "open_foundry.pipeline.ScheduleRunsService.ListRuns":
                return self.pipeline_scheduleruns_listruns((payload.get('query') or {}).get("limit"), (payload.get('query') or {}).get("offset"), (payload.get('query') or {}).get("outcome"), (payload.get('query') or {}).get("schedule_rid"), headers=headers)
            case "open_foundry.pipeline.ScheduleService.ListSchedules":
                return self.pipeline_schedule_listschedules((payload.get('query') or {}).get("include_paused"), (payload.get('query') or {}).get("owner"), (payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("project_rid"), (payload.get('query') or {}).get("query"), headers=headers)
            case "open_foundry.pipeline.ScheduleService.PreviewNextFires":
                return self.pipeline_schedule_previewnextfires(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.LineageService.RecordLineage":
                return self.pipeline_lineage_recordlineage(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.ScheduleService.RunScheduleNow":
                return self.pipeline_schedule_runschedulenow(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.PipelineService.TriggerRun":
                return self.pipeline_pipeline_triggerrun(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.PipelineService.UpdatePipeline":
                return self.pipeline_pipeline_updatepipeline(payload.get('body', payload), headers=headers)
            case "open_foundry.pipeline.ScheduleService.UpdateSchedule":
                return self.pipeline_schedule_updateschedule(payload.get('body', payload), headers=headers)
            case "open_foundry.query.QueryService.DeleteSavedQuery":
                return self.query_query_deletesavedquery((payload.get('query') or {}).get("id"), headers=headers)
            case "open_foundry.query.QueryService.ExecuteQuery":
                return self.query_query_executequery(payload.get('body', payload), headers=headers)
            case "open_foundry.query.QueryService.ExplainQuery":
                return self.query_query_explainquery(payload.get('body', payload), headers=headers)
            case "open_foundry.query.QueryService.ListSavedQueries":
                return self.query_query_listsavedqueries((payload.get('query') or {}).get("pagination"), (payload.get('query') or {}).get("search"), headers=headers)
            case "open_foundry.query.QueryService.SaveQuery":
                return self.query_query_savequery(payload.get('body', payload), headers=headers)
            case "runtime.PythonRuntimeService.DropSession":
                return self.runtime_pythonruntime_dropsession(payload.get('body', payload), headers=headers)
            case "runtime.PythonRuntimeService.EnsureSession":
                return self.runtime_pythonruntime_ensuresession(payload.get('body', payload), headers=headers)
            case "runtime.PythonRuntimeService.ExecuteInlineFunction":
                return self.runtime_pythonruntime_executeinlinefunction(payload.get('body', payload), headers=headers)
            case "runtime.PythonRuntimeService.ExecuteNotebookCell":
                return self.runtime_pythonruntime_executenotebookcell(payload.get('body', payload), headers=headers)
            case "runtime.PythonRuntimeService.ExecutePipelineTransform":
                return self.runtime_pythonruntime_executepipelinetransform(payload.get('body', payload), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.CreateProduct":
                return self.v1_marketplaceproduct_createproduct(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.DisableModel":
                return self.v1_llmcatalog_disablemodel(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.EnableModel":
                return self.v1_llmcatalog_enablemodel(payload.get('body', payload), headers=headers)
            case "open_foundry.audit.v1.AuditService.ExportEvents":
                return self.v1_audit_exportevents(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.GetModel":
                return self.v1_llmcatalog_getmodel((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.GetProduct":
                return self.v1_marketplaceproduct_getproduct((payload.get('query') or {}).get("rid"), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.InstallProduct":
                return self.v1_marketplaceproduct_installproduct(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.Invoke":
                return self.v1_llmcatalog_invoke(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.InvokeStream":
                return self.v1_llmcatalog_invokestream(payload.get('body', payload), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.ListInstallations":
                return self.v1_marketplaceproduct_listinstallations((payload.get('query') or {}).get("limit"), (payload.get('query') or {}).get("offset"), (payload.get('query') or {}).get("product_rid"), (payload.get('query') or {}).get("target_workspace_rid"), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.ListModels":
                return self.v1_llmcatalog_listmodels((payload.get('query') or {}).get("only_enabled"), (payload.get('query') or {}).get("provider"), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.ListProducts":
                return self.v1_marketplaceproduct_listproducts((payload.get('query') or {}).get("limit"), (payload.get('query') or {}).get("offset"), (payload.get('query') or {}).get("status"), headers=headers)
            case "openfoundry.streaming.router.v1.EventRouter.Publish":
                return self.v1_eventrouter_publish(payload.get('body', payload), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.PublishVersion":
                return self.v1_marketplaceproduct_publishversion(payload.get('body', payload), headers=headers)
            case "open_foundry.audit.v1.AuditService.QueryEvents":
                return self.v1_audit_queryevents(payload.get('body', payload), headers=headers)
            case "open_foundry.audit.v1.AuditService.RecordEvent":
                return self.v1_audit_recordevent(payload.get('body', payload), headers=headers)
            case "open_foundry.ai.v1.LlmCatalogService.RegisterModel":
                return self.v1_llmcatalog_registermodel(payload.get('body', payload), headers=headers)
            case "openfoundry.streaming.router.v1.EventRouter.Subscribe":
                return self.v1_eventrouter_subscribe(payload.get('body', payload), headers=headers)
            case "open_foundry.marketplace.v1.MarketplaceProductService.Uninstall":
                return self.v1_marketplaceproduct_uninstall(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.getControlPanel":
                return self.admin_v2_getcontrolpanel(headers=headers)
            case "rest.admin.v2.updateControlPanel":
                return self.admin_v2_updatecontrolpanel(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.listGroups":
                return self.admin_v2_listgroups(headers=headers)
            case "rest.admin.v2.createGroup":
                return self.admin_v2_creategroup(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.updateGroup":
                return self.admin_v2_updategroup((payload.get('path') or {}).get("id"), payload.get('body'), headers=headers)
            case "rest.admin.v2.listPermissions":
                return self.admin_v2_listpermissions(headers=headers)
            case "rest.admin.v2.createPermission":
                return self.admin_v2_createpermission(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.listPolicies":
                return self.admin_v2_listpolicies(headers=headers)
            case "rest.admin.v2.createPolicy":
                return self.admin_v2_createpolicy(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.evaluatePolicy":
                return self.admin_v2_evaluatepolicy(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.updatePolicy":
                return self.admin_v2_updatepolicy((payload.get('path') or {}).get("id"), payload.get('body'), headers=headers)
            case "rest.admin.v2.listRoles":
                return self.admin_v2_listroles(headers=headers)
            case "rest.admin.v2.createRole":
                return self.admin_v2_createrole(payload.get('body', payload), headers=headers)
            case "rest.admin.v2.updateRole":
                return self.admin_v2_updaterole((payload.get('path') or {}).get("id"), payload.get('body'), headers=headers)
            case "rest.admin.v2.listUsers":
                return self.admin_v2_listusers(headers=headers)
            case "rest.admin.v2.getCurrentUser":
                return self.admin_v2_getcurrentuser(headers=headers)
            case "rest.admin.v2.updateUser":
                return self.admin_v2_updateuser((payload.get('path') or {}).get("id"), payload.get('body'), headers=headers)
            case "rest.filesystem.v2.getDatasetFilesystem":
                return self.filesystem_v2_getdatasetfilesystem((payload.get('path') or {}).get("dataset_id"), (payload.get('query') or {}).get("path"), headers=headers)
            case _:
                raise ValueError(f"Unknown OpenFoundry operation: {operation_id}")

    def _request(self, method: str, path_template: str, path_params: Mapping[str, Any] | None = None, query: Mapping[str, Any] | None = None, body: Any = None, headers: Mapping[str, str] | None = None) -> Any:
        path = self._interpolate_path(path_template, path_params)
        url = self._build_url(path, query)
        request_headers = dict(self.default_headers)
        if headers:
            request_headers.update(dict(headers))
        if self.token and "authorization" not in {key.lower() for key in request_headers}:
            request_headers["authorization"] = f"Bearer {self.token}"
        if self.user_agent and "x-openfoundry-client" not in {key.lower() for key in request_headers}:
            request_headers["x-openfoundry-client"] = self.user_agent
        payload = None
        if body is not None:
            request_headers.setdefault("content-type", "application/json")
            payload = json.dumps(models.serialize_model(body)).encode("utf-8")
        attempt = 0
        while attempt < self.max_retries:
            attempt += 1
            request = urllib.request.Request(url=url, data=payload, method=method, headers=request_headers)
            try:
                with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                    raw = response.read()
                    return self._parse_payload(raw) if response.status != 204 else None
            except urllib.error.HTTPError as error:
                if attempt >= self.max_retries or error.code not in {408, 429, 500, 502, 503, 504}:
                    raise OpenFoundryApiError(error.read().decode("utf-8", errors="replace")) from error
                time.sleep(self.retry_backoff_seconds * attempt)
            except urllib.error.URLError as error:
                if attempt >= self.max_retries:
                    raise OpenFoundryApiError(str(error)) from error
                time.sleep(self.retry_backoff_seconds * attempt)
        raise OpenFoundryApiError("OpenFoundry request exhausted retries")

    def _build_url(self, path: str, query: Mapping[str, Any] | None) -> str:
        if not query:
            return f"{self.base_url}{path}"
        pairs: list[tuple[str, str]] = []
        for key, value in query.items():
            if value is None:
                continue
            if isinstance(value, (list, tuple)):
                pairs.extend((key, str(item)) for item in value)
            elif isinstance(value, dict):
                pairs.append((key, json.dumps(models.serialize_model(value))))
            else:
                pairs.append((key, str(value)))
        return f"{self.base_url}{path}?{urllib.parse.urlencode(pairs)}" if pairs else f"{self.base_url}{path}"

    def _interpolate_path(self, path_template: str, path_params: Mapping[str, Any] | None) -> str:
        path = path_template
        for key, value in (path_params or {}).items():
            path = path.replace('{' + key + '}', urllib.parse.quote(str(value), safe=''))
        return path

    def _parse_payload(self, raw: bytes) -> Any:
        if not raw:
            return None
        text = raw.decode("utf-8", errors="replace")
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return text