# This file is generated by `go run ./tools/of-cli docs generate-sdk-python`.
# Do not edit manually.
from __future__ import annotations

from typing import Any, Mapping

from .client import OpenFoundryClient

MCP_TOOL_REGISTRY: list[dict[str, Any]] = [
    {
        "name": "openfoundry.auth.assignrole",
        "operation_id": "open_foundry.auth.RbacService.AssignRole",
    },
    {
        "name": "openfoundry.auth.getme",
        "operation_id": "open_foundry.auth.AuthService.GetMe",
    },
    {
        "name": "openfoundry.auth.listroles",
        "operation_id": "open_foundry.auth.RbacService.ListRoles",
    },
    {
        "name": "openfoundry.auth.login",
        "operation_id": "open_foundry.auth.AuthService.Login",
    },
    {
        "name": "openfoundry.auth.refreshtoken",
        "operation_id": "open_foundry.auth.AuthService.RefreshToken",
    },
    {
        "name": "openfoundry.auth.register",
        "operation_id": "open_foundry.auth.AuthService.Register",
    },
    {
        "name": "openfoundry.common.check",
        "operation_id": "open_foundry.common.HealthService.Check",
    },
    {
        "name": "openfoundry.dataIntegration.cancelingestjob",
        "operation_id": "open_foundry.data_integration.IngestJobService.CancelIngestJob",
    },
    {
        "name": "openfoundry.dataIntegration.createconnection",
        "operation_id": "open_foundry.data_integration.ConnectorService.CreateConnection",
    },
    {
        "name": "openfoundry.dataIntegration.deleteconnection",
        "operation_id": "open_foundry.data_integration.ConnectorService.DeleteConnection",
    },
    {
        "name": "openfoundry.dataIntegration.getingestjob",
        "operation_id": "open_foundry.data_integration.IngestJobService.GetIngestJob",
    },
    {
        "name": "openfoundry.dataIntegration.inferschema",
        "operation_id": "open_foundry.data_integration.ConnectorService.InferSchema",
    },
    {
        "name": "openfoundry.dataIntegration.listconnections",
        "operation_id": "open_foundry.data_integration.ConnectorService.ListConnections",
    },
    {
        "name": "openfoundry.dataIntegration.listingestjobs",
        "operation_id": "open_foundry.data_integration.IngestJobService.ListIngestJobs",
    },
    {
        "name": "openfoundry.dataIntegration.queueingestjob",
        "operation_id": "open_foundry.data_integration.IngestJobService.QueueIngestJob",
    },
    {
        "name": "openfoundry.dataIntegration.syncconnection",
        "operation_id": "open_foundry.data_integration.ConnectorService.SyncConnection",
    },
    {
        "name": "openfoundry.dataIntegration.testconnection",
        "operation_id": "open_foundry.data_integration.ConnectorService.TestConnection",
    },
    {
        "name": "openfoundry.dataIntegration.watchingestjob",
        "operation_id": "open_foundry.data_integration.IngestJobService.WatchIngestJob",
    },
    {
        "name": "openfoundry.dataset.createdataset",
        "operation_id": "open_foundry.dataset.DatasetService.CreateDataset",
    },
    {
        "name": "openfoundry.dataset.deletedataset",
        "operation_id": "open_foundry.dataset.DatasetService.DeleteDataset",
    },
    {
        "name": "openfoundry.dataset.getdataset",
        "operation_id": "open_foundry.dataset.DatasetService.GetDataset",
    },
    {
        "name": "openfoundry.dataset.getversions",
        "operation_id": "open_foundry.dataset.DatasetService.GetVersions",
    },
    {
        "name": "openfoundry.dataset.listdatasets",
        "operation_id": "open_foundry.dataset.DatasetService.ListDatasets",
    },
    {
        "name": "openfoundry.dataset.previewdata",
        "operation_id": "open_foundry.dataset.DatasetService.PreviewData",
    },
    {
        "name": "openfoundry.dataset.updatedataset",
        "operation_id": "open_foundry.dataset.DatasetService.UpdateDataset",
    },
    {
        "name": "openfoundry.mediaSet.aborttransaction",
        "operation_id": "open_foundry.media_set.MediaSetService.AbortTransaction",
    },
    {
        "name": "openfoundry.mediaSet.committransaction",
        "operation_id": "open_foundry.media_set.MediaSetService.CommitTransaction",
    },
    {
        "name": "openfoundry.mediaSet.createmediaset",
        "operation_id": "open_foundry.media_set.MediaSetService.CreateMediaSet",
    },
    {
        "name": "openfoundry.mediaSet.deletemediaitem",
        "operation_id": "open_foundry.media_set.MediaSetService.DeleteMediaItem",
    },
    {
        "name": "openfoundry.mediaSet.deletemediaset",
        "operation_id": "open_foundry.media_set.MediaSetService.DeleteMediaSet",
    },
    {
        "name": "openfoundry.mediaSet.generatepresigneddownloadurl",
        "operation_id": "open_foundry.media_set.MediaSetService.GeneratePresignedDownloadUrl",
    },
    {
        "name": "openfoundry.mediaSet.generatepresigneduploadurl",
        "operation_id": "open_foundry.media_set.MediaSetService.GeneratePresignedUploadUrl",
    },
    {
        "name": "openfoundry.mediaSet.getmediaitem",
        "operation_id": "open_foundry.media_set.MediaSetService.GetMediaItem",
    },
    {
        "name": "openfoundry.mediaSet.getmediaset",
        "operation_id": "open_foundry.media_set.MediaSetService.GetMediaSet",
    },
    {
        "name": "openfoundry.mediaSet.listaccesspatterns",
        "operation_id": "open_foundry.media_set.AccessPatternService.ListAccessPatterns",
    },
    {
        "name": "openfoundry.mediaSet.listmediaitems",
        "operation_id": "open_foundry.media_set.MediaSetService.ListMediaItems",
    },
    {
        "name": "openfoundry.mediaSet.listmediasets",
        "operation_id": "open_foundry.media_set.MediaSetService.ListMediaSets",
    },
    {
        "name": "openfoundry.mediaSet.opentransaction",
        "operation_id": "open_foundry.media_set.MediaSetService.OpenTransaction",
    },
    {
        "name": "openfoundry.mediaSet.registeraccesspattern",
        "operation_id": "open_foundry.media_set.AccessPatternService.RegisterAccessPattern",
    },
    {
        "name": "openfoundry.mediaSet.registervirtualmediaitem",
        "operation_id": "open_foundry.media_set.MediaSetService.RegisterVirtualMediaItem",
    },
    {
        "name": "openfoundry.mediaSet.runaccesspattern",
        "operation_id": "open_foundry.media_set.AccessPatternService.RunAccessPattern",
    },
    {
        "name": "openfoundry.notebook.createnotebook",
        "operation_id": "notebook.NotebookService.CreateNotebook",
    },
    {
        "name": "openfoundry.notebook.createsession",
        "operation_id": "notebook.KernelService.CreateSession",
    },
    {
        "name": "openfoundry.notebook.deletenotebook",
        "operation_id": "notebook.NotebookService.DeleteNotebook",
    },
    {
        "name": "openfoundry.notebook.getnotebook",
        "operation_id": "notebook.NotebookService.GetNotebook",
    },
    {
        "name": "openfoundry.notebook.listnotebooks",
        "operation_id": "notebook.NotebookService.ListNotebooks",
    },
    {
        "name": "openfoundry.notebook.listsessions",
        "operation_id": "notebook.KernelService.ListSessions",
    },
    {
        "name": "openfoundry.notebook.stopsession",
        "operation_id": "notebook.KernelService.StopSession",
    },
    {
        "name": "openfoundry.notebook.updatenotebook",
        "operation_id": "notebook.NotebookService.UpdateNotebook",
    },
    {
        "name": "openfoundry.ontology.binddataset",
        "operation_id": "open_foundry.ontology.OntologyService.BindDataset",
    },
    {
        "name": "openfoundry.ontology.createlinktype",
        "operation_id": "open_foundry.ontology.OntologyService.CreateLinkType",
    },
    {
        "name": "openfoundry.ontology.createobject",
        "operation_id": "open_foundry.ontology.OntologyObjectService.CreateObject",
    },
    {
        "name": "openfoundry.ontology.createobjecttype",
        "operation_id": "open_foundry.ontology.OntologyService.CreateObjectType",
    },
    {
        "name": "openfoundry.ontology.createproperty",
        "operation_id": "open_foundry.ontology.OntologyService.CreateProperty",
    },
    {
        "name": "openfoundry.ontology.deletelinktype",
        "operation_id": "open_foundry.ontology.OntologyService.DeleteLinkType",
    },
    {
        "name": "openfoundry.ontology.deleteobject",
        "operation_id": "open_foundry.ontology.OntologyObjectService.DeleteObject",
    },
    {
        "name": "openfoundry.ontology.deleteobjecttype",
        "operation_id": "open_foundry.ontology.OntologyService.DeleteObjectType",
    },
    {
        "name": "openfoundry.ontology.getobject",
        "operation_id": "open_foundry.ontology.OntologyObjectService.GetObject",
    },
    {
        "name": "openfoundry.ontology.getobjecttype",
        "operation_id": "open_foundry.ontology.OntologyService.GetObjectType",
    },
    {
        "name": "openfoundry.ontology.listlinktypes",
        "operation_id": "open_foundry.ontology.OntologyService.ListLinkTypes",
    },
    {
        "name": "openfoundry.ontology.listobjecttypes",
        "operation_id": "open_foundry.ontology.OntologyService.ListObjectTypes",
    },
    {
        "name": "openfoundry.ontology.listobjects",
        "operation_id": "open_foundry.ontology.OntologyObjectService.ListObjects",
    },
    {
        "name": "openfoundry.ontology.listproperties",
        "operation_id": "open_foundry.ontology.OntologyService.ListProperties",
    },
    {
        "name": "openfoundry.ontology.materializebinding",
        "operation_id": "open_foundry.ontology.OntologyService.MaterializeBinding",
    },
    {
        "name": "openfoundry.ontology.searchobjects",
        "operation_id": "open_foundry.ontology.OntologyObjectService.SearchObjects",
    },
    {
        "name": "openfoundry.ontology.traverselinks",
        "operation_id": "open_foundry.ontology.OntologyObjectService.TraverseLinks",
    },
    {
        "name": "openfoundry.ontology.unbinddataset",
        "operation_id": "open_foundry.ontology.OntologyService.UnbindDataset",
    },
    {
        "name": "openfoundry.ontology.updateobject",
        "operation_id": "open_foundry.ontology.OntologyObjectService.UpdateObject",
    },
    {
        "name": "openfoundry.ontology.updateobjecttype",
        "operation_id": "open_foundry.ontology.OntologyService.UpdateObjectType",
    },
    {
        "name": "openfoundry.pipeline.createpipeline",
        "operation_id": "open_foundry.pipeline.PipelineService.CreatePipeline",
    },
    {
        "name": "openfoundry.pipeline.createschedule",
        "operation_id": "open_foundry.pipeline.ScheduleService.CreateSchedule",
    },
    {
        "name": "openfoundry.pipeline.deletepipeline",
        "operation_id": "open_foundry.pipeline.PipelineService.DeletePipeline",
    },
    {
        "name": "openfoundry.pipeline.deleteschedule",
        "operation_id": "open_foundry.pipeline.ScheduleService.DeleteSchedule",
    },
    {
        "name": "openfoundry.pipeline.getdatasetlineage",
        "operation_id": "open_foundry.pipeline.LineageService.GetDatasetLineage",
    },
    {
        "name": "openfoundry.pipeline.getfulllineage",
        "operation_id": "open_foundry.pipeline.LineageService.GetFullLineage",
    },
    {
        "name": "openfoundry.pipeline.getpipeline",
        "operation_id": "open_foundry.pipeline.PipelineService.GetPipeline",
    },
    {
        "name": "openfoundry.pipeline.getrun",
        "operation_id": "open_foundry.pipeline.ScheduleRunsService.GetRun",
    },
    {
        "name": "openfoundry.pipeline.getschedule",
        "operation_id": "open_foundry.pipeline.ScheduleService.GetSchedule",
    },
    {
        "name": "openfoundry.pipeline.listpipelines",
        "operation_id": "open_foundry.pipeline.PipelineService.ListPipelines",
    },
    {
        "name": "openfoundry.pipeline.listruns",
        "operation_id": "open_foundry.pipeline.ScheduleRunsService.ListRuns",
    },
    {
        "name": "openfoundry.pipeline.listschedules",
        "operation_id": "open_foundry.pipeline.ScheduleService.ListSchedules",
    },
    {
        "name": "openfoundry.pipeline.previewnextfires",
        "operation_id": "open_foundry.pipeline.ScheduleService.PreviewNextFires",
    },
    {
        "name": "openfoundry.pipeline.recordlineage",
        "operation_id": "open_foundry.pipeline.LineageService.RecordLineage",
    },
    {
        "name": "openfoundry.pipeline.runschedulenow",
        "operation_id": "open_foundry.pipeline.ScheduleService.RunScheduleNow",
    },
    {
        "name": "openfoundry.pipeline.triggerrun",
        "operation_id": "open_foundry.pipeline.PipelineService.TriggerRun",
    },
    {
        "name": "openfoundry.pipeline.updatepipeline",
        "operation_id": "open_foundry.pipeline.PipelineService.UpdatePipeline",
    },
    {
        "name": "openfoundry.pipeline.updateschedule",
        "operation_id": "open_foundry.pipeline.ScheduleService.UpdateSchedule",
    },
    {
        "name": "openfoundry.query.deletesavedquery",
        "operation_id": "open_foundry.query.QueryService.DeleteSavedQuery",
    },
    {
        "name": "openfoundry.query.executequery",
        "operation_id": "open_foundry.query.QueryService.ExecuteQuery",
    },
    {
        "name": "openfoundry.query.explainquery",
        "operation_id": "open_foundry.query.QueryService.ExplainQuery",
    },
    {
        "name": "openfoundry.query.listsavedqueries",
        "operation_id": "open_foundry.query.QueryService.ListSavedQueries",
    },
    {
        "name": "openfoundry.query.savequery",
        "operation_id": "open_foundry.query.QueryService.SaveQuery",
    },
    {
        "name": "openfoundry.runtime.dropsession",
        "operation_id": "runtime.PythonRuntimeService.DropSession",
    },
    {
        "name": "openfoundry.runtime.ensuresession",
        "operation_id": "runtime.PythonRuntimeService.EnsureSession",
    },
    {
        "name": "openfoundry.runtime.executeinlinefunction",
        "operation_id": "runtime.PythonRuntimeService.ExecuteInlineFunction",
    },
    {
        "name": "openfoundry.runtime.executenotebookcell",
        "operation_id": "runtime.PythonRuntimeService.ExecuteNotebookCell",
    },
    {
        "name": "openfoundry.runtime.executepipelinetransform",
        "operation_id": "runtime.PythonRuntimeService.ExecutePipelineTransform",
    },
    {
        "name": "openfoundry.marketplaceV1.createproduct",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.CreateProduct",
    },
    {
        "name": "openfoundry.aiV1.disablemodel",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.DisableModel",
    },
    {
        "name": "openfoundry.aiV1.enablemodel",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.EnableModel",
    },
    {
        "name": "openfoundry.auditV1.exportevents",
        "operation_id": "open_foundry.audit.v1.AuditService.ExportEvents",
    },
    {
        "name": "openfoundry.aiV1.getmodel",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.GetModel",
    },
    {
        "name": "openfoundry.marketplaceV1.getproduct",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.GetProduct",
    },
    {
        "name": "openfoundry.marketplaceV1.installproduct",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.InstallProduct",
    },
    {
        "name": "openfoundry.aiV1.invoke",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.Invoke",
    },
    {
        "name": "openfoundry.aiV1.invokestream",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.InvokeStream",
    },
    {
        "name": "openfoundry.marketplaceV1.listinstallations",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.ListInstallations",
    },
    {
        "name": "openfoundry.aiV1.listmodels",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.ListModels",
    },
    {
        "name": "openfoundry.marketplaceV1.listproducts",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.ListProducts",
    },
    {
        "name": "openfoundry.openfoundryStreamingRouterV1.publish",
        "operation_id": "openfoundry.streaming.router.v1.EventRouter.Publish",
    },
    {
        "name": "openfoundry.marketplaceV1.publishversion",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.PublishVersion",
    },
    {
        "name": "openfoundry.auditV1.queryevents",
        "operation_id": "open_foundry.audit.v1.AuditService.QueryEvents",
    },
    {
        "name": "openfoundry.auditV1.recordevent",
        "operation_id": "open_foundry.audit.v1.AuditService.RecordEvent",
    },
    {
        "name": "openfoundry.aiV1.registermodel",
        "operation_id": "open_foundry.ai.v1.LlmCatalogService.RegisterModel",
    },
    {
        "name": "openfoundry.openfoundryStreamingRouterV1.subscribe",
        "operation_id": "openfoundry.streaming.router.v1.EventRouter.Subscribe",
    },
    {
        "name": "openfoundry.marketplaceV1.uninstall",
        "operation_id": "open_foundry.marketplace.v1.MarketplaceProductService.Uninstall",
    },
    {
        "name": "openfoundry.adminV2.getcontrolpanel",
        "operation_id": "rest.admin.v2.getControlPanel",
    },
    {
        "name": "openfoundry.adminV2.updatecontrolpanel",
        "operation_id": "rest.admin.v2.updateControlPanel",
    },
    {
        "name": "openfoundry.adminV2.listgroups",
        "operation_id": "rest.admin.v2.listGroups",
    },
    {
        "name": "openfoundry.adminV2.creategroup",
        "operation_id": "rest.admin.v2.createGroup",
    },
    {
        "name": "openfoundry.adminV2.updategroup",
        "operation_id": "rest.admin.v2.updateGroup",
    },
    {
        "name": "openfoundry.adminV2.listpermissions",
        "operation_id": "rest.admin.v2.listPermissions",
    },
    {
        "name": "openfoundry.adminV2.createpermission",
        "operation_id": "rest.admin.v2.createPermission",
    },
    {
        "name": "openfoundry.adminV2.listpolicies",
        "operation_id": "rest.admin.v2.listPolicies",
    },
    {
        "name": "openfoundry.adminV2.createpolicy",
        "operation_id": "rest.admin.v2.createPolicy",
    },
    {
        "name": "openfoundry.adminV2.evaluatepolicy",
        "operation_id": "rest.admin.v2.evaluatePolicy",
    },
    {
        "name": "openfoundry.adminV2.updatepolicy",
        "operation_id": "rest.admin.v2.updatePolicy",
    },
    {
        "name": "openfoundry.adminV2.listroles",
        "operation_id": "rest.admin.v2.listRoles",
    },
    {
        "name": "openfoundry.adminV2.createrole",
        "operation_id": "rest.admin.v2.createRole",
    },
    {
        "name": "openfoundry.adminV2.updaterole",
        "operation_id": "rest.admin.v2.updateRole",
    },
    {
        "name": "openfoundry.adminV2.listusers",
        "operation_id": "rest.admin.v2.listUsers",
    },
    {
        "name": "openfoundry.adminV2.getcurrentuser",
        "operation_id": "rest.admin.v2.getCurrentUser",
    },
    {
        "name": "openfoundry.adminV2.updateuser",
        "operation_id": "rest.admin.v2.updateUser",
    },
    {
        "name": "openfoundry.filesystemV2.getdatasetfilesystem",
        "operation_id": "rest.filesystem.v2.getDatasetFilesystem",
    },
]
_MCP_TOOL_LOOKUP = {tool["name"]: tool for tool in MCP_TOOL_REGISTRY}

def list_openfoundry_mcp_tools() -> list[dict[str, Any]]:
    return MCP_TOOL_REGISTRY

def call_openfoundry_mcp_tool(client: OpenFoundryClient, tool_name: str, input: Mapping[str, Any] | None = None, headers: Mapping[str, str] | None = None) -> Any:
    tool = _MCP_TOOL_LOOKUP.get(tool_name)
    if tool is None:
        raise ValueError(f"Unknown OpenFoundry MCP tool: {tool_name}")
    return client.call_operation(tool["operation_id"], input=input or {}, headers=headers)