// @generated
// This file is @generated by prost-build.
/// Operator-facing stream configuration.
///
/// All knobs map onto runtime behaviour:
///    * `type`/`compression`           → Kafka producer config + the
///                                        hot-buffer backend.
///    * `partitions`                   → Kafka topic partition count
///                                        (1..=50 per docs throughput
///                                        slider, ~5 MB/s per partition).
///    * `retention_ms`                 → hot-buffer retention.
///    * `ingest_consistency`           → forced AT_LEAST_ONCE per docs;
///                                        validator rejects EXACTLY_ONCE.
///    * `pipeline_consistency`         → consumed by Flink runtime as
///                                        `execution.checkpointing.mode`.
///    * `checkpoint_interval_ms`       → matching
///                                        `execution.checkpointing.interval`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamConfig {
    #[prost(enumeration="StreamType", tag="1")]
    pub r#type: i32,
    #[prost(bool, tag="2")]
    pub compression: bool,
    /// 1..=50
    #[prost(uint32, tag="3")]
    pub partitions: u32,
    #[prost(uint32, tag="4")]
    pub retention_ms: u32,
    #[prost(enumeration="StreamConsistency", tag="5")]
    pub ingest_consistency: i32,
    #[prost(enumeration="StreamConsistency", tag="6")]
    pub pipeline_consistency: i32,
    #[prost(uint32, tag="7")]
    pub checkpoint_interval_ms: u32,
}
/// Streaming consistency contract surfaced by Foundry's docs.
///
/// Streaming sources only support AT_LEAST_ONCE for extracts/exports;
/// streaming pipelines support both. The validator enforces that the
/// `ingest_consistency` field of `StreamConfig` is never EXACTLY_ONCE.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamConsistency {
    ConsistencyUnspecified = 0,
    AtLeastOnce = 1,
    ExactlyOnce = 2,
}
impl StreamConsistency {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ConsistencyUnspecified => "CONSISTENCY_UNSPECIFIED",
            Self::AtLeastOnce => "AT_LEAST_ONCE",
            Self::ExactlyOnce => "EXACTLY_ONCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONSISTENCY_UNSPECIFIED" => Some(Self::ConsistencyUnspecified),
            "AT_LEAST_ONCE" => Some(Self::AtLeastOnce),
            "EXACTLY_ONCE" => Some(Self::ExactlyOnce),
            _ => None,
        }
    }
}
/// Stream type tunes the underlying Kafka producer for throughput vs.
/// latency, with an orthogonal compression dimension. Defaults to STANDARD.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamType {
    Unspecified = 0,
    /// Foundry default: low-latency producer settings.
    Standard = 1,
    /// Higher `linger.ms` and `batch.size` so the producer batches
    /// aggressively. Trades latency for throughput.
    HighThroughput = 2,
    /// Compresses produced batches (lz4) at the cost of some CPU.
    Compressed = 3,
    /// High-throughput plus compression — combinable variant explicitly
    /// recognised so consumers can render a single radio choice.
    HighThroughputCompressed = 4,
}
impl StreamType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STREAM_TYPE_UNSPECIFIED",
            Self::Standard => "STANDARD",
            Self::HighThroughput => "HIGH_THROUGHPUT",
            Self::Compressed => "COMPRESSED",
            Self::HighThroughputCompressed => "HIGH_THROUGHPUT_COMPRESSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "STANDARD" => Some(Self::Standard),
            "HIGH_THROUGHPUT" => Some(Self::HighThroughput),
            "COMPRESSED" => Some(Self::Compressed),
            "HIGH_THROUGHPUT_COMPRESSED" => Some(Self::HighThroughputCompressed),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
