// @generated
// This file is @generated by prost-build.
/// ObjectInstance is one row of an ObjectType. `properties` is a
/// JSON-shaped Struct so the wire format can carry arbitrary scalar /
/// nested values (mirrors the SPA's `Record<string, unknown>` shape).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectInstance {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub properties: ::core::option::Option<super::super::google::protobuf::Struct>,
    #[prost(string, tag="4")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub marking: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
/// PropertyFilter is the wire form of a single ILIKE / equals / range
/// predicate over JSONB property values. Mirrors the SPA's
/// `ObjectQueryFilter` interface.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PropertyFilter {
    #[prost(string, tag="1")]
    pub property_name: ::prost::alloc::string::String,
    /// One of: equals, not_equals, contains, gte, lte, gt, lt, in,
    /// is_empty, is_not_empty. Defaults to equals when empty.
    #[prost(string, tag="2")]
    pub operator: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub value: ::core::option::Option<super::super::google::protobuf::Value>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PropertySort {
    #[prost(string, tag="1")]
    pub property_name: ::prost::alloc::string::String,
    /// asc | desc
    #[prost(string, tag="2")]
    pub direction: ::prost::alloc::string::String,
}
// --- GetObject -----------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    /// Primary-key value of the target object. The type's PK property is
    /// resolved from ontology-definition-service when needed.
    #[prost(string, tag="2")]
    pub primary_key: ::prost::alloc::string::String,
}
// --- ListObjects ---------------------------------------------------

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObjectsRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub filters: ::prost::alloc::vec::Vec<PropertyFilter>,
    #[prost(message, repeated, tag="3")]
    pub sort: ::prost::alloc::vec::Vec<PropertySort>,
    /// Opaque cursor returned by the previous page. Empty for the first
    /// page.
    #[prost(string, tag="4")]
    pub cursor: ::prost::alloc::string::String,
    /// Page size, clamped server-side to \[1, 5000\]. 0 → server default.
    #[prost(int32, tag="5")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObjectsResponse {
    #[prost(message, repeated, tag="1")]
    pub objects: ::prost::alloc::vec::Vec<ObjectInstance>,
    #[prost(string, tag="2")]
    pub next_cursor: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub total: i64,
}
// --- CreateObject --------------------------------------------------

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateObjectRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub properties: ::core::option::Option<super::super::google::protobuf::Struct>,
    #[prost(string, tag="3")]
    pub marking: ::prost::alloc::string::String,
}
// --- UpdateObject --------------------------------------------------

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateObjectRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub primary_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub properties: ::core::option::Option<super::super::google::protobuf::Struct>,
    /// When true, `properties` replaces the existing payload wholesale.
    /// When false, it is merged key-wise on top of the current payload.
    #[prost(bool, tag="4")]
    pub replace: bool,
    #[prost(string, tag="5")]
    pub marking: ::prost::alloc::string::String,
}
// --- DeleteObject --------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub primary_key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectResponse {
    #[prost(bool, tag="1")]
    pub deleted: bool,
    /// Number of incident links removed transitively (cascade).
    #[prost(int32, tag="2")]
    pub cascaded_links: i32,
}
// --- SearchObjects -------------------------------------------------

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchObjectsRequest {
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    /// Plain-text query, matched case-insensitively against every text
    /// property of the type via ILIKE in the v1 implementation.
    #[prost(string, tag="2")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchObjectsResponse {
    #[prost(message, repeated, tag="1")]
    pub objects: ::prost::alloc::vec::Vec<ObjectInstance>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TraverseLinksRequest {
    /// The source object (by type + PK) whose neighbourhood we want.
    #[prost(string, tag="1")]
    pub object_type_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub primary_key: ::prost::alloc::string::String,
    /// Restrict the traversal to a single link type's api_name. Empty
    /// means "every link type". `link_type_api_names` overrides when set.
    #[prost(string, tag="3")]
    pub link_type_api_name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub link_type_api_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="LinkDirection", tag="5")]
    pub direction: i32,
    /// Depth in \[1, 5\]. 0 → 1.
    #[prost(int32, tag="6")]
    pub depth: i32,
    /// Optional cap on returned edges (server-side clamped). 0 → 1000.
    #[prost(int32, tag="7")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkedEdge {
    #[prost(string, tag="1")]
    pub link_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub link_type_api_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source_object_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub target_object_id: ::prost::alloc::string::String,
    #[prost(enumeration="LinkDirection", tag="5")]
    pub direction: i32,
    #[prost(int32, tag="6")]
    pub depth: i32,
    #[prost(message, optional, tag="7")]
    pub properties: ::core::option::Option<super::super::google::protobuf::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraverseLinksResponse {
    #[prost(message, repeated, tag="1")]
    pub edges: ::prost::alloc::vec::Vec<LinkedEdge>,
    /// The fully-hydrated neighbours, deduplicated by object id.
    #[prost(message, repeated, tag="2")]
    pub objects: ::prost::alloc::vec::Vec<ObjectInstance>,
}
// --- TraverseLinks -------------------------------------------------

/// LinkDirection mirrors the SPA's `ObjectSearchAroundQuery.direction`
/// values. UNSPECIFIED is treated as outgoing for backward
/// compatibility with the existing search_around handler.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LinkDirection {
    Unspecified = 0,
    Outgoing = 1,
    Incoming = 2,
    Both = 3,
}
impl LinkDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LINK_DIRECTION_UNSPECIFIED",
            Self::Outgoing => "LINK_DIRECTION_OUTGOING",
            Self::Incoming => "LINK_DIRECTION_INCOMING",
            Self::Both => "LINK_DIRECTION_BOTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LINK_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "LINK_DIRECTION_OUTGOING" => Some(Self::Outgoing),
            "LINK_DIRECTION_INCOMING" => Some(Self::Incoming),
            "LINK_DIRECTION_BOTH" => Some(Self::Both),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectType {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub primary_key_property: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub color: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub owner_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="10")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Property {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub property_type: ::prost::alloc::string::String,
    #[prost(bool, tag="7")]
    pub required: bool,
    #[prost(bool, tag="8")]
    pub unique_constraint: bool,
    #[prost(string, tag="9")]
    pub default_value_json: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub validation_rules_json: ::prost::alloc::string::String,
    #[prost(message, optional, tag="11")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="12")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkType {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub source_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="6")]
    pub target_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="7")]
    pub cardinality: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub owner_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="10")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateObjectTypeRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub primary_key_property: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub color: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetObjectTypeRequest {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListObjectTypesRequest {
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
    #[prost(string, tag="2")]
    pub search: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListObjectTypesResponse {
    #[prost(message, repeated, tag="1")]
    pub object_types: ::prost::alloc::vec::Vec<ObjectType>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateObjectTypeRequest {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub primary_key_property: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub color: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectTypeRequest {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteObjectTypeResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatePropertyRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub property_type: ::prost::alloc::string::String,
    #[prost(bool, tag="6")]
    pub required: bool,
    #[prost(bool, tag="7")]
    pub unique_constraint: bool,
    #[prost(string, tag="8")]
    pub default_value_json: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub validation_rules_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPropertiesRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPropertiesResponse {
    #[prost(message, repeated, tag="1")]
    pub properties: ::prost::alloc::vec::Vec<Property>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateLinkTypeRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub source_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="5")]
    pub target_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="6")]
    pub cardinality: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListLinkTypesRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLinkTypesResponse {
    #[prost(message, repeated, tag="1")]
    pub link_types: ::prost::alloc::vec::Vec<LinkType>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::common::PageResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteLinkTypeRequest {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteLinkTypeResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjectTypeBindingPropertyMapping {
    #[prost(string, tag="1")]
    pub source_field: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub target_property: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectTypeBinding {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="3")]
    pub dataset_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="4")]
    pub dataset_branch: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub dataset_version: i32,
    #[prost(string, tag="6")]
    pub primary_key_column: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="7")]
    pub property_mapping: ::prost::alloc::vec::Vec<ObjectTypeBindingPropertyMapping>,
    #[prost(enumeration="ObjectTypeBindingSyncMode", tag="8")]
    pub sync_mode: i32,
    #[prost(string, tag="9")]
    pub default_marking: ::prost::alloc::string::String,
    #[prost(int32, tag="10")]
    pub preview_limit: i32,
    #[prost(message, optional, tag="11")]
    pub owner_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="12")]
    pub last_materialized_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(string, tag="13")]
    pub last_run_status: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub last_run_summary_json: ::prost::alloc::string::String,
    #[prost(message, optional, tag="15")]
    pub created_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="16")]
    pub updated_at: ::core::option::Option<super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindDatasetRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub dataset_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="3")]
    pub dataset_branch: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub dataset_version: i32,
    #[prost(string, tag="5")]
    pub primary_key_column: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="6")]
    pub property_mapping: ::prost::alloc::vec::Vec<ObjectTypeBindingPropertyMapping>,
    #[prost(enumeration="ObjectTypeBindingSyncMode", tag="7")]
    pub sync_mode: i32,
    #[prost(string, tag="8")]
    pub default_marking: ::prost::alloc::string::String,
    #[prost(int32, tag="9")]
    pub preview_limit: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnbindDatasetRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub binding_id: ::core::option::Option<super::common::Uuid>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnbindDatasetResponse {
    #[prost(bool, tag="1")]
    pub deleted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MaterializeBindingRequest {
    #[prost(message, optional, tag="1")]
    pub object_type_id: ::core::option::Option<super::common::Uuid>,
    #[prost(message, optional, tag="2")]
    pub binding_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="3")]
    pub dataset_branch: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub dataset_version: i32,
    #[prost(int32, tag="5")]
    pub limit: i32,
    #[prost(bool, tag="6")]
    pub dry_run: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MaterializeBindingResponse {
    #[prost(message, optional, tag="1")]
    pub binding_id: ::core::option::Option<super::common::Uuid>,
    #[prost(string, tag="2")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub rows_read: i32,
    #[prost(int32, tag="4")]
    pub inserted: i32,
    #[prost(int32, tag="5")]
    pub updated: i32,
    #[prost(int32, tag="6")]
    pub skipped: i32,
    #[prost(int32, tag="7")]
    pub errors: i32,
    #[prost(bool, tag="8")]
    pub dry_run: bool,
    #[prost(string, repeated, tag="9")]
    pub error_details_json: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// --- ObjectType ↔ dataset bindings ---------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObjectTypeBindingSyncMode {
    Unspecified = 0,
    Snapshot = 1,
    Incremental = 2,
    View = 3,
}
impl ObjectTypeBindingSyncMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OBJECT_TYPE_BINDING_SYNC_MODE_UNSPECIFIED",
            Self::Snapshot => "OBJECT_TYPE_BINDING_SYNC_MODE_SNAPSHOT",
            Self::Incremental => "OBJECT_TYPE_BINDING_SYNC_MODE_INCREMENTAL",
            Self::View => "OBJECT_TYPE_BINDING_SYNC_MODE_VIEW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OBJECT_TYPE_BINDING_SYNC_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "OBJECT_TYPE_BINDING_SYNC_MODE_SNAPSHOT" => Some(Self::Snapshot),
            "OBJECT_TYPE_BINDING_SYNC_MODE_INCREMENTAL" => Some(Self::Incremental),
            "OBJECT_TYPE_BINDING_SYNC_MODE_VIEW" => Some(Self::View),
            _ => None,
        }
    }
}
include!("open_foundry.ontology.tonic.rs");
// @@protoc_insertion_point(module)