// @generated
// This file is @generated by prost-build.
/// Model is one row of the catalog. `rid` is the stable resource handle
/// callers reference in InvokeRequest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Model {
    #[prost(message, optional, tag="1")]
    pub rid: ::core::option::Option<super::super::common::Uuid>,
    #[prost(enumeration="Provider", tag="2")]
    pub provider: i32,
    #[prost(string, tag="3")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub context_window: i32,
    #[prost(double, tag="6")]
    pub input_cost_per_1k: f64,
    #[prost(double, tag="7")]
    pub output_cost_per_1k: f64,
    #[prost(enumeration="Capability", repeated, tag="8")]
    pub capabilities: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag="9")]
    pub enabled: bool,
    #[prost(message, optional, tag="10")]
    pub created_at: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="11")]
    pub updated_at: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterModelRequest {
    #[prost(enumeration="Provider", tag="1")]
    pub provider: i32,
    #[prost(string, tag="2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub context_window: i32,
    #[prost(double, tag="5")]
    pub input_cost_per_1k: f64,
    #[prost(double, tag="6")]
    pub output_cost_per_1k: f64,
    #[prost(enumeration="Capability", repeated, tag="7")]
    pub capabilities: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, tag="8")]
    pub enabled: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {
    /// Optional filters. Empty = no filter.
    #[prost(enumeration="Provider", tag="1")]
    pub provider: i32,
    #[prost(bool, tag="2")]
    pub only_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<Model>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelRequest {
    #[prost(message, optional, tag="1")]
    pub rid: ::core::option::Option<super::super::common::Uuid>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnableModelRequest {
    #[prost(message, optional, tag="1")]
    pub rid: ::core::option::Option<super::super::common::Uuid>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisableModelRequest {
    #[prost(message, optional, tag="1")]
    pub rid: ::core::option::Option<super::super::common::Uuid>,
}
/// Wire-compatible chat message — mirrors the OpenAI chat-completions
/// shape so apps/web speaks one schema across providers.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Message {
    /// system | user | assistant | tool
    #[prost(string, tag="1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
}
/// Tool definition (registered for forward-compat — v1 does not execute
/// tools, it just round-trips the schema).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Tool {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub parameters_json_schema: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvokeRequest {
    #[prost(message, optional, tag="1")]
    pub model_rid: ::core::option::Option<super::super::common::Uuid>,
    #[prost(message, repeated, tag="2")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(int32, tag="3")]
    pub max_tokens: i32,
    #[prost(float, tag="4")]
    pub temperature: f32,
    #[prost(message, repeated, tag="5")]
    pub tools: ::prost::alloc::vec::Vec<Tool>,
    /// hint; server-side stream uses InvokeStream
    #[prost(bool, tag="6")]
    pub stream: bool,
}
/// Usage block mirrors OpenAI {prompt_tokens, completion_tokens,
/// total_tokens}. completion_tokens is filled from provider counts when
/// available, otherwise estimated.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Usage {
    #[prost(int32, tag="1")]
    pub prompt_tokens: i32,
    #[prost(int32, tag="2")]
    pub completion_tokens: i32,
    #[prost(int32, tag="3")]
    pub total_tokens: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvokeResponse {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(message, optional, tag="2")]
    pub usage: ::core::option::Option<Usage>,
    /// echo for client correlation
    #[prost(string, tag="3")]
    pub model_rid: ::prost::alloc::string::String,
    #[prost(double, tag="4")]
    pub cost_usd: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvokeStreamChunk {
    /// token / partial content
    #[prost(string, tag="1")]
    pub delta: ::prost::alloc::string::String,
    /// last chunk for the stream
    #[prost(bool, tag="2")]
    pub done: bool,
    /// populated on the last chunk only
    #[prost(message, optional, tag="3")]
    pub usage: ::core::option::Option<Usage>,
}
/// Provider enumeration. Anthropic and OpenAI-compatible (also covers
/// Ollama and vLLM via the chat_completions API mode) are wired in v1;
/// BEDROCK is reserved — registration succeeds, invocation returns
/// UNIMPLEMENTED.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Provider {
    Unspecified = 0,
    Anthropic = 1,
    Openai = 2,
    Ollama = 3,
    Bedrock = 4,
}
impl Provider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROVIDER_UNSPECIFIED",
            Self::Anthropic => "ANTHROPIC",
            Self::Openai => "OPENAI",
            Self::Ollama => "OLLAMA",
            Self::Bedrock => "BEDROCK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "ANTHROPIC" => Some(Self::Anthropic),
            "OPENAI" => Some(Self::Openai),
            "OLLAMA" => Some(Self::Ollama),
            "BEDROCK" => Some(Self::Bedrock),
            _ => None,
        }
    }
}
/// Capabilities advertised by a registered model. Capability filtering is
/// applied at the planner layer; the invoke handler does not enforce.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Capability {
    Unspecified = 0,
    Text = 1,
    Vision = 2,
    Tools = 3,
}
impl Capability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CAPABILITY_UNSPECIFIED",
            Self::Text => "TEXT",
            Self::Vision => "VISION",
            Self::Tools => "TOOLS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CAPABILITY_UNSPECIFIED" => Some(Self::Unspecified),
            "TEXT" => Some(Self::Text),
            "VISION" => Some(Self::Vision),
            "TOOLS" => Some(Self::Tools),
            _ => None,
        }
    }
}
include!("open_foundry.ai.v1.tonic.rs");
// @@protoc_insertion_point(module)