// @generated
// This file is @generated by prost-build.
/// AuditEvent is the canonical row shape returned by the query API.
/// Field tags are stable; new optional fields may be appended.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditEvent {
    #[prost(string, tag="1")]
    pub event_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub occurred_at: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
    #[prost(string, tag="3")]
    pub kind: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub categories: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub resource_rid: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub project_rid: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="9")]
    pub markings_at_event: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="10")]
    pub source_service: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub correlation_id: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub user_agent: ::prost::alloc::string::String,
    /// payload is the JSON-encoded variant body.
    #[prost(bytes="vec", tag="15")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordEventRequest {
    /// Either provide the structured fields below…
    #[prost(message, optional, tag="1")]
    pub event: ::core::option::Option<AuditEvent>,
    /// …or the raw envelope bytes already produced by libs/audit-trail.
    /// When both are set, raw_envelope wins.
    #[prost(bytes="vec", tag="2")]
    pub raw_envelope: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordEventResponse {
    #[prost(string, tag="1")]
    pub event_id: ::prost::alloc::string::String,
}
/// QueryEventsRequest filters the audit_events table.
/// All filter fields are AND-combined. Empty/zero values mean "no
/// constraint". `page_size` is clamped to \[1, 1000\] server-side;
/// pagination uses an opaque `next_cursor` cursor (created_at,event_id).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryEventsRequest {
    #[prost(string, tag="1")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub resource_rid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub action: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub from: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub to: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
    #[prost(int32, tag="6")]
    pub page_size: i32,
    #[prost(string, tag="7")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryEventsResponse {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<AuditEvent>,
    #[prost(string, tag="2")]
    pub next_cursor: ::prost::alloc::string::String,
}
/// ExportEvents streams NDJSON-encoded events. Each AuditEventExport
/// frame carries one event's bytes (`event_ndjson`), allowing clients
/// to write straight to disk without re-encoding.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportEventsRequest {
    #[prost(string, tag="1")]
    pub actor_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub resource_rid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub action: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub from: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub to: ::core::option::Option<super::super::super::google::protobuf::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuditEventExport {
    #[prost(bytes="vec", tag="1")]
    pub event_ndjson: ::prost::alloc::vec::Vec<u8>,
}
include!("open_foundry.audit.v1.tonic.rs");
// @@protoc_insertion_point(module)